import type { Metadata } from 'next';
import { StaticPage } from '@/components/StaticPage';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The rules for using R2BOT — written in plain English.',
};

export default function TermsPage() {
  return (
    <StaticPage
      eyebrow="Terms · The rules"
      title="Terms of Service, in plain English."
      lede="The boring-but-necessary contract for using R2BOT. We've stripped the legalese where we can. The short version is at the top of each section."
    >
      <p style={{ fontSize: 13, color: 'var(--muted)' }}>Last updated: 19 May 2026.</p>

      <h2>1. What R2BOT is</h2>
      <p>
        R2BOT is a free educational platform about robotics, operated by Ravi Bohra as a sole
        proprietor based in India. By using R2BOT (the website at r2bot.com or any subdomain,
        the API, R2 Co-pilot, and any associated services), you agree to these Terms.
      </p>

      <h2>2. Free use, free of guarantees</h2>
      <ul>
        <li>R2BOT is free for personal, educational use.</li>
        <li>Content is provided &quot;as-is&quot; without warranty. We work hard to keep it accurate, but we may be wrong.</li>
        <li>R2 Co-pilot is an AI assistant. It may occasionally produce inaccurate or incomplete answers. Don&apos;t use it as the sole source of decisions that matter (medical, legal, safety, engineering).</li>
        <li>We&apos;re not liable for losses arising from your reliance on R2BOT content. If you build a real robot from R2BOT lessons and it falls on your foot, that&apos;s on you.</li>
      </ul>

      <h2>3. Account responsibilities</h2>
      <p>If you create an account:</p>
      <ul>
        <li>You&apos;re responsible for keeping your password safe.</li>
        <li>You won&apos;t share your account with others.</li>
        <li>You&apos;ll give us a real email address you can receive at.</li>
        <li>You won&apos;t pretend to be someone else.</li>
        <li>If you&apos;re under 18, please use the platform with a parent or guardian.</li>
      </ul>

      <h2>4. What you can and can&apos;t do</h2>
      <p><strong>You can:</strong></p>
      <ul>
        <li>Read, share, and link to anything on R2BOT freely.</li>
        <li>Quote Atlas entries with attribution (e.g., &quot;Source: R2BOT&quot; and a link).</li>
        <li>Embed our public widgets (when we ship them).</li>
        <li>Use the platform for non-commercial educational purposes — including in schools and colleges — for free.</li>
      </ul>

      <p><strong>You can&apos;t:</strong></p>
      <ul>
        <li>Scrape the entire Atlas or Pulse archive in bulk for commercial purposes.</li>
        <li>Train an AI model on R2BOT content without our written permission.</li>
        <li>Reproduce R2BOT content on another site without attribution.</li>
        <li>Use R2 Co-pilot for illegal activity, harassment, or large-scale automated abuse.</li>
        <li>Reverse-engineer, hack, probe for vulnerabilities, or DDoS R2BOT.</li>
        <li>Misrepresent R2BOT&apos;s relationship with you (e.g., claim to be an employee or partner when you&apos;re not).</li>
      </ul>

      <h2>5. R2 Co-pilot and AI-generated content</h2>
      <ul>
        <li>R2 Co-pilot uses Anthropic&apos;s Claude API. Responses are generated by AI in real time.</li>
        <li>AI responses may contain mistakes, omissions, or outdated information.</li>
        <li>R2BOT does not own AI responses — they&apos;re generated for you, in real time, and you may use them as you would any tool&apos;s output.</li>
        <li>R2BOT will not knowingly use AI to produce illegal, discriminatory, or harmful content. If R2 Co-pilot ever does, please report it.</li>
      </ul>

      <h2>6. Content you contribute</h2>
      <p>
        If you ever submit content to R2BOT (a comment, a correction, a community post — though
        we don&apos;t currently support these), you grant us a non-exclusive, worldwide, royalty-free
        licence to publish, edit, and remove it. You confirm you have the right to grant this licence.
      </p>

      <h2>7. Changes to the service</h2>
      <p>
        R2BOT is evolving. We may add, change, or remove features at any time. Major changes
        affecting paid services or your data will be announced in advance.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can stop using R2BOT at any time. You can delete your account by emailing
        <strong> ravi6703@gmail.com</strong>. We can suspend or terminate any account that violates these
        Terms. If we do, we&apos;ll tell you why.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These Terms are governed by the laws of India. Disputes will be resolved in the courts
        of Bengaluru, Karnataka. If you&apos;re using R2BOT from outside India and a local law
        gives you rights that conflict with these Terms, the local law wins for that conflict only.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms? Email <strong>ravi6703@gmail.com</strong>.
      </p>
    </StaticPage>
  );
}
