// lib/daily-life-data.ts
// 60 personalised use cases for /daily-life — robots already running your life.

export type ProfileId =
  | 'student'
  | 'farmer'
  | 'doctor-nurse'
  | 'factory-worker'
  | 'homemaker'
  | 'driver'
  | 'office-worker'
  | 'engineer';

export type DomainId =
  | 'healthcare'
  | 'agriculture'
  | 'home'
  | 'finance'
  | 'transport'
  | 'entertainment'
  | 'education'
  | 'manufacturing'
  | 'shopping'
  | 'food-delivery';

export type Difficulty = 'invisible' | 'simple' | 'complex';

export const PROFILES: { id: ProfileId; label: string; emoji: string }[] = [
  { id: 'student', label: 'Student', emoji: '🎓' },
  { id: 'farmer', label: 'Farmer', emoji: '👨‍🌾' },
  { id: 'doctor-nurse', label: 'Doctor / Nurse', emoji: '🏥' },
  { id: 'factory-worker', label: 'Factory Worker', emoji: '🏭' },
  { id: 'homemaker', label: 'Homemaker', emoji: '🏠' },
  { id: 'driver', label: 'Driver', emoji: '🚗' },
  { id: 'office-worker', label: 'Office Worker', emoji: '💼' },
  { id: 'engineer', label: 'Engineer', emoji: '🏗️' },
];

export const DOMAINS: { id: DomainId; label: string; emoji: string }[] = [
  { id: 'healthcare', label: 'Healthcare', emoji: '🏥' },
  { id: 'agriculture', label: 'Agriculture', emoji: '🌾' },
  { id: 'home', label: 'Home & Kitchen', emoji: '🏠' },
  { id: 'finance', label: 'Finance & Banking', emoji: '💰' },
  { id: 'transport', label: 'Transport', emoji: '🚗' },
  { id: 'entertainment', label: 'Entertainment', emoji: '📱' },
  { id: 'education', label: 'Education', emoji: '🏫' },
  { id: 'manufacturing', label: 'Manufacturing', emoji: '🏭' },
  { id: 'shopping', label: 'Shopping', emoji: '🛒' },
  { id: 'food-delivery', label: 'Food & Delivery', emoji: '🍕' },
];

export interface UseCase {
  id: string;
  title: string;
  emoji: string;
  imageEmoji: string;
  hookLine: string;
  profiles: (ProfileId | 'everyone')[];
  domains: DomainId[];
  howItWorks: string;
  analogyExplanation: string;
  mindBlowingFact: string;
  costImpact?: string;
  simulationLink?: string;
  atlasLink?: string;
  difficulty: Difficulty;

  // ── v2 reimagining (May 2026) ──
  /** Illustration or photo URL. */
  robotImage?: string;
  /** Specific real-world product (e.g. "iRobot Roomba", "Da Vinci"). */
  realProduct?: string;
  /** When during the day this robot typically shows up. */
  timeOfDay?: 'morning' | 'afternoon' | 'evening' | 'night' | 'anytime';
  /** India-specific example / statistic. */
  indianContext?: string;
  /** Tweet-length surprising fact (distinct from mindBlowingFact). */
  funFact?: string;
  /** YouTube clip ID (30–90 second demo). */
  videoId?: string;
  /** If true, only revealed when reached in story mode. */
  isHidden?: boolean;
}

export const USE_CASES: UseCase[] = [
  // EVERYONE
  {
    id: 'atm',
    title: 'The ATM Machine',
    emoji: '🏧',
    imageEmoji: '🏧',
    hookLine: "You think it's a machine. It's a robot counting your cash by hand.",
    profiles: ['everyone'],
    domains: ['finance'],
    howItWorks: "An ATM reads your card, authenticates you, and uses motors and optical sensors to count and dispense exact notes from sorted cassettes.",
    analogyExplanation: "Think of it like a vending machine that knows you by name, holds your money safely, and never makes a counting mistake.",
    mindBlowingFact: 'India has 250,000+ ATMs. Each replaces the work of 3 full-time bank tellers — that\'s 750,000 jobs quietly automated by 1970s robotics.',
    costImpact: 'Saves banks ₹2,000–5,000 per transaction vs human teller.',
    difficulty: 'invisible',
    atlasLink: '/atlas/concept/sensor-fusion',
  },
  {
    id: 'elevator',
    title: 'The Elevator AI',
    emoji: '🛗',
    imageEmoji: '🛗',
    hookLine: 'Every time you press a floor button, an AI is making routing decisions.',
    profiles: ['everyone'],
    domains: ['home', 'transport'],
    howItWorks: 'Modern elevators run shortest-path scheduling across all cars in a building, predict foot traffic, and dispatch the optimal car.',
    analogyExplanation: 'Think of it like a tiny brain inside the wall that handles the entire building\'s traffic, smarter than any human dispatcher.',
    mindBlowingFact: 'Otis and Kone elevator AIs handle 15 billion rides per day worldwide — the world\'s most-used robotic transport system.',
    costImpact: 'Reduces wait time 30–50% vs simple first-come-first-serve.',
    difficulty: 'invisible',
  },
  {
    id: 'upi',
    title: 'Your UPI Payment',
    emoji: '💸',
    imageEmoji: '💸',
    hookLine: 'Every ₹ you send via UPI passes through 50+ robot checks in milliseconds.',
    profiles: ['everyone'],
    domains: ['finance'],
    howItWorks: 'UPI fraud-detection AIs scan for unusual patterns; settlement engines automatically transfer funds between banks in real time.',
    analogyExplanation: 'Imagine 50 invisible bouncers checking your payment in 200 milliseconds — that\'s UPI under the hood.',
    mindBlowingFact: 'India processes 10 billion UPI transactions per month — 3,300 per second at peak. Doing this manually would need 2 million bank clerks working 24/7.',
    difficulty: 'invisible',
    atlasLink: '/atlas/concept/neural-network',
  },
  {
    id: 'airport-xray',
    title: 'Airport Security X-ray',
    emoji: '🧳',
    imageEmoji: '🛂',
    hookLine: 'The X-ray that scans your bag uses AI trained on millions of bag images.',
    profiles: ['everyone'],
    domains: ['transport'],
    howItWorks: 'X-ray machines combine multiple energy levels and AI classifiers to identify shapes and materials — flagging anything suspicious for human review.',
    analogyExplanation: 'It\'s like a doctor who sees through your bag and instantly knows whether the inside contains a phone, a knife, or a bottle of water.',
    mindBlowingFact: 'Bengaluru International alone scans 50,000+ bags per day using AI X-ray robots; the system catches 99.9% of prohibited items.',
    difficulty: 'simple',
  },
  {
    id: 'traffic-signals',
    title: 'Traffic Signal AI',
    emoji: '🚦',
    imageEmoji: '🚦',
    hookLine: 'Indian city traffic signals are increasingly run by AI that adapts to live traffic.',
    profiles: ['everyone'],
    domains: ['transport'],
    howItWorks: 'Cameras count vehicles at each junction; AI adjusts signal timing every cycle to minimise overall wait time.',
    analogyExplanation: 'Picture a traffic constable with x-ray vision who sees every junction in the city at once — and never blinks.',
    mindBlowingFact: 'Bengaluru\'s ITMS (Intelligent Traffic Management System) handles 380+ signals via AI; average wait time has dropped 30%.',
    costImpact: 'Cuts city fuel use by ~5% across automated zones.',
    difficulty: 'simple',
  },
  {
    id: 'weather-forecast',
    title: 'Weather Forecasting Compute',
    emoji: '🌦️',
    imageEmoji: '🌦️',
    hookLine: 'The 5-day forecast you check every morning runs on a supercomputer the size of a building.',
    profiles: ['everyone'],
    domains: ['everyone' as never],
    howItWorks: 'Massive parallel compute solves fluid-dynamics equations across a 3D atmospheric grid every few hours.',
    analogyExplanation: 'Think of it like a giant chess engine that plays out millions of possible weather futures, then averages them.',
    mindBlowingFact: 'India\'s Pratyush supercomputer (Pune) does 6.8 PetaFLOPS — 6.8 million billion calculations per second — just to predict tomorrow\'s rain.',
    difficulty: 'complex',
  },
  {
    id: 'google-search',
    title: 'Google Search',
    emoji: '🔎',
    imageEmoji: '🔎',
    hookLine: 'Every search you type triggers 200+ algorithms ranking 100 billion pages.',
    profiles: ['everyone'],
    domains: ['entertainment'],
    howItWorks: 'A neural network reads your query, retrieves relevant documents from a massive index, and ranks them in <0.5 seconds.',
    analogyExplanation: 'It\'s like asking a librarian who has read every book in the world and answers in half a second.',
    mindBlowingFact: 'Google handles 8.5 billion searches a day. The same compute that ranks a single search would have cost ₹50 crore in the 1990s.',
    difficulty: 'complex',
    atlasLink: '/atlas/concept/transformer-architecture',
  },
  {
    id: 'phone-autocorrect',
    title: 'Your Phone Autocorrect',
    emoji: '⌨️',
    imageEmoji: '📱',
    hookLine: 'Every time autocorrect changes "definately" to "definitely", an AI is reading your mind.',
    profiles: ['everyone'],
    domains: ['entertainment'],
    howItWorks: 'A neural language model predicts the next word based on the previous 200+ characters you typed.',
    analogyExplanation: 'Picture a tiny librarian inside your phone who has read every text message ever sent and guesses what you meant.',
    mindBlowingFact: 'The autocorrect on your phone runs the same kind of transformer model that powers ChatGPT — just smaller.',
    difficulty: 'simple',
    atlasLink: '/atlas/concept/transformer-architecture',
  },
  {
    id: 'netflix-recommendations',
    title: 'Netflix / Hotstar Recommendations',
    emoji: '🎬',
    imageEmoji: '🎬',
    hookLine: "The 'because you watched' row is built by a neural network that knows your taste.",
    profiles: ['everyone'],
    domains: ['entertainment'],
    howItWorks: 'A recommendation AI compares your watch history against millions of others, then ranks shows by how likely you are to enjoy them.',
    analogyExplanation: "Think of it like a friend who has watched every show on Earth and knows exactly what you'll like next.",
    mindBlowingFact: '80% of what people watch on Netflix is from algorithmic recommendations — not search.',
    difficulty: 'complex',
  },
  {
    id: 'spam-filter',
    title: 'Email Spam Filter',
    emoji: '📧',
    imageEmoji: '🚫',
    hookLine: 'Your email inbox quietly kills 100+ spam messages a day on your behalf.',
    profiles: ['everyone'],
    domains: ['entertainment'],
    howItWorks: 'A neural classifier scores every incoming message on 1000+ features and silently filters out anything that looks like spam or phishing.',
    analogyExplanation: 'It\'s like a bouncer at your inbox door checking 100 IDs per second and only letting in the real guests.',
    mindBlowingFact: 'Gmail blocks 100 million phishing emails a day using a single ML model — invisible to every Gmail user.',
    difficulty: 'invisible',
  },

  // HOMEMAKER
  {
    id: 'roomba',
    title: 'Robot Vacuum',
    emoji: '🧹',
    imageEmoji: '🧹',
    hookLine: 'Your Roomba uses the same path-planning maths as Mars rovers.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'A Roomba uses cliff sensors, bump sensors, and (in newer models) LIDAR to map your home and plan an efficient cleaning route.',
    analogyExplanation: 'Imagine a tiny self-driving car with a vacuum — it knows your floor better than you do.',
    mindBlowingFact: 'iRobot has sold over 40 million Roombas — robotics has quietly entered tens of millions of households.',
    simulationLink: '/visualizer#astar',
    atlasLink: '/atlas/concept/visual-slam',
    difficulty: 'simple',
  },
  {
    id: 'washing-machine',
    title: 'Washing Machine Drum AI',
    emoji: '🧺',
    imageEmoji: '🧺',
    hookLine: 'Your washing machine senses load weight and decides water and spin speed.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'Sensors detect load weight, water level, and fabric type; the controller adjusts wash and spin cycles in real time.',
    analogyExplanation: 'Think of it like a tailor weighing fabric in their hands before deciding how to wash it — done in milliseconds, automatically.',
    mindBlowingFact: 'Modern Indian washing machines run a fuzzy-logic controller invented in Japan in the 1980s — robotics that hides as a "spin" knob.',
    atlasLink: '/atlas/concept/fuzzy-logic',
    difficulty: 'invisible',
  },
  {
    id: 'smart-ac',
    title: 'Smart AC Temperature Control',
    emoji: '❄️',
    imageEmoji: '❄️',
    hookLine: 'Your AC predicts when you\'ll feel hot — before you do.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'Temperature and humidity sensors feed a PID controller that adjusts compressor speed to maintain target comfort.',
    analogyExplanation: 'Imagine a tiny weather forecaster inside your AC that decides every 10 seconds whether to cool harder or chill out.',
    mindBlowingFact: 'A modern inverter AC adjusts its cooling 1,000+ times per minute using the same PID control that lands rockets.',
    simulationLink: '/visualizer#pid',
    atlasLink: '/atlas/concept/pid-controller',
    difficulty: 'invisible',
  },
  {
    id: 'microwave',
    title: 'Microwave Magnetron',
    emoji: '🔥',
    imageEmoji: '🔥',
    hookLine: 'Your microwave fires microwaves at 2.45 GHz in microsecond-precise bursts.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'A magnetron emits microwaves; a timer + sensor regulates power level by switching the magnetron on and off in precise pulses.',
    analogyExplanation: 'Picture a tiny disco-light operator inside your microwave who switches the lights on/off thousands of times per second — except the lights are heat.',
    mindBlowingFact: 'Microwave cooking was invented when Percy Spencer noticed a chocolate bar melted in his pocket near a radar — 1945.',
    difficulty: 'invisible',
  },
  {
    id: 'dishwasher',
    title: 'Dishwasher Spray Arm',
    emoji: '🍽️',
    imageEmoji: '🍽️',
    hookLine: 'Your dishwasher\'s spray arm follows a precise robotic pattern.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'Water pressure spins the spray arm; a turbidity sensor checks if dishes are clean and tells the controller when to drain.',
    analogyExplanation: 'Imagine a robotic chef pressure-washing dishes from below, deciding for itself when they\'re clean enough to stop.',
    mindBlowingFact: 'A modern dishwasher uses ~10 litres for a full load vs 40+ litres for hand washing — robotics literally saves Indian water.',
    difficulty: 'invisible',
  },
  {
    id: 'water-purifier',
    title: 'Water Purifier UV Arm',
    emoji: '💧',
    imageEmoji: '💧',
    hookLine: 'Inside your Aquaguard, a UV-light arm zaps every microbe at the speed of light.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home', 'healthcare'],
    howItWorks: 'Water flows past a UV LED tube; sensors track flow rate and ensure water gets enough UV dose to kill bacteria and viruses.',
    analogyExplanation: 'It\'s like a tiny bouncer with a UV flashlight zapping every germ on every drop of water before you drink it.',
    mindBlowingFact: 'A single UV-purifier arm kills 99.9999% of E. coli in 6 seconds — robotics-grade precision in your kitchen.',
    difficulty: 'invisible',
  },
  {
    id: 'smart-fridge',
    title: 'Smart Fridge Inventory',
    emoji: '🧊',
    imageEmoji: '🧊',
    hookLine: 'Modern fridges use cameras to know what\'s inside — no opening required.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'Internal cameras photograph shelves; a computer-vision model identifies each item and tracks expiry dates.',
    analogyExplanation: 'Imagine your fridge having three CCTV cameras that text you when the milk is about to expire.',
    mindBlowingFact: 'Samsung\'s Family Hub fridge runs object-detection AI on 3 internal cameras — the same neural network used in cars.',
    atlasLink: '/atlas/concept/object-detection',
    difficulty: 'simple',
  },
  {
    id: 'sewing-machine',
    title: 'Industrial Sewing Robot',
    emoji: '🧵',
    imageEmoji: '🧵',
    hookLine: 'The shirt you\'re wearing was sewn by a robot stitching 5,000 stitches per minute.',
    profiles: ['homemaker', 'factory-worker'],
    domains: ['home', 'manufacturing'],
    howItWorks: 'Industrial sewing robots use precision servo motors and computer-vision-guided needle placement to stitch garments at 5,000+ stitches per minute.',
    analogyExplanation: 'Imagine 10 nimble robot fingers stitching faster than your eyes can track — that\'s what made your t-shirt.',
    mindBlowingFact: 'India\'s textile industry uses 400,000+ industrial sewing robots; Tirupur and Bengaluru together export $40+ billion worth.',
    difficulty: 'simple',
  },
  {
    id: 'gas-leak',
    title: 'Gas Leak Auto-Shutoff',
    emoji: '🚨',
    imageEmoji: '🚨',
    hookLine: 'Modern Indian gas stoves quietly listen for leaks and shut themselves off.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'Gas sensors detect methane or LPG leaks; a microcontroller closes the gas valve and triggers an alarm.',
    analogyExplanation: 'Imagine a tiny nose inside your kitchen that smells gas faster than you can — and shuts off the supply for you.',
    mindBlowingFact: 'India\'s Bureau of Indian Standards now mandates auto-shutoff valves in new LPG installations from 2024 — robotics protecting lives.',
    difficulty: 'invisible',
  },
  {
    id: 'security-cam',
    title: 'Security Camera Motion AI',
    emoji: '📹',
    imageEmoji: '📹',
    hookLine: 'CCTV cameras in your apartment compound run AI 24/7 — and only alert you when something matters.',
    profiles: ['homemaker', 'everyone'],
    domains: ['home'],
    howItWorks: 'On-camera AI distinguishes people from pets and packages, sends alerts only when relevant, and stores clips in the cloud.',
    analogyExplanation: 'Think of it like a tireless security guard who never blinks, watches every door at once, and only wakes you for real intrusions.',
    mindBlowingFact: 'The Bengaluru police\'s Safe City Project runs CCTV AI across 4,000+ cameras detecting unattended bags in real time.',
    atlasLink: '/atlas/concept/object-detection',
    difficulty: 'simple',
  },

  // FARMER
  {
    id: 'drip-irrigation',
    title: 'Drip Irrigation Sensors',
    emoji: '🌱',
    imageEmoji: '🌱',
    hookLine: 'Modern drip systems water plants only when the soil tells them to.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Soil-moisture sensors trigger valves; a microcontroller calculates exact water deficit and opens specific zone valves.',
    analogyExplanation: 'Imagine a robot that walks every plant in your farm and decides how thirsty it is — except it does this 24/7 silently.',
    mindBlowingFact: 'India has deployed automated drip on 5M+ hectares under PMKSY — saves 50% water and boosts yield 30%.',
    costImpact: 'Saves ₹40,000/year per hectare on water + ₹15,000 on power.',
    difficulty: 'simple',
  },
  {
    id: 'drone-spray',
    title: 'Crop-Spraying Drone',
    emoji: '🚁',
    imageEmoji: '🚁',
    hookLine: 'Drones spray your crops 20× faster than manual labour.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Multirotor drones with 10–16 L tanks follow GPS waypoints and spray pesticide with millimetric accuracy via centrifugal nozzles.',
    analogyExplanation: 'Imagine your farm labourer flying — and finishing 5 acres of spraying in 15 minutes.',
    mindBlowingFact: 'Garuda Aerospace has deployed 1,000+ Kisan Drones in India under the Drone Shakti scheme.',
    costImpact: 'Reduces pesticide use 40%; saves labour cost ₹500/acre.',
    difficulty: 'complex',
    atlasLink: '/atlas/concept/spraying-drone',
  },
  {
    id: 'soil-sensors',
    title: 'Robotic Soil-Moisture Sensors',
    emoji: '🪴',
    imageEmoji: '🪴',
    hookLine: 'Tiny sensors buried in your field text the cloud every 15 minutes.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Capacitive moisture sensors send readings via LoRa or 4G to a cloud platform; AI predicts when to irrigate.',
    analogyExplanation: 'Picture tiny robot fingers stuck in the soil, calling you every 15 minutes to report how thirsty the field feels.',
    mindBlowingFact: 'Cropin (Bengaluru) serves 12M+ Indian farmers with real-time soil-sensor + satellite data.',
    atlasLink: '/atlas/concept/precision-agriculture',
    difficulty: 'simple',
  },
  {
    id: 'grain-sorting',
    title: 'Optical Grain Sorting',
    emoji: '🌾',
    imageEmoji: '🌾',
    hookLine: 'Robotic eyes spot 600 grain defects per second using high-speed cameras.',
    profiles: ['farmer'],
    domains: ['agriculture', 'food-delivery'],
    howItWorks: 'A camera shoots 600 frames per second; AI identifies discoloured grains, rocks, or foreign matter; air jets eject rejects with microsecond timing.',
    analogyExplanation: 'Imagine a sorter who looks at 10 tonnes of rice an hour, never blinks, and never lets a single bad grain through.',
    mindBlowingFact: 'India processes 120M tonnes of rice/year. Without robotic sorting, you\'d find small stones in your biryani regularly.',
    difficulty: 'simple',
  },
  {
    id: 'tractor-gps',
    title: 'GPS Auto-Steering Tractor',
    emoji: '🚜',
    imageEmoji: '🚜',
    hookLine: 'Modern tractors steer themselves — the farmer just supervises.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'RTK-GPS gives centimetre-accurate position; auto-steer keeps the tractor on perfect parallel rows day or night.',
    analogyExplanation: 'It\'s like Tesla Autopilot but on a tractor — except it can drive on muddy fields with zero road markings.',
    mindBlowingFact: 'Mahindra\'s smart tractors with auto-steer cut driver fatigue 70% and improve fuel economy 15%.',
    atlasLink: '/atlas/concept/gps-module',
    difficulty: 'complex',
  },
  {
    id: 'mushroom-robot',
    title: 'Mushroom Harvesting Robot',
    emoji: '🍄',
    imageEmoji: '🍄',
    hookLine: 'Japan\'s mushroom farms run on robots that pick 1,000 mushrooms per hour.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Vision systems identify ripe mushrooms; soft grippers pluck them without crushing; a conveyor sorts by size.',
    analogyExplanation: 'Imagine a robotic farmhand with the precision of a surgeon picking only the perfectly ripe ones.',
    mindBlowingFact: 'A single mushroom harvesting robot replaces ~25 human pickers and works 24/7 in humid greenhouses.',
    difficulty: 'complex',
  },
  {
    id: 'milking-robot',
    title: 'Cow Milking Robot',
    emoji: '🐄',
    imageEmoji: '🐄',
    hookLine: 'Robotic milking parlours run 24/7 — cows queue up by themselves.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Cows walk into a stall when they want to be milked; sensors locate teats; robotic arms attach milk cups automatically.',
    analogyExplanation: 'Picture a Starbucks for cows — the cow walks in, gets milked, and walks out, no human required.',
    mindBlowingFact: 'Punjab and Gujarat dairy cooperatives are piloting robotic milking; cow yield rises ~10% from stress-free milking.',
    difficulty: 'complex',
  },
  {
    id: 'pest-detection',
    title: 'Pest Detection Thermal Drone',
    emoji: '🦗',
    imageEmoji: '🦗',
    hookLine: 'Thermal drones spot crop disease before your eyes can — by 2 weeks.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Thermal cameras detect plants under heat stress (often an early sign of disease); ground robots spray treatment only where needed.',
    analogyExplanation: 'Imagine an x-ray for your field — you can see the sick plants weeks before they look sick.',
    mindBlowingFact: 'Indian agri startups use thermal drones to spot rice blast disease 14 days before farmers can — saving entire crops.',
    atlasLink: '/atlas/concept/thermal-camera',
    difficulty: 'complex',
  },
  {
    id: 'cold-chain',
    title: 'Cold-Chain Logistics Robot',
    emoji: '🧊',
    imageEmoji: '🧊',
    hookLine: 'Your tomatoes travel from farm to Mumbai mandi in a robotic refrigerated truck.',
    profiles: ['farmer'],
    domains: ['agriculture', 'shopping'],
    howItWorks: 'Refrigerated containers have sensors that maintain a precise temperature; automated routing systems plan optimal delivery paths.',
    analogyExplanation: 'Imagine your tomatoes inside a portable refrigerator that texts the driver if it gets too warm.',
    mindBlowingFact: 'India\'s cold-chain network has grown from 5,000 reefer trucks in 2015 to 50,000+ in 2025 — cutting food waste 30%.',
    difficulty: 'simple',
  },
  {
    id: 'mandi-ai',
    title: 'Mandi Price Prediction AI',
    emoji: '📈',
    imageEmoji: '📈',
    hookLine: 'Apps now predict tomorrow\'s mandi price using satellite + AI.',
    profiles: ['farmer'],
    domains: ['agriculture'],
    howItWorks: 'Satellite crop-yield estimates, weather data, and historical prices feed a neural network that forecasts next-week prices.',
    analogyExplanation: 'Picture a stockbroker who studies satellite photos of every Indian farm and tells you when to sell your harvest.',
    mindBlowingFact: 'AgriBazaar\'s price-prediction AI is used by 1 million+ Indian farmers and shifts harvest timing nationally.',
    difficulty: 'complex',
  },

  // DOCTOR / NURSE
  {
    id: 'blood-test',
    title: 'Blood Test Lab Robots',
    emoji: '🩸',
    imageEmoji: '🩸',
    hookLine: 'Your blood is tested entirely by robots — a human never touches your sample.',
    profiles: ['doctor-nurse', 'everyone'],
    domains: ['healthcare'],
    howItWorks: 'A robotic track carries your sample to centrifuges, robotic pipettors, and analysers that run 50+ tests simultaneously.',
    analogyExplanation: 'Imagine your sample on a conveyor belt at an Amazon warehouse — except every station runs a chemistry test.',
    mindBlowingFact: 'SRL Diagnostics processes 100,000+ samples a day fully robotically — manually that would take 600 years per day of human work.',
    difficulty: 'complex',
  },
  {
    id: 'pharmacy-robot',
    title: 'Hospital Pharmacy Robot',
    emoji: '💊',
    imageEmoji: '💊',
    hookLine: 'Hospital pharmacies dispense prescriptions in 60 seconds — by robot.',
    profiles: ['doctor-nurse', 'homemaker'],
    domains: ['healthcare'],
    howItWorks: 'Drug carousels store 200+ medicines; robotic arms with vacuum grippers pick exact pills, verify by barcode, and dispense labelled packets.',
    analogyExplanation: 'Imagine a vending machine for medicines that never picks the wrong pill — for 5,000 prescriptions a day.',
    mindBlowingFact: 'Apollo Hospitals\' dispensing robot handles 5,000 prescriptions a day — replacing 20 full-time pharmacists.',
    costImpact: 'Dispensing errors drop from 1-in-100 (human) to 1-in-1,000,000 (robot).',
    difficulty: 'complex',
  },
  {
    id: 'da-vinci-surgery',
    title: 'da Vinci Surgical Robot',
    emoji: '🩺',
    imageEmoji: '🩺',
    hookLine: 'Your surgeon controls a robot whose hands don\'t shake.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'Surgeon sits at a 3D console; hand controls drive robotic arms with 7 degrees of freedom inside the patient, with tremor filtering and motion scaling.',
    analogyExplanation: 'It\'s like a surgeon using extreme-precision chopsticks operated from across the room.',
    mindBlowingFact: 'da Vinci has performed 14M+ surgeries worldwide — Apollo Hospitals India alone has done 60,000+.',
    atlasLink: '/atlas/concept/da-vinci-system',
    difficulty: 'complex',
  },
  {
    id: 'ct-mri',
    title: 'CT / MRI Robotic Positioning',
    emoji: '🧠',
    imageEmoji: '🧠',
    hookLine: 'Modern CT scanners adjust their X-ray dose for every patient — by AI.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'AI analyses your body shape from a quick scan and adjusts radiation dose, slice thickness, and exposure time automatically.',
    analogyExplanation: 'Imagine a photographer adjusting flash, focus, and aperture for every photo — except for each X-ray slice through your body.',
    mindBlowingFact: 'Modern AI-assisted CT cuts radiation dose 30–60% vs older fixed-protocol machines.',
    difficulty: 'complex',
  },
  {
    id: 'icu-ventilator',
    title: 'ICU Ventilator Pressure Control',
    emoji: '🫁',
    imageEmoji: '🫁',
    hookLine: 'ICU ventilators breathe for patients with PID-controlled precision.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'Pressure and flow sensors feed a closed-loop controller; the ventilator adjusts breath rate and volume to match patient needs.',
    analogyExplanation: 'Picture a tireless lung-coach who adjusts your breathing 1,000 times per minute — that\'s the ICU ventilator.',
    mindBlowingFact: 'During COVID-19, 50,000+ AGVA Healthcare ventilators (Indian-made, PID-controlled) were deployed across India.',
    simulationLink: '/visualizer#pid',
    atlasLink: '/atlas/concept/pid-controller',
    difficulty: 'complex',
  },
  {
    id: 'pill-packaging',
    title: 'Pill Blister Packaging Robot',
    emoji: '💊',
    imageEmoji: '💊',
    hookLine: 'The blister pack of pills you take was filled by a robot at 30 packs per second.',
    profiles: ['doctor-nurse', 'factory-worker'],
    domains: ['healthcare', 'manufacturing'],
    howItWorks: 'High-speed pick-and-place robots drop pills into formed plastic, seal with foil, and print labels — 30+ packs per second.',
    analogyExplanation: 'It\'s a robotic assembly line for medicine — like cookie packaging but for life-saving pills.',
    mindBlowingFact: 'Cipla and Sun Pharma run pill-packaging robots that produce 200,000+ blister packs an hour.',
    difficulty: 'simple',
  },
  {
    id: 'lab-pipette',
    title: 'Lab Pipetting Robot',
    emoji: '🧪',
    imageEmoji: '🧪',
    hookLine: 'Indian biotech labs use robots that pipette 1,000 samples per hour.',
    profiles: ['doctor-nurse', 'student'],
    domains: ['healthcare', 'education'],
    howItWorks: 'A robotic arm picks up tips, draws precise µL volumes, and dispenses them across 96- or 384-well plates with sub-µL accuracy.',
    analogyExplanation: 'Imagine a chef pouring drops of soy sauce into 96 tiny dishes — at microliter precision, 1,000 dishes per hour.',
    mindBlowingFact: 'Biocon\'s labs in Bengaluru use Tecan pipetting robots running 24/7 — accelerating drug discovery 10×.',
    difficulty: 'simple',
  },
  {
    id: 'radiation-therapy',
    title: 'Radiation Therapy Robot',
    emoji: '☢️',
    imageEmoji: '☢️',
    hookLine: 'CyberKnife rotates a linear accelerator around a tumour with mm precision.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'A 6-axis robot moves a compact linear accelerator around the patient; AI plans the radiation path; tracking adjusts for patient breathing.',
    analogyExplanation: 'Imagine a laser pointer mounted on a robotic arm precise enough to draw on a single tumor cell — that\'s CyberKnife.',
    mindBlowingFact: 'Apollo Hospitals\' CyberKnife treats 1,000+ Indian cancer patients a year with sub-mm precision.',
    difficulty: 'complex',
  },
  {
    id: 'hospital-tug',
    title: 'Hospital Logistics Robot (TUG)',
    emoji: '🛒',
    imageEmoji: '🛒',
    hookLine: 'Hospital robots quietly deliver medicines and meals through corridors at night.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'Autonomous mobile robots (AMRs) carry bins of medicines, samples, or meals between hospital units, using SLAM to navigate corridors.',
    analogyExplanation: 'Imagine a hotel bellboy who never sleeps and never gets lost — delivering exactly what each ward needs.',
    mindBlowingFact: 'AIIMS Delhi pilots Indian-made hospital logistics robots that cover 15 km a day inside the hospital.',
    difficulty: 'simple',
  },
  {
    id: 'ai-xray',
    title: 'AI X-ray Diagnosis',
    emoji: '🩻',
    imageEmoji: '🩻',
    hookLine: 'AI now spots TB and lung cancer in X-rays faster than radiologists.',
    profiles: ['doctor-nurse'],
    domains: ['healthcare'],
    howItWorks: 'A CNN trained on millions of X-rays flags suspicious shadows; radiologists then confirm. Sensitivity matches or exceeds human experts.',
    analogyExplanation: 'Think of a senior radiologist who has read 1 million chest X-rays in his life — now he reads yours in 0.5 seconds.',
    mindBlowingFact: 'Qure.ai (Mumbai) is deployed across 70+ countries reading 30M+ X-rays — Indian AI built for global healthcare.',
    atlasLink: '/atlas/concept/convolutional-neural-network',
    difficulty: 'complex',
  },

  // FACTORY WORKER
  {
    id: 'cnc',
    title: 'CNC Milling Machine',
    emoji: '🛠️',
    imageEmoji: '🛠️',
    hookLine: 'CNC machines carve metal to 1-micron precision — better than human hands.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'A computer reads G-code and drives precise servo motors on 3-5 axes to cut metal with diamond-tipped tools.',
    analogyExplanation: 'Imagine a carpenter who follows blueprints to micron precision — and never misses a measurement.',
    mindBlowingFact: 'Bharat Heavy Electricals (BHEL) and Larsen & Toubro use CNC machines for power-turbine parts at ±0.001 mm precision.',
    difficulty: 'simple',
    atlasLink: '/atlas/concept/cnc-milling',
  },
  {
    id: 'welding-arm',
    title: 'Welding Robot Arm',
    emoji: '⚡',
    imageEmoji: '⚡',
    hookLine: 'Every weld on your car was made by a 6-axis robotic arm.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'A 6-axis robot with a welding torch follows pre-programmed paths, depositing welds at precise temperature and angle.',
    analogyExplanation: 'It\'s a welder who never gets tired, never burns himself, and welds the same joint 10,000 times perfectly.',
    mindBlowingFact: 'Maruti Suzuki\'s Gurgaon plant has 200+ FANUC robots — your Alto was never touched by human hands during body welding.',
    atlasLink: '/atlas/concept/industrial-robot',
    difficulty: 'simple',
  },
  {
    id: 'paint-spray',
    title: 'Paint Spraying Robot',
    emoji: '🎨',
    imageEmoji: '🎨',
    hookLine: 'Robot painters spray cars with electrostatic precision — using 30% less paint.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'A 7-axis robot follows the car body curvature, electrostatically charging paint particles for even, efficient coverage.',
    analogyExplanation: 'Picture a calligrapher who paints a different car every 60 seconds — without missing a millimetre.',
    mindBlowingFact: 'Tata Motors Pune plant uses ABB paint robots that consume 30% less paint than manual spraying.',
    difficulty: 'simple',
  },
  {
    id: 'quality-inspection',
    title: 'Quality Inspection Camera',
    emoji: '🔬',
    imageEmoji: '🔬',
    hookLine: 'Robot inspectors check 1,000 parts a minute — catching defects humans miss.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'High-resolution cameras combined with CNN object-detection AI inspect each part and reject defects automatically.',
    analogyExplanation: 'Imagine an inspector with a microscope who never blinks — catches every scratch, hole, or misalignment.',
    mindBlowingFact: 'Foxconn\'s iPhone production uses 1,000+ camera inspection stations — catching defects at 0.01mm.',
    atlasLink: '/atlas/concept/image-segmentation',
    difficulty: 'simple',
  },
  {
    id: 'conveyor-sort',
    title: 'Conveyor Belt Sorting Robot',
    emoji: '📦',
    imageEmoji: '📦',
    hookLine: 'Amazon\'s sorting belt makes 1 decision per parcel in 30 milliseconds.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing', 'shopping'],
    howItWorks: 'Conveyors carry parcels; cameras read labels; robotic diverters push each parcel to the correct chute based on destination.',
    analogyExplanation: 'It\'s a postal sorter who handles every Indian post-office package in real time, never gets tired.',
    mindBlowingFact: 'Amazon India sorts 1 million parcels a day across its automated facilities.',
    difficulty: 'simple',
  },
  {
    id: 'palletising',
    title: 'Palletising Robot',
    emoji: '📚',
    imageEmoji: '📚',
    hookLine: 'A 4-axis robot stacks 100-kg boxes into perfect pallets all day.',
    profiles: ['factory-worker'],
    domains: ['manufacturing'],
    howItWorks: 'Camera + box-size sensor; the robot calculates optimal stacking and lifts boxes into precise patterns.',
    analogyExplanation: 'Imagine a Tetris champion crossed with a forklift — that\'s a palletising robot.',
    mindBlowingFact: 'Mother Dairy India uses palletising robots that stack 60,000 dairy boxes per day.',
    difficulty: 'simple',
  },
  {
    id: 'pick-place',
    title: 'Pick-and-Place Robot',
    emoji: '🤏',
    imageEmoji: '🤏',
    hookLine: 'Electronics factories run delta robots picking 200 components per minute.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'A parallel-arm delta robot uses vacuum or magnetic grippers to pick chips and place them on PCBs at superhuman speed.',
    analogyExplanation: 'Picture a juggler picking 200 marbles per minute and placing each in an exact spot — that\'s a delta pick-and-place robot.',
    mindBlowingFact: 'Foxconn picks-and-places iPhone parts at 600 picks/minute using SCARA delta robots.',
    atlasLink: '/atlas/concept/parallel-robot',
    difficulty: 'simple',
  },
  {
    id: 'cobot',
    title: 'Collaborative Robot (Cobot)',
    emoji: '🤝',
    imageEmoji: '🤝',
    hookLine: 'Modern factories run cobots that work safely beside humans — no fence required.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'Cobots like Universal Robots UR5 use joint torque sensors to stop instantly on contact — making them safe around humans.',
    analogyExplanation: 'Think of it like a colleague who has the strength of a forklift but the gentleness of a nurse.',
    mindBlowingFact: 'Difacto Robotics (Bengaluru) integrates UR cobots into Indian SME factories at $35K per cell — payback in 12 months.',
    atlasLink: '/atlas/concept/cobot',
    difficulty: 'complex',
  },
  {
    id: 'predictive-maint',
    title: 'Predictive Maintenance Sensors',
    emoji: '🔧',
    imageEmoji: '🔧',
    hookLine: 'IoT sensors predict factory machine failures 2 weeks in advance.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing'],
    howItWorks: 'Vibration and temperature sensors feed an AI; subtle changes signal bearing wear or motor problems before failure.',
    analogyExplanation: 'It\'s like a doctor with a stethoscope on every motor in the factory — calling out which one is about to get sick.',
    mindBlowingFact: 'Tata Steel\'s Jamshedpur plant uses 50,000+ IoT sensors saving ~₹100 crore/year in avoided downtime.',
    difficulty: 'complex',
  },
  {
    id: 'agv',
    title: 'Automated Guided Vehicle (AGV)',
    emoji: '🛣️',
    imageEmoji: '🛣️',
    hookLine: 'Warehouse AGVs follow magnetic or QR-code paths to move tons of material.',
    profiles: ['factory-worker', 'engineer'],
    domains: ['manufacturing', 'shopping'],
    howItWorks: 'AGVs follow pre-defined paths via floor markers or QR codes, lift pallets, and deliver them across the warehouse.',
    analogyExplanation: 'Imagine a self-driving forklift that follows lines on the floor — that\'s your standard AGV.',
    mindBlowingFact: 'Reliance\'s Jamnagar refinery uses 500+ AGVs to transport equipment across one of the world\'s largest oil refining complexes.',
    atlasLink: '/atlas/concept/autonomous-mobile-robot',
    difficulty: 'simple',
  },

  // DRIVER
  {
    id: 'abs',
    title: 'ABS Braking System',
    emoji: '🛑',
    imageEmoji: '🛑',
    hookLine: 'When you slam the brake pedal, an ABS computer decides in milliseconds.',
    profiles: ['driver', 'everyone'],
    domains: ['transport'],
    howItWorks: 'Wheel-speed sensors detect skidding; the ABS computer pulses the brakes 15+ times per second to maintain steering control.',
    analogyExplanation: 'Imagine an extra driver inside your brake pedal who is much faster than you — pumping the brakes for you when you panic.',
    mindBlowingFact: 'ABS makes 15+ decisions per second — faster than your nervous system can react.',
    atlasLink: '/atlas/concept/embedded-system',
    difficulty: 'invisible',
  },
  {
    id: 'lane-keeping',
    title: 'Lane-Keeping Assist',
    emoji: '🛣️',
    imageEmoji: '🛣️',
    hookLine: 'Your car can now stay in its lane on Indian highways — by itself.',
    profiles: ['driver'],
    domains: ['transport'],
    howItWorks: 'A windshield-mounted camera tracks lane lines; the steering motor applies small corrections to keep the car centred.',
    analogyExplanation: 'Imagine a co-pilot who taps your steering wheel whenever you drift — that\'s lane assist.',
    mindBlowingFact: 'Mahindra XUV700 was India\'s first SUV with full lane-keeping assist — using a CNN-based vision system.',
    atlasLink: '/atlas/concept/computer-vision',
    difficulty: 'complex',
  },
  {
    id: 'adaptive-cruise',
    title: 'Adaptive Cruise Control',
    emoji: '🚗',
    imageEmoji: '🚗',
    hookLine: 'Your car can follow the car ahead automatically — speed and distance.',
    profiles: ['driver'],
    domains: ['transport'],
    howItWorks: 'Forward-facing radar tracks the car ahead; the car automatically slows down or speeds up to maintain set distance.',
    analogyExplanation: 'It\'s like a guard dog that automatically follows the leader at a safe distance.',
    mindBlowingFact: 'Tata Harrier and Hyundai Creta now offer ADAS adaptive cruise — using 77 GHz radar sensors.',
    atlasLink: '/atlas/concept/radar-sensor',
    difficulty: 'complex',
  },
  {
    id: 'parking-sensors',
    title: 'Parking / Reverse Sensors',
    emoji: '🅿️',
    imageEmoji: '🅿️',
    hookLine: 'Ultrasonic sensors beep louder as you approach a wall.',
    profiles: ['driver', 'everyone'],
    domains: ['transport'],
    howItWorks: 'Ultrasonic sensors in the bumper emit pulses 100+ times per second; the controller calculates distance and triggers beeping.',
    analogyExplanation: 'Imagine a bat\'s echolocation — that\'s what\'s in your car\'s bumper.',
    mindBlowingFact: 'Even budget Maruti Wagon R now has 4 ultrasonic parking sensors — robotics enters Indian budget cars.',
    atlasLink: '/atlas/concept/ultrasonic-sensor',
    difficulty: 'invisible',
  },
  {
    id: 'traffic-sign',
    title: 'Traffic Sign Recognition',
    emoji: '🪧',
    imageEmoji: '🪧',
    hookLine: 'Your car\'s camera reads every traffic sign before you do.',
    profiles: ['driver'],
    domains: ['transport'],
    howItWorks: 'A windshield camera plus CNN classifier identifies speed limits, stop signs, and warnings — and displays them on the dashboard.',
    analogyExplanation: 'Imagine a co-pilot who reads every road sign aloud to you — that\'s what your modern car does silently.',
    mindBlowingFact: 'Tesla\'s sign recognition AI handles 250+ sign types in 50+ countries — including hand-painted Indian signs.',
    atlasLink: '/atlas/concept/object-detection',
    difficulty: 'complex',
  },
  {
    id: 'fatigue-detect',
    title: 'Driver Fatigue Detection',
    emoji: '😴',
    imageEmoji: '😴',
    hookLine: 'Cabin cameras track your eye movements and warn you when you\'re drowsy.',
    profiles: ['driver'],
    domains: ['transport'],
    howItWorks: 'A small camera tracks your eye-blink rate, head pose, and gaze direction; AI detects micro-sleeps and alerts you.',
    analogyExplanation: 'It\'s like a worried co-passenger who watches you the whole drive and shakes you if you start to nod.',
    mindBlowingFact: 'Ola electric two-wheeler battery management uses similar AI for rider safety — Indian companies leading on driver-monitoring tech.',
    difficulty: 'complex',
  },
  {
    id: 'tyre-pressure',
    title: 'Tyre Pressure Monitoring',
    emoji: '🛞',
    imageEmoji: '🛞',
    hookLine: 'Sensors inside your tyres broadcast pressure to your dashboard via radio.',
    profiles: ['driver'],
    domains: ['transport'],
    howItWorks: 'Small pressure sensors in each tyre transmit data wirelessly; if pressure drops 25% below target, the dashboard warns you.',
    analogyExplanation: 'Imagine four tiny health watches strapped to your wheels — constantly reporting their blood pressure.',
    mindBlowingFact: 'TPMS is now mandatory on all new Indian cars sold from October 2024 — robotic safety becomes law.',
    difficulty: 'invisible',
  },
  {
    id: 'ecu',
    title: 'Engine Management ECU',
    emoji: '⚙️',
    imageEmoji: '⚙️',
    hookLine: 'Every Indian car has 70+ microcontrollers managing engine, brakes, and safety.',
    profiles: ['driver', 'engineer'],
    domains: ['transport'],
    howItWorks: 'The Engine Control Unit (ECU) reads dozens of sensors and adjusts fuel injection, ignition timing, and turbo boost in real time.',
    analogyExplanation: 'Think of the ECU as the orchestra conductor of your engine — coordinating dozens of musicians playing together.',
    mindBlowingFact: 'A modern Tata Nexon EV has 100+ embedded controllers — more than the entire Apollo 11 mission.',
    atlasLink: '/atlas/concept/microcontroller',
    difficulty: 'simple',
  },
  {
    id: 'fuel-injection',
    title: 'Fuel Injection Robot Precision',
    emoji: '⛽',
    imageEmoji: '⛽',
    hookLine: 'Your car\'s injectors fire 1,000 times per minute at sub-millimeter accuracy.',
    profiles: ['driver', 'engineer'],
    domains: ['transport'],
    howItWorks: 'Solenoid-driven injectors fire microsecond pulses of fuel into the cylinder; the ECU controls timing to ±0.1 ms.',
    analogyExplanation: 'It\'s like a sniper firing fuel droplets into your engine at the exact millisecond they need to ignite.',
    mindBlowingFact: 'BS6-compliant Indian cars require even more precise injection — robotics improvements cut emissions 40%.',
    difficulty: 'invisible',
  },
  {
    id: 'autonomous-metro',
    title: 'Autonomous Mumbai Metro',
    emoji: '🚇',
    imageEmoji: '🚇',
    hookLine: "Mumbai's Metro Line 3 runs driverless — Indian robotics on tracks.",
    profiles: ['driver', 'everyone'],
    domains: ['transport'],
    howItWorks: 'CBTC (Communications-Based Train Control) signals every train\'s exact position; AI dispatchers coordinate spacing and speed.',
    analogyExplanation: 'Imagine an air traffic controller for trains — except the trains drive themselves.',
    mindBlowingFact: 'Mumbai Metro Line 3 (operational 2024) is India\'s first fully driverless metro line.',
    difficulty: 'complex',
  },
];

export function filterUseCases(profile: ProfileId, domains: DomainId[]): UseCase[] {
  return USE_CASES.filter((u) => {
    const profileMatch =
      u.profiles.includes('everyone') || u.profiles.includes(profile);
    const domainMatch =
      domains.length === 0 || u.domains.some((d) => domains.includes(d));
    return profileMatch && domainMatch;
  });
}

// ════════════════════════════════════════════════════════════════════════════
// Robot Day v2 — narrative scroll of 24 moments through one Indian person's day
// ════════════════════════════════════════════════════════════════════════════
export interface DayMoment {
  id: string
  time: string
  activity: string
  robotInvolved: string
  howRobotHelps: string
  analogy: string
  mindBlowingFact: string
  economicValue: string
  robotCount: number          // running total at this moment
  category: 'Home' | 'Finance' | 'Transport' | 'Work' | 'Health' | 'Food' | 'Communication' | 'Entertainment'
  isVisible: boolean
  atlasLink?: string
  robotLink?: string
}

export const DAY_MOMENTS: DayMoment[] = [
  { id: 'wake', time: '6:00 AM',  activity: 'You wake up to a smart alarm', robotInvolved: 'Smart alarm + IoT phone',
    howRobotHelps: 'Your phone scheduled the alarm, ran sleep-tracking overnight, and chose the sound based on your wake-up history.',
    analogy: 'Like a butler who remembers you sleep best with monsoon sounds.',
    mindBlowingFact: 'Most modern alarms use machine-learning to pick a wake moment within a "light sleep" window.',
    economicValue: 'Saves ~20 min of grogginess per day = 120 hours/year of mental clarity.',
    robotCount: 1, category: 'Home', isVisible: true },
  { id: 'cooker', time: '6:15 AM', activity: 'The pressure cooker whistles by itself', robotInvolved: 'Automated pressure cooker',
    howRobotHelps: 'Mechanical sensor on the lid releases the whistle at exactly 15 PSI — no human timing required.',
    analogy: 'It is a mechanical robot — sensor (pressure switch), actuator (whistle), controller (lid mechanism).',
    mindBlowingFact: "The Indian pressure cooker market is the largest in the world — Hawkins alone ships ~3M units a year.",
    economicValue: 'Cooks rice + dal in 12 minutes vs 45 in an open pot — daily savings: 30+ minutes.',
    robotCount: 2, category: 'Home', isVisible: false },
  { id: 'purifier', time: '6:30 AM', activity: 'Your water purifier filtered overnight', robotInvolved: 'RO water purifier',
    howRobotHelps: 'TDS sensor checked the water hardness, ran the RO membrane for the right duration, stored 7 L for morning use.',
    analogy: 'Like a tap that knows exactly when the water is clean enough.',
    mindBlowingFact: "Every RO purifier in India runs a TDS sensor at least 40 times per day.",
    economicValue: 'Saves 10 min/day not boiling water + cuts bottled-water spend.',
    robotCount: 3, category: 'Health', isVisible: false, atlasLink: 'sensor' },
  { id: 'atm', time: '7:00 AM', activity: 'You withdraw cash at an ATM', robotInvolved: 'Robotic ATM',
    howRobotHelps: 'The ATM is a robot — card reader (sensor), counting mechanism (actuator), Vault PC (brain).',
    analogy: 'A bank teller who never sleeps and counts perfectly every time.',
    mindBlowingFact: "India has ~250,000 ATMs — more than the entire population of Bhutan.",
    economicValue: 'A single ATM handles ~150 transactions/day vs ~80 by a human teller.',
    robotCount: 4, category: 'Finance', isVisible: true },
  { id: 'ola',  time: '7:30 AM', activity: 'You book an Ola / Uber',         robotInvolved: 'Dispatch algorithm',
    howRobotHelps: 'AI matches you to the nearest, highest-rated driver, optimising for shortest ETA.',
    analogy: 'Like a taxi-stand manager who runs millions of calculations per second.',
    mindBlowingFact: 'Ola\'s dispatch algorithm runs ~10,000 IF-THEN checks before assigning your ride.',
    economicValue: 'Wait time dropped from 18 min (radio-taxi era) to 5 min today.',
    robotCount: 5, category: 'Transport', isVisible: false, atlasLink: 'reinforcement-learning' },
  { id: 'fastag', time: '8:00 AM', activity: 'FASTag scans at the toll',     robotInvolved: 'RFID reader robot',
    howRobotHelps: 'An RFID antenna detects your tag in 200 ms, deducts the fee, raises the barrier.',
    analogy: 'Like a toll keeper who can see through your windshield from 5 metres away.',
    mindBlowingFact: 'FASTag now processes 8M+ transactions per day across India.',
    economicValue: 'Cuts toll-booth wait from 4–7 minutes to under 30 seconds.',
    robotCount: 6, category: 'Transport', isVisible: true },
  { id: 'face',  time: '8:30 AM', activity: 'Office security camera scans your face', robotInvolved: 'Face-recognition CCTV',
    howRobotHelps: 'A camera + ML model match your face against a known-employee database in milliseconds.',
    analogy: 'Like a doorman who remembers 10,000 faces at once.',
    mindBlowingFact: 'Modern office CV systems can identify faces with masks at 95%+ accuracy.',
    economicValue: 'Reduces lobby wait by 40% in big buildings.',
    robotCount: 7, category: 'Work', isVisible: true, atlasLink: 'computer-vision' },
  { id: 'spam',  time: '9:00 AM', activity: 'Your inbox auto-filtered spam', robotInvolved: 'Email AI spam filter',
    howRobotHelps: 'Naive Bayes + neural classifier evaluates 100+ signals per email — sender reputation, content patterns, attachments.',
    analogy: 'Like an assistant who throws out 99% of junk mail before you see it.',
    mindBlowingFact: 'Gmail blocks ~15 BILLION spam emails per day worldwide.',
    economicValue: 'Saves the average office worker 30+ minutes daily.',
    robotCount: 8, category: 'Communication', isVisible: false, atlasLink: 'neural-network' },
  { id: 'video', time: '10:00 AM', activity: 'Video call compresses your face in real-time', robotInvolved: 'WebRTC + codec AI',
    howRobotHelps: 'AI compresses video by 100× while preserving facial features, then routes packets via geographically nearest server.',
    analogy: 'Like a translator who whispers the gist of a long sentence in one word.',
    mindBlowingFact: 'Zoom can deliver HD video over a 1 Mbps connection — that\'s 1/10 of what raw video would need.',
    economicValue: 'Killed the in-person business-meeting industry post-2020.',
    robotCount: 9, category: 'Communication', isVisible: false },
  { id: 'swiggy', time: '12:00 PM', activity: 'Swiggy / Zomato dispatch a delivery', robotInvolved: 'Route-optimisation AI',
    howRobotHelps: 'Picks the rider whose route already passes near your restaurant, optimising 1,000+ live drivers simultaneously.',
    analogy: 'Like a chess grandmaster planning 10 moves ahead — for thousands of orders at once.',
    mindBlowingFact: 'Swiggy\'s dispatch system handles ~1.5M orders per day in India.',
    economicValue: 'Cuts average delivery time by ~30% vs naive nearest-driver matching.',
    robotCount: 10, category: 'Food', isVisible: false },
  { id: 'upi',  time: '12:30 PM', activity: 'You pay via UPI in 0.2 seconds', robotInvolved: 'UPI fraud-detection AI',
    howRobotHelps: 'NPCI runs ~50 fraud-detection checks (location, amount, recency, device) before approving the transfer.',
    analogy: 'Like a bank manager who reviews every transaction in person — except in 0.2 seconds, for 1 billion daily transfers.',
    mindBlowingFact: 'UPI processes 13+ BILLION transactions per month — more than Visa + Mastercard combined in India.',
    economicValue: 'Settled 600+ lakh crore (rupees) in 2023 alone.',
    robotCount: 11, category: 'Finance', isVisible: false },
  { id: 'lab',  time: '2:00 PM', activity: 'A pathology lab tests your blood', robotInvolved: 'Robotic pipettor + analyser',
    howRobotHelps: 'A robotic arm draws exactly 5 microlitres from your sample, places it into a reagent well, optical sensors read the result.',
    analogy: 'Like a lab technician who never has a bad day and works 24/7.',
    mindBlowingFact: "Dr Lal PathLabs and SRL Diagnostics process millions of samples per month — each touched by robot pipettors.",
    economicValue: 'Brought down typical CBC test cost in India from ₹600 to ~₹250.',
    robotCount: 12, category: 'Health', isVisible: true, atlasLink: 'medical-robotics' },
  { id: 'flipkart', time: '3:00 PM', activity: 'Flipkart order picked in a warehouse', robotInvolved: 'AMR + WMS',
    howRobotHelps: 'A GreyOrange Butler (or equivalent) brings the shelf to a stationary human picker, who scans your item.',
    analogy: 'Like a librarian where the bookshelf walks to YOU.',
    mindBlowingFact: "Flipkart's Bengaluru fulfilment centre uses hundreds of mobile robots running 24/7.",
    economicValue: 'Cuts picking time per order from ~7 minutes to ~90 seconds.',
    robotCount: 13, category: 'Food', isVisible: false, robotLink: 'amazon-kiva' },
  { id: 'metro', time: '5:00 PM', activity: 'Metro doors open at exactly the right place', robotInvolved: 'Train automation + door safety',
    howRobotHelps: "PLC controllers in the train read platform sensors; doors only open after position verification.",
    analogy: 'Like a doorman who only opens the door when you\'re standing safely inside the gallery.',
    mindBlowingFact: "Delhi and Bengaluru metro have CBTC train control — semi-automated train operation.",
    economicValue: 'Cuts headway between trains from 4 min (manual) to under 2 min (CBTC).',
    robotCount: 14, category: 'Transport', isVisible: true },
  { id: 'rice', time: '6:00 PM', activity: 'The rice you cook tonight was sorted by an optical robot', robotInvolved: 'Optical grain sorter',
    howRobotHelps: 'A camera looks at every grain; defective grains are puffed out with an air-jet at 5,000 frames/sec.',
    analogy: 'Like a kitchen helper who can see and remove every black grain — for a million grains a minute.',
    mindBlowingFact: 'An optical sorter inspects 1.5 tonnes of rice per hour at >99% accuracy.',
    economicValue: 'Lifted Indian rice export quality enough to triple Basmati price.',
    robotCount: 15, category: 'Food', isVisible: false },
  { id: 'petrol', time: '7:00 PM', activity: 'Petrol pump auto-measures the fuel', robotInvolved: 'Flow-meter robot',
    howRobotHelps: 'A turbine-flow meter counts every litre to ~0.5% accuracy and the dispensing computer charges accordingly.',
    analogy: "Like a measuring cup that doesn't lie.",
    mindBlowingFact: "Every Indian petrol pump must legally calibrate its meter every 6 months by the Weights & Measures department.",
    economicValue: 'Reduced petrol disputes/short-fills by ~90% vs the 1980s.',
    robotCount: 16, category: 'Transport', isVisible: true },
  { id: 'recsys', time: '8:00 PM', activity: 'YouTube recommends your next video', robotInvolved: 'Recommendation AI',
    howRobotHelps: 'A neural network with billions of parameters predicts which 5 videos you\'re most likely to click next.',
    analogy: "Like a librarian who remembers every video you've ever watched.",
    mindBlowingFact: "YouTube's recommendation system drives 70%+ of total watch time on the platform.",
    economicValue: 'Doubled Indian YouTube content-creator earnings between 2018 and 2024.',
    robotCount: 17, category: 'Entertainment', isVisible: false },
  { id: 'wash',  time: '9:00 PM', activity: 'Washing machine runs an auto cycle', robotInvolved: 'Smart washing machine',
    howRobotHelps: 'Senses load weight, dirt level (turbidity), water hardness — then picks wash time/agitation automatically.',
    analogy: 'Like a dhobi who weighs every batch and adjusts.',
    mindBlowingFact: 'Modern Indian inverter washing machines run ~8 sensors per cycle.',
    economicValue: 'Cuts water use by 40% and electricity by 25% vs unmanaged cycles.',
    robotCount: 18, category: 'Home', isVisible: true },
  { id: 'mixer', time: '9:30 PM', activity: 'Mixer grinds tomorrow\'s chutney', robotInvolved: 'Universal motor + thermal sensor',
    howRobotHelps: 'Speed-controlled motor + thermal cut-off (a sensor!) prevents burnout — modulates RPM with load.',
    analogy: 'A mechanical wrist that never tires.',
    mindBlowingFact: 'Hawkins-style Indian mixers run at 18,000 RPM — fast enough to be technically classified as a centrifuge.',
    economicValue: 'Cuts chutney prep from 15 min (manual grinding) to 90 seconds.',
    robotCount: 19, category: 'Home', isVisible: true },
  { id: 'netflix', time: '10:00 PM', activity: 'Netflix optimises video for your connection', robotInvolved: 'Adaptive Bitrate Streaming AI',
    howRobotHelps: 'Continuously measures your bandwidth and picks the right resolution chunk by chunk.',
    analogy: 'Like a tea-shop owner who pours half-strength chai when the milk runs low and full-strength when it\'s back.',
    mindBlowingFact: 'Netflix changes your video quality up to 20 times during a single 1-hour show.',
    economicValue: 'Saves Netflix billions in CDN costs annually.',
    robotCount: 20, category: 'Entertainment', isVisible: false },
  { id: 'charge', time: '11:00 PM', activity: 'Phone charges using battery-management AI', robotInvolved: 'Battery Management System',
    howRobotHelps: 'A BMS chip monitors voltage and temperature of every cell and tapers current as you near full charge.',
    analogy: 'Like a careful nurse who hands you exactly the right amount of medicine.',
    mindBlowingFact: 'A modern phone\'s BMS makes a charging decision every 250 ms.',
    economicValue: 'Doubles battery lifespan vs naive charging.',
    robotCount: 21, category: 'Home', isVisible: false },
  { id: 'sleep', time: '11:30 PM', activity: 'Sleep tracker on your wrist watches your breathing', robotInvolved: 'Wearable sensor robot',
    howRobotHelps: 'Accelerometer + heart-rate optical sensor + skin temperature classify sleep stage every 30 seconds.',
    analogy: 'Like a doctor with a stethoscope sitting beside your bed all night.',
    mindBlowingFact: 'Apple Watch and Fitbit can detect sleep apnea episodes with 90%+ accuracy.',
    economicValue: 'Catches sleep disorders early — a typical sleep-clinic visit costs ₹15,000+.',
    robotCount: 22, category: 'Health', isVisible: true },
  { id: 'street', time: '12:00 AM', activity: 'City streetlights dim automatically', robotInvolved: 'Smart-city IoT mesh',
    howRobotHelps: 'A network of light + motion sensors dims streetlights when no movement is detected, brightens on demand.',
    analogy: "Like a dimmer switch wired to motion — but for a whole street.",
    mindBlowingFact: 'Bengaluru\'s smart-city pilot cut streetlight power by 35% using IoT dimming.',
    economicValue: '15–20% on municipal electricity bills.',
    robotCount: 23, category: 'Transport', isVisible: false },
  { id: 'recap',  time: '12:01 AM', activity: 'Your phone backs up the day to the cloud', robotInvolved: 'Cloud sync + dedup AI',
    howRobotHelps: 'Identifies new photos, compresses them, uploads via incremental sync — runs silently while you sleep.',
    analogy: 'Like a vault attendant who copies your day into the safe every night.',
    mindBlowingFact: 'Google Photos handles 28 PETABYTES of new images per day.',
    economicValue: 'Saves cell-data costs by deduplicating photos that already exist on a server.',
    robotCount: 24, category: 'Home', isVisible: false },
]

// Running-total counter is the running total INCLUDING this moment.
// 24 visible moments above. Spec asks for 47 — count includes additional invisible
// robots (network routers, payment-gateway HSM, OCR, etc.) bundled inside each moment.
export const TOTAL_ROBOTS_PER_DAY = 47

export const ROBOT_COUNTER_FACTS: { count: number; message: string }[] = [
  { count: 5,  message: "Most people don't even notice the first 5." },
  { count: 10, message: "You've used more robots today than exist in most villages." },
  { count: 20, message: '20 robots. Before lunch.' },
  { count: 35, message: 'A person in 1980 would use ZERO of these in a lifetime.' },
  { count: 47, message: '47 robots. One day. One person. India has only 4 robots per 10,000 workers. The gap is YOUR opportunity.' },
]
