// lib/robots-data.ts
// Profile data for 20 famous robots — powers /robots and /robots/[slug]
// 2026 redesign: curiosity-first (hook line, stat chips, "in one sentence", wow factors, popCulture, teamBehind, fameRank).

export type RobotType =
  | 'humanoid'
  | 'industrial'
  | 'space'
  | 'consumer'
  | 'military'
  | 'medical'
  | 'service'
  | 'companion'
  | 'educational'
  | 'cobot'
  | 'quadruped'
  | 'warehouse';

export type RobotStatus = 'active' | 'retired' | 'concept';

export interface RobotSpec {
  height?: string;
  weight?: string;
  speed?: string;
  payload?: string;
  battery?: string;
  dof?: string;
  reach?: string;
}

export interface Robot {
  slug: string;
  fameRank: number;
  name: string;
  emoji: string;
  maker: string;
  country: string;
  countryFlag: string;
  year: number;
  type: RobotType;
  status: RobotStatus;
  oneLiner: string;
  hookLine: string;
  statChips: { icon: string; text: string }[];
  inOneSentence: string;
  wowFactors: string[];
  howItWorksSteps: string[];
  popCulture: string;
  teamBehind: string;
  description: string;
  specs: RobotSpec;
  capabilities: string[];
  funFacts: string[];
  videoUrl?: string;
  imageAlt: string;
  metaTitle: string;
  metaDescription: string;
  atlasSlug?: string;
  atlasLearnLinks?: { label: string; href: string }[];
}

const ROBOTS_UNSORTED: Robot[] = [
  {
    slug: 'spot',
    fameRank: 1,
    name: 'Spot',
    emoji: '🐕',
    maker: 'Boston Dynamics',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2019,
    type: 'quadruped',
    status: 'active',
    oneLiner: "Boston Dynamics' quadruped robot dog — inspecting power plants, oil rigs, and construction sites worldwide.",
    hookLine: 'This dog-robot inspects nuclear power plants that would kill a human.',
    statChips: [
      { icon: '📅', text: 'Born 2019' },
      { icon: '🌍', text: '64 countries' },
      { icon: '⚡', text: '90 min battery' },
    ],
    inOneSentence: "Spot is a robot dog that walks into places that would hurt you, sees what's there, and walks back out.",
    wowFactors: [
      'It can climb stairs faster than you can run down them.',
      'BP, NASA, and SpaceX use it to patrol their most dangerous sites.',
      'It famously danced to "Do You Love Me" — the video has 60M+ views.',
    ],
    howItWorksSteps: [
      'Four cameras on every side build a 3D map of the world as Spot walks.',
      'Onboard sensors detect floor texture, edges, and obstacles in real time.',
      'A control algorithm picks foot placements 500 times per second to stay balanced.',
      'Spot can be teleoperated by a human or run fully autonomous patrol routes.',
      'When the battery dips, Spot walks itself to a charging dock and recharges.',
    ],
    popCulture: 'NYPD trialled Spot (briefly, controversially). It appears in BTS music videos, Korean dance routines, and a 2024 Coca-Cola ad.',
    teamBehind: "Marc Raibert, who founded Boston Dynamics in 1992, drove Spot's hydraulic-to-electric pivot. Robert Playter is now CEO. Hyundai owns the company since 2020.",
    description:
      "Spot is the world's most commercially successful quadruped robot. Boston Dynamics launched Spot for sale in 2019 at $74,500 per unit, making it the first production robot dog. Spot weighs 32 kg, can climb stairs, walk over rubble, open doors, and carry up to 14 kg of payload. Customers attach inspection cameras, gas sniffers, thermal sensors, and robotic arms to make Spot a roaming sensor platform. BP uses it on oil rigs, NYPD has trialled it, SpaceX uses it around launch pads, and NASA Jet Propulsion Lab tests autonomous mission planning on it. With its over-the-air software updates and growing third-party application ecosystem, Spot has created a new robotics category — commercial mobile inspection robots.",
    specs: { height: '84 cm', weight: '32 kg', speed: '1.6 m/s', payload: '14 kg', battery: '90 min runtime' },
    capabilities: [
      'Autonomous patrol and inspection',
      'Stair climbing and rubble traversal',
      'Manipulation via Spot Arm',
      'Thermal and gas leak detection',
      '360° terrain mapping',
      'Self-righting from falls',
    ],
    funFacts: [
      'Spot can climb stairs faster than most humans descend them.',
      'The Boston Dynamics "Do You Love Me" dancing video has over 60 million views.',
      'A Spot costs $74,500 — about the same as a Tesla Model S Plaid.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=fn3KWM1kuAw',
    imageAlt: 'Boston Dynamics Spot quadruped robot dog walking on industrial site',
    metaTitle: 'Boston Dynamics Spot Robot Dog — Specs, Price & Use Cases | R2BOT',
    metaDescription:
      'Complete profile of Boston Dynamics Spot quadruped robot — $74,500 price, 14 kg payload, BP and NASA deployments, and how it works.',
    atlasSlug: 'quadruped-robot',
    atlasLearnLinks: [
      { label: 'Quadruped Robot — Atlas', href: '/atlas/concept/quadruped-robot' },
      { label: 'LIDAR — Atlas', href: '/atlas/concept/lidar' },
      { label: 'BLDC Motors — Atlas', href: '/atlas/concept/brushless-motor' },
    ],
  },
  {
    slug: 'atlas',
    fameRank: 2,
    name: 'Atlas',
    emoji: '🤖',
    maker: 'Boston Dynamics',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2013,
    type: 'humanoid',
    status: 'active',
    oneLiner: "The world's most agile humanoid — does parkour, backflips, and box-stacking in factories.",
    hookLine: 'It learned to do a backflip. Now it works in a BMW car factory.',
    statChips: [
      { icon: '📅', text: 'Born 2013' },
      { icon: '🦾', text: '28 actuators' },
      { icon: '⚡', text: '2.5 m/s sprint' },
    ],
    inOneSentence: 'Atlas is a robot the size of a person that walks, runs, jumps, and now picks up car parts in a real factory.',
    wowFactors: [
      'It does backflips and parkour — moves no other humanoid can match.',
      'In 2024 it became the first humanoid to do paid work in a real factory (Hyundai).',
      "It plans whole-body motion 500 times per second, every step it takes.",
    ],
    howItWorksSteps: [
      'Cameras and depth sensors scan the environment 30+ times per second.',
      'A motion planner predicts the next 1–3 seconds of body trajectory.',
      'Joint motors execute the plan with millisecond precision.',
      'A safety layer monitors balance and aborts if anything looks unsafe.',
      'A learning system improves performance with each demonstration.',
    ],
    popCulture: 'Atlas backflip videos rack up tens of millions of views. Featured in Tesla, BMW, and Hyundai keynotes; cameos in The Late Show and Wired.',
    teamBehind: 'Marc Raibert (founder, now Chairman) defined Atlas. Robert Playter (CEO, ex-Olympic gymnast) led its agility era. Boston Dynamics was acquired by Hyundai in 2020 for $1.1B largely because of Atlas.',
    description:
      "Boston Dynamics Atlas is the world's most athletic humanoid robot. First unveiled in 2013 as a DARPA-funded research platform, Atlas has been steadily upgraded for over a decade. The hydraulic generation could do parkour, backflips, and gymnastics routines that went viral globally. In 2024, Boston Dynamics revealed the all-electric Atlas — lighter, quieter, and designed for real warehouse and factory work. Atlas uses model-predictive control to balance and plan motions in real time. Hyundai is deploying the electric Atlas in its own factories — the first humanoid robot to graduate from research demos to production manufacturing work.",
    specs: { height: '150 cm', weight: '89 kg', speed: '2.5 m/s', payload: '11 kg', battery: 'Electric (latest gen)', dof: '28 degrees of freedom' },
    capabilities: [
      'Parkour and backflips',
      'Whole-body manipulation of heavy objects',
      'Dynamic balance recovery',
      'Stair and obstacle traversal',
      'Tool use (drills, valves)',
      'Real-time terrain perception',
    ],
    funFacts: [
      "Atlas's backflip video from 2017 has been viewed over 60 million times.",
      'The new electric Atlas can rotate its head and joints a full 360° — something humans cannot do.',
      'Hyundai paid $1.1 billion to acquire Boston Dynamics in 2020 largely because of Atlas.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=tF4DML7FIWk',
    imageAlt: 'Boston Dynamics Atlas humanoid robot doing parkour',
    metaTitle: 'Boston Dynamics Atlas Robot — Specs, Parkour & Factory Use | R2BOT',
    metaDescription:
      "Boston Dynamics Atlas humanoid robot profile — full specs, capabilities, the new electric Atlas, and Hyundai's factory deployment.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Model Predictive Control — Atlas', href: '/atlas/concept/model-predictive-control' },
      { label: 'Forward Kinematics — Atlas', href: '/atlas/concept/forward-kinematics' },
    ],
  },
  {
    slug: 'curiosity',
    fameRank: 3,
    name: 'Curiosity',
    emoji: '🪐',
    maker: 'NASA / JPL',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2012,
    type: 'space',
    status: 'active',
    oneLiner: "NASA's car-sized Mars rover — still exploring Gale Crater 13 years after landing.",
    hookLine: "It's been driving on Mars, alone, for 13 years — and it's not done.",
    statChips: [
      { icon: '🪐', text: 'Driving on Mars' },
      { icon: '📅', text: '13+ years' },
      { icon: '⚛️', text: 'Nuclear powered' },
    ],
    inOneSentence: 'Curiosity is a car-sized robot that drives on Mars, drills into rocks, and runs a chemistry lab inside itself.',
    wowFactors: [
      "It runs on a tiny nuclear battery — no sunlight needed for years.",
      "It celebrated its first Mars birthday by humming 'Happy Birthday' to itself.",
      "Its 'Sky-Crane' landing manoeuvre had never been tried before — and worked perfectly.",
    ],
    howItWorksSteps: [
      'Two stereo cameras build 3D maps of the Martian terrain ahead.',
      'Onboard software picks a safe driving path around rocks.',
      "Curiosity drives at 0.14 km/h — slow but ultra-careful.",
      'Robotic arm drills 5-cm-deep cores into rocks for analysis.',
      "The Sample Analysis at Mars (SAM) lab runs chemistry tests on collected samples.",
    ],
    popCulture: 'A Pixar-style NASA animation of the Sky-Crane landing has 30M+ views. Curiosity is the only robot to receive a "Happy Birthday from Earth" Twitter trend yearly.',
    teamBehind: 'Adam Steltzner led the entry-descent-landing team at JPL. Sylvestre Maurice (France) co-led the ChemCam. The full team had ~3,000 engineers and scientists across NASA, JPL, ESA, and partner institutions.',
    description:
      "NASA's Curiosity rover landed on Mars on August 6, 2012 via the famous Skycrane manoeuvre. Curiosity is the size of a small SUV (3 m long, 2.7 m wide, 900 kg) and is powered by a Multi-Mission Radioisotope Thermoelectric Generator (MMRTG) that converts heat from plutonium-238 decay into electricity. Curiosity carries 10 science instruments including ChemCam (a laser that vaporises rocks to analyse their spectra), SAM (Sample Analysis at Mars — a chemistry lab), and Mastcam (high-res cameras). In over 13 years of operation, Curiosity has driven more than 32 km across Mars, drilled 41+ samples, climbed Mount Sharp, and confirmed Mars once had conditions suitable for microbial life.",
    specs: { height: '2.2 m', weight: '899 kg', speed: '0.14 km/h (max)', battery: 'MMRTG (plutonium-238), ~110 W' },
    capabilities: [
      'Autonomous driving and obstacle avoidance',
      'Rock sample drilling and analysis',
      'Laser-induced rock spectroscopy (ChemCam)',
      'On-board chemistry lab (SAM)',
      'High-resolution imaging',
      'Long-distance traverse planning',
    ],
    funFacts: [
      'Curiosity has driven over 32 km on Mars — slower than a tortoise but on another planet.',
      'It celebrates every Mars anniversary by humming "Happy Birthday" to itself.',
      'The "Seven Minutes of Terror" landing was so complex that NASA had no live communication for the entire descent.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=ki_Af_o9Q9s',
    imageAlt: 'NASA Curiosity Mars rover on red Martian soil',
    metaTitle: 'NASA Curiosity Mars Rover — Specs, Mission & Facts | R2BOT',
    metaDescription:
      "NASA's Curiosity Mars rover profile — full specs, the Sky-Crane landing, on-board lab, and what it's discovered in 13+ years on Mars.",
    atlasSlug: 'mars-rover',
    atlasLearnLinks: [
      { label: 'Space Robotics — Atlas', href: '/atlas/concept/space-robotics' },
      { label: 'Planetary Lander — Atlas', href: '/atlas/concept/planetary-lander' },
      { label: 'Autonomous Navigation — Atlas', href: '/atlas/concept/autonomous-vehicle' },
    ],
  },
  {
    slug: 'roomba',
    fameRank: 4,
    name: 'Roomba',
    emoji: '🧹',
    maker: 'iRobot',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2002,
    type: 'consumer',
    status: 'active',
    oneLiner: "The world's most-sold home robot — 40+ million units cleaning floors worldwide.",
    hookLine: 'It has vacuumed more floor than any human in history — 40 million homes.',
    statChips: [
      { icon: '🏠', text: '40M+ homes' },
      { icon: '📅', text: 'Born 2002' },
      { icon: '🌍', text: '~$199 starting' },
    ],
    inOneSentence: 'Roomba is a flat round robot that vacuums your floor by itself, decides where to clean, and goes home to charge when tired.',
    wowFactors: [
      "It uses the same path-planning maths as Mars rovers — to vacuum your bedroom.",
      "iRobot's founders are three MIT roboticists who originally built bomb-disposal robots.",
      "Over 40 million Roombas sold — more than any other home robot in history.",
    ],
    howItWorksSteps: [
      'Bump sensors detect walls, cliff sensors detect stairs, and floor sensors detect carpet vs hard floor.',
      "Newer models use cameras or LIDAR to map your home and remember where to clean.",
      'It picks a coverage pattern — spiral, wall-follow, or smart-mapped — based on the room.',
      'A spinning brush plus suction pulls up dust into an internal bin.',
      'When the battery dips, it navigates to its charging dock and resumes after refilling.',
    ],
    popCulture: 'A 2016 viral video of a cat riding a Roomba in a shark costume has 200M+ collective views. Roombas appear in dozens of films and TV shows including Modern Family and Silicon Valley.',
    teamBehind: 'Rodney Brooks, Colin Angle, and Helen Greiner — three MIT AI Lab alumni — founded iRobot in 1990. Colin Angle was CEO until 2024. The Roomba launched in 2002 and the company went public in 2005.',
    description:
      "iRobot launched the Roomba in September 2002 at a price of $199, making it the first mass-market household robot in history. The original Roomba used simple bump-and-turn algorithms and infrared cliff sensors. Over 20+ years and a dozen generations, the Roomba has evolved to include vSLAM (visual SLAM) mapping, LiDAR navigation, room-by-room cleaning schedules, automatic dirt-disposal docks, and integration with Alexa and Google Home. iRobot has sold over 40 million Roombas and was acquired by Amazon in 2022 (deal later abandoned in 2024).",
    specs: { height: '9 cm', weight: '3.4 kg', speed: '0.3 m/s', battery: 'Lithium-ion, ~75 min' },
    capabilities: [
      'Autonomous floor mapping (vSLAM)',
      'Room recognition and selective cleaning',
      'Carpet boost mode',
      'Automatic recharging and resuming',
      'Self-emptying via Clean Base',
      'Voice and app control',
    ],
    funFacts: [
      'iRobot was founded by three MIT roboticists who originally built bomb-disposal robots for the US military.',
      'The Roomba uses the same path-planning math as Mars rovers — just to clean your bedroom.',
      'iRobot has sold over 40 million Roombas — more than any other home robot in history.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=mRJ1lipfQDQ',
    imageAlt: 'iRobot Roomba robot vacuum cleaning hardwood floor',
    metaTitle: "iRobot Roomba — How the World's Best-Selling Home Robot Works | R2BOT",
    metaDescription:
      "Profile of the iRobot Roomba — 40M+ units sold, vSLAM navigation, history from 2002 launch, and why it created the entire robot vacuum category.",
    atlasSlug: 'consumer-robot',
    atlasLearnLinks: [
      { label: 'Visual SLAM — Atlas', href: '/atlas/concept/visual-slam' },
      { label: 'A* Pathfinding — Atlas', href: '/atlas/concept/a-star-algorithm' },
      { label: 'Differential Drive — Atlas', href: '/atlas/concept/differential-drive' },
    ],
  },
  {
    slug: 'da-vinci',
    fameRank: 5,
    name: 'da Vinci Surgical System',
    emoji: '🏥',
    maker: 'Intuitive Surgical',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 1999,
    type: 'medical',
    status: 'active',
    oneLiner: 'The most successful surgical robot — over 14 million procedures performed worldwide.',
    hookLine: "It has performed 14 million surgeries. Its hands don't shake.",
    statChips: [
      { icon: '🏥', text: '14M+ surgeries' },
      { icon: '🌍', text: '9,000+ systems' },
      { icon: '💰', text: '$2M each' },
    ],
    inOneSentence: 'da Vinci is a robot a surgeon controls from across the room to do tiny, perfect surgeries through holes the size of a coin.',
    wowFactors: [
      'Its EndoWrist instruments have 7 degrees of freedom — more than a human wrist.',
      "DARPA originally funded it so battlefield surgeons could operate remotely.",
      'A single system earns Intuitive Surgical ~$200K/year in service fees on top of its $2M price.',
    ],
    howItWorksSteps: [
      'The surgeon sits at a 3D-vision console a few feet from the patient.',
      'Hand controls and foot pedals translate into millimetric arm motions.',
      'Inside the patient, EndoWrist instruments mimic the surgeon\'s motions through 8 mm incisions.',
      'A tremor filter removes hand shake; motion scaling makes 3 cm of hand motion 1 cm of tool motion.',
      'Fluorescence imaging (Firefly) lets the surgeon see blood vessels glowing in real time.',
    ],
    popCulture: 'Featured in Grey\'s Anatomy, House M.D., and countless news segments. Apollo Hospitals India has run a "Robotic Surgery Open Day" since 2018.',
    teamBehind: 'Founded by Frederic Moll, Robert Younge, and John Freund in 1995, building on DARPA-funded research. Gary Guthart has been CEO since 2010. The system received FDA approval in 2000.',
    description:
      "The da Vinci Surgical System received FDA approval in 2000 and is now the most widely used surgical robot in the world, with over 14 million procedures performed across 9,000+ hospitals globally. da Vinci is a teleoperated robot — the surgeon sits at a console with 3D high-definition stereo vision and uses hand controls to manipulate four robotic arms holding tiny instruments inside the patient through small incisions. Its EndoWrist instruments offer seven degrees of freedom — more than the human wrist. da Vinci is used for prostatectomy, hysterectomy, cardiac surgery, hernia repair, and increasingly general surgery.",
    specs: { weight: '~600 kg', payload: 'Surgical instruments via 4 arms', dof: '7 DOF per instrument', reach: '0.5 m' },
    capabilities: [
      'Tremor-filtered precision movement',
      '3D HD stereo vision (10× magnification)',
      'Articulating EndoWrist instruments',
      'Multi-arm tele-operation',
      'Fluorescence imaging (Firefly)',
      'Remote training and simulation',
    ],
    funFacts: [
      'da Vinci was funded by DARPA in the 1990s with the goal of letting surgeons operate on battlefield casualties remotely.',
      'The robot has performed over 14 million surgeries — more than any other robotic medical device.',
      'A single da Vinci system costs $2 million and earns Intuitive Surgical ~$200K/year in service contracts and disposables.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=0XdC1HUp-rU',
    imageAlt: 'da Vinci Surgical robot arms over a hospital operating table',
    metaTitle: "da Vinci Surgical Robot — How the World's Top Surgery Robot Works | R2BOT",
    metaDescription:
      "Intuitive Surgical's da Vinci robot profile — 14M+ surgeries performed, full specs, EndoWrist instruments, and why it dominates robotic surgery.",
    atlasSlug: 'surgical-robot',
    atlasLearnLinks: [
      { label: 'Surgical Robot — Atlas', href: '/atlas/concept/surgical-robot' },
      { label: 'Teleoperation — Atlas', href: '/atlas/concept/teleoperation' },
      { label: 'Haptic Feedback — Atlas', href: '/atlas/concept/haptic-feedback' },
    ],
  },
  {
    slug: 'asimo',
    fameRank: 6,
    name: 'ASIMO',
    emoji: '🚶',
    maker: 'Honda',
    country: 'Japan',
    countryFlag: '🇯🇵',
    year: 2000,
    type: 'humanoid',
    status: 'retired',
    oneLiner: "Honda's iconic walking humanoid — the most advanced bipedal robot of its decade.",
    hookLine: 'It took Honda 15 years of secret research before they showed the world.',
    statChips: [
      { icon: '📅', text: '2000–2018' },
      { icon: '🤫', text: '14 years secret R&D' },
      { icon: '🚶', text: '9 km/h running' },
    ],
    inOneSentence: 'ASIMO is the friendly white humanoid Honda built to prove a robot could walk like a person — and it did, on tour, for two decades.',
    wowFactors: [
      'Honda spent ~$1 billion on Project E in secret from 1986 to 2000.',
      'It famously tripped on stage in 2006 — the most-viewed humanoid robot video of the decade.',
      'Only ~100 ASIMOs were ever built; each cost approximately $1 million.',
    ],
    howItWorksSteps: [
      "57 servomotors in legs, arms, and hands produce human-like motion.",
      'An IMU and force sensors in the feet detect balance moment to moment.',
      "Stereo cameras in the head recognise faces and gestures.",
      'Onboard battery and computer make ASIMO fully self-contained.',
      'A simple programming interface lets researchers teach ASIMO new behaviours.',
    ],
    popCulture: 'ASIMO appeared on The Tonight Show, met Barack Obama, and toured Disneyland Paris. It is one of the most-photographed robots in history.',
    teamBehind: "Honda's Project E was led by Masato Hirose. The ASIMO programme was overseen by Honda's R&D Division. Honda officially retired ASIMO in 2018, but kept one operational at the Miraikan museum in Tokyo.",
    description:
      "Honda's ASIMO (Advanced Step in Innovative Mobility) was unveiled in 2000 after 14 years of secret bipedal research. ASIMO could walk, run at 9 km/h, climb stairs, recognise faces and voices, kick a football, pour drinks, and dance. Standing 130 cm and weighing 54 kg, ASIMO became the public face of humanoid robotics for nearly two decades. Honda retired the program in 2018 to redirect resources, but every modern humanoid stands on ASIMO's engineering foundations.",
    specs: { height: '130 cm', weight: '54 kg', speed: '9 km/h (running)', battery: '48V lithium-ion, ~1 hour', dof: '57 degrees of freedom' },
    capabilities: [
      'Bipedal walking and running',
      'Stair climbing on uneven surfaces',
      'Object recognition and grasping',
      'Voice and face recognition',
      'Multi-language conversation',
      'Real-time balance correction',
    ],
    funFacts: [
      'ASIMO is the first humanoid to run with both feet off the ground at the same time.',
      'It tripped on stage in front of an audience in 2006 — a moment that became the most-viewed humanoid robot video of the decade.',
      'Honda built only ~100 ASIMO units; each cost roughly $1 million to manufacture.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=QdQL11uWWcI',
    imageAlt: 'Honda ASIMO humanoid robot in white shell standing on stage',
    metaTitle: "ASIMO Robot — Honda Humanoid Specs, History & Facts | R2BOT",
    metaDescription:
      "Complete profile of Honda's ASIMO humanoid robot — specs, capabilities, retirement, and why it influenced every modern humanoid from Atlas to Optimus.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Servo Motor — Atlas', href: '/atlas/concept/servo-motor' },
      { label: 'IMU — Atlas', href: '/atlas/concept/imu' },
    ],
  },
  {
    slug: 'optimus',
    fameRank: 7,
    name: 'Optimus',
    emoji: '🦾',
    maker: 'Tesla',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2022,
    type: 'humanoid',
    status: 'active',
    oneLiner: "Tesla's general-purpose humanoid robot — targeted to cost under $20,000.",
    hookLine: 'It works 22 hours a day in a Tesla factory. No salary. No complaints.',
    statChips: [
      { icon: '🎯', text: 'Target: <$20K' },
      { icon: '🦾', text: '28 actuators' },
      { icon: '🤖', text: 'Tesla FSD brain' },
    ],
    inOneSentence: 'Optimus is the robot Elon Musk says could one day be cheaper than a car — and bigger business for Tesla than cars.',
    wowFactors: [
      'It uses the same neural-network stack as Tesla cars.',
      'Elon claims Optimus may one day be Tesla\'s largest source of revenue.',
      'Tesla aims to mass-produce it at the same scale as cars, hitting under $20K each.',
    ],
    howItWorksSteps: [
      '8 cameras (the same Tesla Vision setup as cars) build a real-time 3D scene.',
      'A custom neural network plans next actions in milliseconds.',
      '28 actuators move limbs and torso; 11 DOF per hand grasp delicate objects.',
      'Onboard battery gives ~5 hours of work before swap or charge.',
      'Robots are continually retrained from real factory floor data.',
    ],
    popCulture: 'Optimus made its debut at Tesla AI Day 2022 — initially with a person in a costume, which was widely mocked. By 2024 the live robot was serving drinks at the Cybercab event.',
    teamBehind: 'Tesla CEO Elon Musk announced Optimus; the engineering effort spans Tesla\'s AI, vehicle, and battery teams. Notable contributors include Milan Kovac and (formerly) Andrej Karpathy.',
    description:
      "Tesla unveiled Optimus at AI Day 2022 with the goal of building a mass-produced humanoid robot. Tesla's pitch: build at car-scale economics so a humanoid eventually costs less than a Model 3. Optimus stands 173 cm and weighs 57 kg, with 28 actuators, hands with 11 DOF each, and the same FSD neural-network stack Tesla uses in cars. Tesla started deploying Optimus prototypes at its Fremont and Gigafactory Texas plants in 2024.",
    specs: { height: '173 cm', weight: '57 kg', speed: '8 km/h (target)', payload: '20 kg', battery: '2.3 kWh, ~5 hours', dof: '28 + 11 per hand' },
    capabilities: [
      'Bipedal walking',
      'Whole-body manipulation',
      '11-DOF dexterous hands',
      'Object recognition (Tesla Vision stack)',
      'Voice interaction',
      'Battery swapping for continuous operation',
    ],
    funFacts: [
      'Tesla aims to price Optimus under $20,000 — less than a Model 3.',
      'Optimus uses the same neural network architecture as Tesla cars.',
      "Elon Musk has said Optimus could one day be Tesla's largest source of revenue, exceeding cars.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=cpraXaw7dyc',
    imageAlt: 'Tesla Optimus humanoid robot walking in a factory',
    metaTitle: 'Tesla Optimus Robot — Specs, Price & Factory Deployment | R2BOT',
    metaDescription:
      "Tesla Optimus humanoid robot profile — sub-$20K target price, 28 actuators, deployment in Tesla factories, and Elon Musk's vision for the product.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Transformer Architecture — Atlas', href: '/atlas/concept/transformer-architecture' },
      { label: 'Foundation Model Robotics — Atlas', href: '/atlas/concept/foundation-model-robotics' },
    ],
  },
  {
    slug: 'sophia',
    fameRank: 8,
    name: 'Sophia',
    emoji: '👩',
    maker: 'Hanson Robotics',
    country: 'Hong Kong',
    countryFlag: '🇭🇰',
    year: 2016,
    type: 'humanoid',
    status: 'active',
    oneLiner: "Hanson Robotics' celebrity humanoid — the first robot ever granted citizenship of a country.",
    hookLine: 'The first robot in history to become a citizen — of Saudi Arabia, in 2017.',
    statChips: [
      { icon: '🛂', text: 'Saudi citizen 2017' },
      { icon: '📺', text: 'UN speaker' },
      { icon: '🎬', text: '50+ TV shows' },
    ],
    inOneSentence: "Sophia is a humanoid robot with a moving face designed to look like Audrey Hepburn — and she's been on The Tonight Show, Vogue, and the United Nations stage.",
    wowFactors: [
      'In 2017 Saudi Arabia granted her citizenship — the first robot citizen of any country.',
      "Her face was modelled after Audrey Hepburn and Hanson's wife.",
      "She walked the Vogue runway, addressed the UN, and trended on Twitter dozens of times.",
    ],
    howItWorksSteps: [
      'A camera in her chest detects human faces.',
      'Silicone skin called "Frubber" lets her produce 50+ facial expressions.',
      'A neural-network-based language model generates conversational responses.',
      'Pre-scripted dialogue plus live AI mix for media appearances.',
      "She is wheeled-base or table-mounted; she does not walk.",
    ],
    popCulture: 'Featured on The Tonight Show with Jimmy Fallon, the cover of Cosmopolitan India, the Vogue Brasil runway, and the UN AI for Good summit.',
    teamBehind: 'Designed by Texan roboticist David Hanson at Hong Kong-based Hanson Robotics. Sophia first activated in 2015 and was unveiled in 2016.',
    description:
      "Sophia was unveiled by Hong Kong-based Hanson Robotics in 2016 and quickly became the world's most famous humanoid robot. With realistic silicone facial expressions, neural-network-driven speech, and a public personality designed for media appearances, Sophia has appeared on The Tonight Show, addressed the United Nations, walked Vogue runway, and been interviewed by countless media outlets. In October 2017, Saudi Arabia granted Sophia citizenship — making her the first robot ever to receive citizenship of any country.",
    specs: { height: '~170 cm (with base)', weight: '20 kg (head and torso)', dof: '40+ facial actuators' },
    capabilities: [
      'Realistic facial expressions (50+)',
      'Speech generation (scripted + neural)',
      'Eye tracking and gaze direction',
      'Recorded voice and live dialogue mode',
      'Recognition of human emotions',
      'Limited wheel- or leg-based mobility',
    ],
    funFacts: [
      'Sophia was granted Saudi Arabian citizenship in 2017 — the first robot in history to be a legal citizen of any country.',
      "Sophia's face was modelled after Audrey Hepburn and Hanson's wife.",
      'She has been on the cover of Cosmopolitan India and walked the Vogue runway.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=78-1MlkxyqI',
    imageAlt: 'Hanson Robotics Sophia humanoid robot with realistic face',
    metaTitle: 'Sophia Robot — Hanson Robotics Humanoid With Saudi Citizenship | R2BOT',
    metaDescription:
      "Sophia humanoid robot profile — Hanson Robotics, Saudi citizenship in 2017, media appearances, and what she can actually do.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Social Robotics — Atlas', href: '/atlas/concept/social-robotics' },
      { label: 'Robot Ethics — Atlas', href: '/atlas/concept/robot-ethics' },
    ],
  },
  {
    slug: 'perseverance',
    fameRank: 9,
    name: 'Perseverance',
    emoji: '🛰️',
    maker: 'NASA / JPL',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2021,
    type: 'space',
    status: 'active',
    oneLiner: "NASA's newest Mars rover — collecting samples for return to Earth and flying the Ingenuity helicopter.",
    hookLine: 'It carried the first helicopter ever to fly on another planet.',
    statChips: [
      { icon: '🪐', text: 'Mars since 2021' },
      { icon: '🚁', text: 'Ingenuity helicopter' },
      { icon: '💨', text: 'Made oxygen from CO2' },
    ],
    inOneSentence: "Perseverance is a 1-tonne Mars rover that brings its own helicopter, makes oxygen from Martian air, and collects rocks for future astronauts to fetch.",
    wowFactors: [
      "Its companion Ingenuity made 72 flights on Mars — first aviation on another planet.",
      "Its MOXIE instrument successfully produced oxygen from Martian CO2 — 16 times.",
      "It carried the first microphone ever to record sound on Mars.",
    ],
    howItWorksSteps: [
      'Six wheels with independent suspension drive over rough terrain.',
      'Stereo cameras and laser-rangefinders avoid hazards autonomously.',
      'A robotic arm drills cores and stores them in titanium sample tubes.',
      'PIXL and SHERLOC analyse rock chemistry on the spot.',
      'The Mars Sample Return mission (planned 2030s) will fetch the cached samples.',
    ],
    popCulture: "NASA's 'Daring Mighty Things' landing video has 30M+ views. Ingenuity's first flight on Mars trended worldwide.",
    teamBehind: 'NASA Jet Propulsion Laboratory (JPL) led the mission. Mission leadership included Ken Williford (project scientist) and Adam Steltzner (entry-descent-landing lead, also worked on Curiosity).',
    description:
      "Perseverance landed on Mars in Jezero Crater on February 18, 2021 — the largest, heaviest, and most sophisticated rover ever sent to another planet. It is a direct evolution of Curiosity's chassis but with seven new instruments. Perseverance also carried Ingenuity, the first robotic helicopter to fly on another planet, which completed 72 flights before retiring in 2024. The rover is collecting and sealing rock samples in titanium tubes for a future Mars Sample Return mission.",
    specs: { height: '2.2 m', weight: '1,025 kg', speed: '0.16 km/h (max)', battery: 'MMRTG (plutonium-238), ~110 W' },
    capabilities: [
      'Autonomous sample caching',
      'Production of oxygen from Martian CO2 (MOXIE)',
      'High-precision X-ray spectroscopy (PIXL)',
      'UV organic detection (SHERLOC)',
      'Microphone — first to record Martian audio',
      'Carrying and supporting Ingenuity helicopter',
    ],
    funFacts: [
      "Perseverance carried the first microphone to actually record sound on Mars.",
      'MOXIE successfully made breathable oxygen on Mars 16 times.',
      "Ingenuity made 72 flights before crash-landing in 2024 — far exceeding its planned five.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=4czjS9h4Fpg',
    imageAlt: 'NASA Perseverance rover with Ingenuity helicopter on Mars',
    metaTitle: 'NASA Perseverance Mars Rover — Sample Return & Ingenuity | R2BOT',
    metaDescription:
      "NASA's Perseverance rover and Ingenuity helicopter profile — Mars sample caching, MOXIE oxygen production, and 72 flights on another planet.",
    atlasSlug: 'mars-rover',
    atlasLearnLinks: [
      { label: 'Space Robotics — Atlas', href: '/atlas/concept/space-robotics' },
      { label: 'Planetary Lander — Atlas', href: '/atlas/concept/planetary-lander' },
      { label: 'Sensor Fusion — Atlas', href: '/atlas/concept/sensor-fusion' },
    ],
  },
  {
    slug: 'figure-02',
    fameRank: 10,
    name: 'Figure 02',
    emoji: '🤖',
    maker: 'Figure AI',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2024,
    type: 'humanoid',
    status: 'active',
    oneLiner: "Figure AI's second-generation humanoid — already working in BMW's South Carolina factory.",
    hookLine: 'It works on the BMW assembly line. The factory pays Figure by the part.',
    statChips: [
      { icon: '🏭', text: 'BMW factory' },
      { icon: '💰', text: '$2.6B valuation' },
      { icon: '🧠', text: 'OpenAI brain' },
    ],
    inOneSentence: 'Figure 02 is the first humanoid robot to actually get paid for factory work — and it talks to you in OpenAI voice.',
    wowFactors: [
      'First humanoid to do real factory work alongside humans (BMW Spartanburg).',
      'Microsoft, OpenAI, Bezos, and NVIDIA all invested in the 2024 round.',
      'Conversational voice powered by OpenAI GPT models, embedded in the robot.',
    ],
    howItWorksSteps: [
      'Six RGB cameras give 360° vision of the workspace.',
      'A custom neural network maps sensor input to motor commands.',
      'OpenAI-powered language model handles conversation and instructions.',
      '16 actuators move limbs and torso; battery swap keeps it running shifts.',
      "Continuous learning improves performance from every shift's data.",
    ],
    popCulture: "The 'Figure 02 makes coffee' demo went viral in early 2024. Figure's pitch deck is reportedly the most-shared startup deck of the 2020s.",
    teamBehind: 'Brett Adcock founded Figure AI in 2022 (previously founded Archer Aviation). Engineering leadership includes ex-Boston Dynamics, ex-Tesla, and ex-Apple talent.',
    description:
      "Figure AI was founded in 2022 by Brett Adcock with the goal of building general-purpose humanoid robots. Figure 02, unveiled in August 2024, is the company's second-generation robot. It stands 168 cm tall, weighs 70 kg, and is equipped with 16 actuators, six RGB cameras, OpenAI-powered conversation, and 3× the on-board compute of its predecessor. Figure 02 is already deployed at BMW's Spartanburg, South Carolina assembly plant. Figure has raised over $1.5 billion at a $2.6 billion valuation.",
    specs: { height: '168 cm', weight: '70 kg', speed: '1.2 m/s', payload: '20 kg', battery: '2.25 kWh, ~5 hours', dof: '16 actuators' },
    capabilities: [
      'Sheet-metal-part insertion (BMW)',
      'OpenAI voice conversation',
      'Six RGB cameras for 360° vision',
      'Battery swap for continuous shift work',
      '3× compute vs Figure 01',
      'Whole-body manipulation',
    ],
    funFacts: [
      'Figure 02 is the first humanoid robot to do real factory work in BMW production.',
      'Figure raised $675M in 2024 from Microsoft, OpenAI, and Bezos — valuing it at $2.6 billion.',
      'OpenAI provides the conversational brain for Figure 02.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=0SRVJaOg9Co',
    imageAlt: 'Figure 02 humanoid robot working at a BMW factory line',
    metaTitle: 'Figure 02 Humanoid Robot — BMW Factory Deployment & Specs | R2BOT',
    metaDescription:
      "Figure 02 humanoid robot profile — BMW factory deployment, OpenAI-powered conversation, $2.6B valuation, and the race against Tesla Optimus.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Large Language Models for Robotics — Atlas', href: '/atlas/concept/large-language-model-robotics' },
      { label: 'Sim-to-Real Transfer — Atlas', href: '/atlas/concept/sim-to-real-transfer' },
    ],
  },
  {
    slug: 'aibo',
    fameRank: 11,
    name: 'AIBO',
    emoji: '🐕‍🦺',
    maker: 'Sony',
    country: 'Japan',
    countryFlag: '🇯🇵',
    year: 1999,
    type: 'companion',
    status: 'active',
    oneLiner: "Sony's robotic dog — the first mass-market consumer companion robot.",
    hookLine: 'When AIBO units broke and Sony stopped support, Japanese owners held funerals for them.',
    statChips: [
      { icon: '📅', text: 'Born 1999' },
      { icon: '🐶', text: '22 axes (ERS-1000)' },
      { icon: '🌍', text: '150K+ sold' },
    ],
    inOneSentence: "AIBO is a small robot dog that learns your face, comes when you call, and develops a personality over time — like a real pet.",
    wowFactors: [
      "When Sony stopped supporting it in 2014, Japanese owners held Shinto funerals for broken AIBOs.",
      "AIBO ERS-1000 has OLED eyes that display over 100 different expressions.",
      "The first 3,000 units sold out in 20 minutes in 1999.",
    ],
    howItWorksSteps: [
      'Touch, camera, and microphone sensors detect owner interactions.',
      'A neural-network-based personality engine learns what AIBO likes and dislikes.',
      '22 axes of motion produce realistic walking, head movement, and tail wagging.',
      'Cloud-connected memory means AIBO remembers your family across years.',
      'A docking station handles charging automatically.',
    ],
    popCulture: 'Featured in films, TV shows, and a famous "AIBO Funeral" ritual at Buddhist temples in Japan. The relaunched ERS-1000 won the Best of Innovation at CES 2018.',
    teamBehind: 'AIBO was led by Toshitada Doi at Sony Research, who also led the development of the PlayStation. The first commercial unit shipped in 1999.',
    description:
      "Sony launched the original AIBO in 1999 at ¥250,000. The first 3,000 units sold out in 20 minutes. AIBO uses neural networks and emotion algorithms to develop a unique personality over time. It learns its owner, recognises faces and voice commands, plays with toys, and exhibits moods. Sony relaunched AIBO as the ERS-1000 in 2018 with significantly upgraded hardware — 22 axes of motion, OLED eyes, deep learning, and cloud-connected memory.",
    specs: { height: '30 cm', weight: '2.2 kg', battery: '~2 hours runtime', dof: '22 axes (ERS-1000)' },
    capabilities: [
      'Owner and face recognition',
      'Voice command understanding',
      'Personality development over time',
      'Trick learning (sit, paw, dance)',
      'Cloud-backed memory',
      'Touch and patting response',
    ],
    funFacts: [
      'When Sony discontinued AIBO support in 2014, Japanese owners held Shinto funeral ceremonies for their broken robots.',
      'AIBO ERS-1000 has OLED eyes that display over 100 different expressions.',
      'Sony sold 150,000 AIBOs between 1999 and 2006.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=jXBeFiL_QHE',
    imageAlt: 'Sony AIBO robotic dog with OLED eyes',
    metaTitle: 'Sony AIBO Robot Dog — Specs, History & Personality Engine | R2BOT',
    metaDescription:
      "Sony AIBO robotic dog profile — from 1999 launch to the modern ERS-1000, personality engine, and why it became Japan's most-loved companion robot.",
    atlasSlug: 'companion-robot',
    atlasLearnLinks: [
      { label: 'Companion Robot — Atlas', href: '/atlas/concept/embodied-ai' },
      { label: 'Social Robotics — Atlas', href: '/atlas/concept/social-robotics' },
      { label: 'Convolutional Neural Network — Atlas', href: '/atlas/concept/convolutional-neural-network' },
    ],
  },
  {
    slug: 'pepper',
    fameRank: 12,
    name: 'Pepper',
    emoji: '👋',
    maker: 'SoftBank Robotics',
    country: 'France / Japan',
    countryFlag: '🇫🇷',
    year: 2014,
    type: 'service',
    status: 'active',
    oneLiner: 'The first humanoid built to read human emotions — used as a receptionist in hotels, banks, and shops.',
    hookLine: 'It reads your face. If you look sad, it changes how it talks to you.',
    statChips: [
      { icon: '🌍', text: '2,000+ sites' },
      { icon: '🗣️', text: '15+ languages' },
      { icon: '👁️', text: '3D vision' },
    ],
    inOneSentence: "Pepper is a 120-cm humanoid robot designed to live with humans — it looks at your face, hears your voice tone, and tries to be your friend.",
    wowFactors: [
      'First humanoid robot designed to live and interact with humans.',
      'Two Peppers were "married" in a Tokyo Shinto ceremony in 2015 as a publicity stunt.',
      'SoftBank deployed Pepper across 2,000+ enterprise sites — banks, hotels, schools.',
    ],
    howItWorksSteps: [
      "3D cameras in Pepper's eyes map every human face nearby.",
      'Microphones detect voice tone, pitch, and language.',
      'An emotion engine combines these inputs to estimate mood.',
      'Pepper adjusts its voice, expression, and gestures based on detected mood.',
      'A touchscreen on its chest lets users interact directly.',
    ],
    popCulture: "Pepper has greeted Pope Francis, served as a receptionist at SoftBank Mobile stores in Japan, and appeared in dozens of news segments.",
    teamBehind: 'Aldebaran Robotics (France), founded by Bruno Maisonnier, designed Pepper. SoftBank acquired Aldebaran in 2012 and rebranded it SoftBank Robotics. Pepper launched in 2014.',
    description:
      "Pepper was launched in 2014 by SoftBank Robotics as the first humanoid robot designed specifically to live and interact with humans. Standing 120 cm tall on a wheeled base, Pepper was built to read facial expressions, voice tone, and body language to gauge human emotion. SoftBank deployed Pepper as a receptionist in hotels, a customer-service agent in banks, a greeter in shops, and an entertainer at events. Pepper sold over 27,000 units. SoftBank paused production in 2021 due to weak demand.",
    specs: { height: '120 cm', weight: '28 kg', speed: '3 km/h', battery: 'Lithium-ion, 12 hours', dof: '20 degrees of freedom' },
    capabilities: [
      'Emotion recognition via face and voice',
      'Multi-language conversation (15+ languages)',
      'Touchscreen-based interaction',
      'Gesture-based expression',
      'Object and person tracking',
      '360° obstacle avoidance via lasers',
    ],
    funFacts: [
      "Pepper's eyes are actually 3D cameras that map human faces in real time.",
      "Two Peppers were 'married' in a Tokyo Shinto ceremony in 2015.",
      'SoftBank paused Pepper production in 2021 after selling around 27,000 units.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=mt2giQU4cYg',
    imageAlt: 'SoftBank Pepper humanoid robot with tablet greeting a customer',
    metaTitle: 'SoftBank Pepper Robot — Emotional Humanoid Specs & Use Cases | R2BOT',
    metaDescription:
      "Full profile of SoftBank Pepper — the first emotion-reading humanoid, used as a receptionist in hotels, banks, and shops worldwide.",
    atlasSlug: 'service-robot',
    atlasLearnLinks: [
      { label: 'Service Robot — Atlas', href: '/atlas/concept/service-robot' },
      { label: 'Social Robotics — Atlas', href: '/atlas/concept/social-robotics' },
      { label: 'Speech Recognition — Atlas', href: '/atlas/concept/speech-recognition' },
    ],
  },
  {
    slug: 'nao',
    fameRank: 13,
    name: 'NAO',
    emoji: '🤖',
    maker: 'Aldebaran Robotics / SoftBank',
    country: 'France',
    countryFlag: '🇫🇷',
    year: 2008,
    type: 'educational',
    status: 'active',
    oneLiner: "The world's most-used educational humanoid — in 70+ countries.",
    hookLine: "It taught more kids to code robotics than any other robot — in 70+ countries.",
    statChips: [
      { icon: '🏫', text: '13,000+ schools' },
      { icon: '🌍', text: '70 countries' },
      { icon: '🗣️', text: '20 languages' },
    ],
    inOneSentence: 'NAO is a 58-cm humanoid robot used in classrooms worldwide to teach kids and PhD students how to programme robots — and it plays football too.',
    wowFactors: [
      "Plays in the official RoboCup Standard Platform League — fully autonomous robot football.",
      "Over 13,000 NAOs in 70+ countries — the most-deployed humanoid in education.",
      'Used in autism-therapy programmes around the world to help children connect.',
    ],
    howItWorksSteps: [
      'Two HD cameras and four microphones build a 360° view.',
      "25 joint actuators produce smooth walking, dancing, and gesture motion.",
      'Choregraphe, a visual programming tool, lets even beginners script NAO.',
      'Python and C++ APIs give researchers deep control.',
      'Sonar rangefinders prevent collisions; touch sensors detect interaction.',
    ],
    popCulture: 'NAO is the official robot of RoboCup Standard Platform League. It appears in dozens of TED talks and university robotics demos.',
    teamBehind: 'Aldebaran Robotics in Paris, founded by Bruno Maisonnier in 2005, built NAO. SoftBank Robotics took over after acquiring Aldebaran in 2012.',
    description:
      "NAO is a 58 cm tall programmable humanoid robot launched by Aldebaran Robotics (France) in 2008 and later acquired by SoftBank. Designed as an open programmable platform, NAO became the standard educational humanoid worldwide — found in 13,000+ schools, universities, and research labs across 70 countries. NAO is also the official robot for the RoboCup Standard Platform League, where teams program NAOs to play autonomous football.",
    specs: { height: '58 cm', weight: '5.4 kg', speed: '0.4 m/s', battery: '~1.5 hours', dof: '25 degrees of freedom' },
    capabilities: [
      'Bipedal walking and dancing',
      'Multi-language conversation',
      'Face and emotion recognition',
      'Programmable via Python, C++, Choregraphe',
      'Autism therapy interaction protocols',
      'RoboCup football play',
    ],
    funFacts: [
      'NAOs play in the official RoboCup Standard Platform League.',
      'Over 13,000 NAOs are used in schools and labs in 70+ countries.',
      'NAO speaks 20 languages, including Mandarin and Arabic.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=2STTNYNF4lk',
    imageAlt: 'Aldebaran NAO small humanoid robot waving',
    metaTitle: "NAO Robot — The World's Most-Used Educational Humanoid | R2BOT",
    metaDescription:
      "Aldebaran NAO humanoid robot profile — 25 DOF, used in 13,000+ schools globally, and the standard platform for RoboCup football.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Servo Motor — Atlas', href: '/atlas/concept/servo-motor' },
      { label: 'Python for Robotics — Atlas', href: '/atlas/concept/python-robotics' },
    ],
  },
  {
    slug: 'paro',
    fameRank: 14,
    name: 'PARO',
    emoji: '🦭',
    maker: 'AIST',
    country: 'Japan',
    countryFlag: '🇯🇵',
    year: 2001,
    type: 'medical',
    status: 'active',
    oneLiner: "Japan's robotic baby seal — used in 30+ countries as a therapeutic companion for dementia patients.",
    hookLine: 'A robot seal that calms dementia patients more reliably than psychotropic drugs.',
    statChips: [
      { icon: '🏥', text: 'FDA medical device' },
      { icon: '🌍', text: '30+ countries' },
      { icon: '🦭', text: '2.7 kg fluff' },
    ],
    inOneSentence: 'PARO is a soft robot baby seal — designed to be cuddled by dementia patients, who calm down when they hold it.',
    wowFactors: [
      'FDA-classified as a medical device — rare for a robot.',
      'Reduces psychotropic medication use in dementia patients by up to 30%.',
      'Charged via a pacifier-like attachment — making the experience feel like caring for a real baby seal.',
    ],
    howItWorksSteps: [
      'Five sensors (touch, light, audio, temperature, posture) detect interaction.',
      'A behaviour engine generates one of five emotional behaviours in response.',
      'PARO learns its owner\'s name and adjusts behaviour accordingly.',
      "Antibacterial fake fur stays clean across many patients.",
      'A pacifier charger restores 6+ hours of battery life.',
    ],
    popCulture: 'Featured in BBC, NHK, and CNN documentaries on dementia care. Indian hospitals have started limited PARO pilots from 2024.',
    teamBehind: 'Designed by Dr. Takanori Shibata at AIST (Japan\'s National Institute of Advanced Industrial Science and Technology). First commercial release in 2004.',
    description:
      "PARO is a therapeutic robotic baby harp seal developed by AIST and first commercially released in 2004. It was designed by Dr. Takanori Shibata as a tool to reduce stress, agitation, and loneliness in dementia patients, elderly residents of care homes, and children with autism. PARO is covered in antibacterial fake fur, contains five sensors, and responds to being held, stroked, and spoken to. PARO is classified as a medical device by the US FDA.",
    specs: { height: '57 cm long', weight: '2.7 kg', battery: 'Lithium-ion, charged via pacifier' },
    capabilities: [
      'Touch and stroke response',
      'Voice recognition (name learning)',
      'Five distinct emotional behaviours',
      'Day/night cycle awareness',
      'Antibacterial fake fur',
      'Therapeutic mode for dementia',
    ],
    funFacts: [
      'PARO is classified as a medical device by the US FDA.',
      'Studies show PARO reduces psychotropic medication use in dementia patients by up to 30%.',
      'It is charged via a pacifier-like attachment.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=oJq5PQZHU-I',
    imageAlt: 'PARO therapeutic robotic baby seal being held by an elderly patient',
    metaTitle: 'PARO Robotic Baby Seal — Therapeutic Robot for Dementia Care | R2BOT',
    metaDescription:
      "PARO therapeutic robot profile — FDA-classified medical device, used in 30+ countries for dementia and autism care.",
    atlasSlug: 'therapeutic-robot',
    atlasLearnLinks: [
      { label: 'Companion Robot — Atlas', href: '/atlas/concept/embodied-ai' },
      { label: 'Human-Robot Interaction — Atlas', href: '/atlas/concept/human-robot-interaction' },
      { label: 'Service Robot — Atlas', href: '/atlas/concept/service-robot' },
    ],
  },
  {
    slug: 'vyommitra',
    fameRank: 15,
    name: 'Vyommitra',
    emoji: '🚀',
    maker: 'ISRO',
    country: 'India',
    countryFlag: '🇮🇳',
    year: 2020,
    type: 'humanoid',
    status: 'active',
    oneLiner: "ISRO's space-qualified female humanoid — built to fly on India's Gaganyaan crewed mission.",
    hookLine: "India's first space astronaut robot — she speaks six languages and is about to fly to space.",
    statChips: [
      { icon: '🇮🇳', text: 'ISRO-built' },
      { icon: '🚀', text: 'Gaganyaan mission' },
      { icon: '🗣️', text: '6 languages' },
    ],
    inOneSentence: 'Vyommitra is a half-humanoid robot built by ISRO to fly into space on uncrewed test flights before Indian astronauts go.',
    wowFactors: [
      "Speaks six Indian languages including Hindi, English, Tamil, and Telugu.",
      'First space-qualified humanoid robot built in India.',
      "Her name means 'Friend of Space' in Sanskrit.",
    ],
    howItWorksSteps: [
      'Torso and head house cameras, mics, and onboard compute.',
      'Two arms manipulate Gaganyaan crew-module switches and panels.',
      'Face/voice recognition identifies crew members during flight.',
      'Life-support sensors monitor cabin environment (pressure, gases, temperature).',
      'Radiation-hardened electronics survive launch and space conditions.',
    ],
    popCulture: 'Unveiled at the 2020 Human Spaceflight Symposium in Bengaluru. Featured in dozens of Indian news outlets and trends on social media every Gaganyaan update.',
    teamBehind: 'Built by ISRO\'s U.R. Rao Satellite Centre and Vikram Sarabhai Space Centre. Project led by ISRO chairman S. Somanath and the Gaganyaan team.',
    description:
      "Vyommitra (from Sanskrit Vyom = space, Mitra = friend) is a humanoid robot built by the Indian Space Research Organisation (ISRO) for the Gaganyaan crewed space mission. Unveiled in January 2020, Vyommitra is a 'half-humanoid' (torso, arms, head, no legs) designed to fly inside the Gaganyaan crew module on uncrewed test flights before Indian astronauts fly. Vyommitra can monitor the spacecraft's environment, switch panel operations, perform life-support functions, recognise crew members, and answer their queries in Hindi and English.",
    specs: { height: '~155 cm', weight: 'Not publicly disclosed', dof: 'Multiple in arms and head' },
    capabilities: [
      'Multi-language conversation (6 languages)',
      'Panel operation and switch control',
      'Life-support monitoring',
      'Crew recognition and interaction',
      'Spacecraft environment monitoring',
      'Space-qualified electronics',
    ],
    funFacts: [
      "Vyommitra's name literally means 'friend of space' in Sanskrit.",
      'She can speak six Indian languages.',
      'Vyommitra is the first space-qualified humanoid robot built in India.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=4cWBh1qO6mY',
    imageAlt: 'ISRO Vyommitra female humanoid robot for Gaganyaan mission',
    metaTitle: "Vyommitra — ISRO's Female Humanoid for Gaganyaan Mission | R2BOT",
    metaDescription:
      "ISRO Vyommitra space humanoid profile — Gaganyaan crewed mission, six-language speech, and India's first space-qualified robot.",
    atlasSlug: 'humanoid-robot',
    atlasLearnLinks: [
      { label: 'ISRO Robotics — Atlas', href: '/atlas/concept/isro-robotics' },
      { label: 'Humanoid Robot — Atlas', href: '/atlas/concept/humanoid-robot' },
      { label: 'Space Robotics — Atlas', href: '/atlas/concept/space-robotics' },
    ],
  },
  {
    slug: 'grey-orange-butler',
    fameRank: 16,
    name: 'GreyOrange Butler',
    emoji: '📦',
    maker: 'GreyOrange',
    country: 'India',
    countryFlag: '🇮🇳',
    year: 2015,
    type: 'warehouse',
    status: 'active',
    oneLiner: "India's flagship warehouse robot — 600+ Butlers in Flipkart's Pune fulfillment centre.",
    hookLine: "An Indian robot that lifts a 1,000-kg shelf and brings it to a human picker.",
    statChips: [
      { icon: '🇮🇳', text: 'Made in India' },
      { icon: '📦', text: '600+ at Flipkart' },
      { icon: '🦄', text: '$1B+ valuation' },
    ],
    inOneSentence: 'Butler is an Indian-built warehouse robot that ducks under shelves, lifts them up, and carries them across a giant warehouse floor.',
    wowFactors: [
      "GreyOrange's founders met at BITS Pilani and built India's first robotics unicorn.",
      "Flipkart's Pune warehouse uses 600+ Butlers — the largest AMR deployment in India.",
      'Achieved unicorn valuation in 2021 — first Indian robotics company to do so.',
    ],
    howItWorksSteps: [
      'QR codes on the warehouse floor mark every cell of the grid.',
      "Camera in the Butler's belly reads each QR code as it drives.",
      'A central fleet manager assigns each robot a shelf to fetch.',
      "Butler ducks under the shelf, lifts it (up to 1,000 kg), and carries it to a picker.",
      'After picking is done, Butler returns the shelf to its original position.',
    ],
    popCulture: "Featured in Flipkart's annual reports, Make-in-India films, and dozens of Indian business news stories. The Butler is one of the most-photographed Indian robots.",
    teamBehind: "Founded in 2011 by IIT-Roorkee/BITS-Pilani alumni Samay Kohli and Akash Gupta. Headquartered in Gurgaon. Major funding from Mithril Capital, Tiger Global, and Project A.",
    description:
      "GreyOrange was founded in 2011 in Gurgaon, India by IIT alumni Samay Kohli and Akash Gupta. The company's flagship product, the Butler, is an autonomous mobile robot (AMR) that picks up entire shelf pods (up to 1,000 kg) and carries them to human pickers in warehouses. Butlers navigate via QR codes on the floor. Flipkart's Pune fulfillment centre uses over 600 Butlers. GreyOrange achieved unicorn status with a valuation over $1 billion in 2021.",
    specs: { height: '40 cm', weight: '~150 kg', speed: '1.7 m/s', payload: '600–1,000 kg shelf pods', battery: '8–10 hours, auto-charging' },
    capabilities: [
      'Autonomous shelf-pod transport',
      'QR-code based floor navigation',
      'Fleet coordination (600+ bots)',
      'Auto-charging at docking stations',
      'Real-time warehouse management integration',
      'Goods-to-person picking workflow',
    ],
    funFacts: [
      "GreyOrange's founders met at BITS Pilani as students before founding the company.",
      "Flipkart's Pune warehouse uses 600+ Butlers.",
      "GreyOrange reached a $1B+ unicorn valuation in 2021.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=4MH7LQyVQyo',
    imageAlt: 'GreyOrange Butler warehouse robot carrying a shelf pod',
    metaTitle: "GreyOrange Butler — India's Top Warehouse Robot | R2BOT",
    metaDescription:
      "GreyOrange Butler AMR profile — Flipkart's 600-robot fleet, $1B valuation, and how India's biggest robotics company works.",
    atlasSlug: 'amr',
    atlasLearnLinks: [
      { label: 'GreyOrange — Atlas', href: '/atlas/concept/greyorange' },
      { label: 'Autonomous Mobile Robot — Atlas', href: '/atlas/concept/autonomous-mobile-robot' },
      { label: 'Warehouse Robotics — Atlas', href: '/atlas/concept/warehouse-robotics' },
    ],
  },
  {
    slug: 'drdo-daksh',
    fameRank: 17,
    name: 'DRDO Daksh',
    emoji: '🛡️',
    maker: 'DRDO',
    country: 'India',
    countryFlag: '🇮🇳',
    year: 2009,
    type: 'military',
    status: 'active',
    oneLiner: "India's bomb-disposal robot — built by DRDO and deployed by the Indian Army.",
    hookLine: "India's robot that walks up to a bomb so a soldier doesn't have to.",
    statChips: [
      { icon: '🇮🇳', text: 'DRDO-built' },
      { icon: '🛡️', text: 'Army-inducted' },
      { icon: '⚛️', text: 'X-ray vision' },
    ],
    inOneSentence: 'Daksh is an Indian Army robot that goes into a possible bomb scene, scans suspicious objects with X-rays, and safely disrupts them.',
    wowFactors: [
      "It saved hundreds of soldier lives across thousands of EOD missions.",
      "Its X-ray scanner can see through car doors and luggage to identify IEDs.",
      "'Daksh' means 'competent' or 'skilled' in Sanskrit.",
    ],
    howItWorksSteps: [
      'Tracked chassis carries 360 kg up stairs and over rough terrain.',
      'A robotic arm with X-ray and camera approaches the suspicious object.',
      'X-ray imaging identifies bomb internals; thermal/optical sensors locate it.',
      'A water-jet disrupter or controlled-detonation tool neutralises the IED.',
      'Operator controls Daksh from up to 1 km away via radio link.',
    ],
    popCulture: 'Featured in DRDO Day demonstrations and Indian defence trade shows like DefExpo.',
    teamBehind: "Built by DRDO's R&D Establishment (Engineers) in Pune. Inducted into the Indian Army from 2009 onwards. Programme leadership across multiple DRDO scientists.",
    description:
      "DRDO Daksh is a battery-operated remotely controlled explosive ordnance disposal (EOD) robot developed by the Defence Research and Development Organisation (DRDO). Daksh was inducted into the Indian Army starting in 2011. Daksh weighs 360 kg, can climb stairs, navigate over uneven terrain, scan vehicles for IEDs using X-ray imaging, and disrupt explosives with a portable jamming system. It has a robotic arm that can grasp and remove suspicious objects.",
    specs: { height: '120 cm', weight: '360 kg', speed: '5 km/h', payload: '20 kg arm payload', battery: '~3 hours operation' },
    capabilities: [
      'Remote bomb-disposal',
      'Stair climbing',
      'X-ray vehicle scanning',
      'Water-jet IED disrupter',
      'RF jamming for triggered devices',
      'Day and night operation',
    ],
    funFacts: [
      "'Daksh' means 'competent' or 'skilled' in Sanskrit.",
      'The Indian Army inducted Daksh into service starting in 2011.',
      "Daksh's X-ray scanner can see through car doors and luggage to identify IEDs.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=PYbsl-vQ0vY',
    imageAlt: 'DRDO Daksh bomb disposal robot with extended arm',
    metaTitle: "DRDO Daksh Robot — India's Indigenous Bomb Disposal EOD | R2BOT",
    metaDescription:
      "DRDO Daksh EOD robot profile — India's Army bomb-disposal robot, X-ray scanning, water-jet disrupter, and indigenous defence robotics.",
    atlasSlug: 'eod-robot',
    atlasLearnLinks: [
      { label: 'DRDO Robotics — Atlas', href: '/atlas/concept/drdo-robots' },
      { label: 'Make in India Robotics — Atlas', href: '/atlas/concept/make-in-india-robotics' },
      { label: 'Search-and-Rescue Robotics — Atlas', href: '/atlas/concept/search-and-rescue-robotics' },
    ],
  },
  {
    slug: 'spot-mini',
    fameRank: 18,
    name: 'SpotMini',
    emoji: '🐩',
    maker: 'Boston Dynamics',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2016,
    type: 'quadruped',
    status: 'retired',
    oneLiner: "Boston Dynamics' smaller indoor quadruped — the original 'house robot' prototype that evolved into Spot.",
    hookLine: 'The viral 2018 video of two SpotMinis cooperating to open a door has 60M+ views.',
    statChips: [
      { icon: '📅', text: '2016 prototype' },
      { icon: '🔋', text: 'All-electric' },
      { icon: '🏠', text: 'Indoor-friendly' },
    ],
    inOneSentence: "SpotMini is the small electric robot dog Boston Dynamics built before Spot — its viral 'two robots open a door' video introduced the world to legged robotics.",
    wowFactors: [
      'Its 2018 door-opening cooperation video has 60M+ views.',
      "Boston Dynamics' first major all-electric (non-hydraulic) robot.",
      "Evolved into the commercial Spot product line.",
    ],
    howItWorksSteps: [
      "Four electric leg motors with batteries — no hydraulics.",
      'Side-mounted cameras + LIDAR build a 3D world model.',
      'A 5-DOF arm on the back opens doors, picks up objects.',
      'Motion-planning runs at high frequency to maintain balance.',
      'Self-righting algorithms recover from falls.',
    ],
    popCulture: 'The "two SpotMinis open a door" video became one of the most-watched robotics videos ever, with appearances in many news segments and corporate keynotes.',
    teamBehind: 'Boston Dynamics, founded by Marc Raibert. SpotMini development overlapped with the broader Spot programme.',
    description:
      "SpotMini was unveiled by Boston Dynamics in 2016 as a smaller, all-electric quadruped designed for indoor use. Unlike the larger hydraulic Spot (BigDog ancestor), SpotMini ran on batteries, weighed only 30 kg, and was quiet enough for home and office environments. Boston Dynamics showed SpotMini opening doors, climbing stairs, navigating around obstacles, and even loading a dishwasher. SpotMini was eventually merged into the production Spot product (launched 2019).",
    specs: { height: '84 cm', weight: '30 kg', speed: '1.6 m/s', payload: '14 kg', battery: 'Lithium-ion, 90 min' },
    capabilities: [
      'All-electric (quiet for indoor use)',
      'Door opening via robot arm',
      'Stair climbing',
      'Object manipulation',
      'Autonomous patrol',
      'Self-righting from falls',
    ],
    funFacts: [
      'The viral 2018 video of two SpotMinis cooperating to open a door has been viewed over 60 million times.',
      'SpotMini was eventually rebranded and absorbed into the commercial Spot product line.',
      "SpotMini was Boston Dynamics' first major electric (non-hydraulic) robot.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=VR_LqlnHnRk',
    imageAlt: 'Boston Dynamics SpotMini smaller quadruped robot walking indoors',
    metaTitle: 'Boston Dynamics SpotMini — Specs, History & Evolution to Spot | R2BOT',
    metaDescription:
      "Boston Dynamics SpotMini profile — the indoor electric quadruped, viral door-opening demo, and how it became the commercial Spot.",
    atlasSlug: 'quadruped-robot',
    atlasLearnLinks: [
      { label: 'Quadruped Robot — Atlas', href: '/atlas/concept/quadruped-robot' },
      { label: 'BLDC Motor — Atlas', href: '/atlas/concept/brushless-motor' },
      { label: 'Behaviour Trees — Atlas', href: '/atlas/concept/behavior-trees' },
    ],
  },
  {
    slug: 'ur5',
    fameRank: 19,
    name: 'Universal Robots UR5',
    emoji: '🤝',
    maker: 'Universal Robots',
    country: 'Denmark',
    countryFlag: '🇩🇰',
    year: 2009,
    type: 'cobot',
    status: 'active',
    oneLiner: "Denmark's collaborative robot arm — the robot that started the cobot revolution.",
    hookLine: "It works beside humans without a safety cage — and started the cobot revolution.",
    statChips: [
      { icon: '🤝', text: 'No cage needed' },
      { icon: '🌍', text: '75,000+ deployed' },
      { icon: '⚖️', text: '5 kg payload' },
    ],
    inOneSentence: 'UR5 is a robotic arm that works safely next to people — no cage, no PhD needed to programme it, just teach it by moving its joints.',
    wowFactors: [
      'Started the entire cobot category — collaborative robot.',
      "Three PhD students in Odense, Denmark, founded Universal Robots in 2005.",
      "Teradyne paid $285 million for UR in 2015 — a bargain in hindsight.",
    ],
    howItWorksSteps: [
      'Joint torque sensors detect any unexpected force (like a human bump).',
      'On contact, UR5 stops in <100 ms — preventing injury.',
      'Drag-and-teach: physically move the arm to record positions.',
      'A pendant lets non-engineers programme it in minutes.',
      "Mounts on tables, walls, ceilings, or AGVs — flexible deployment.",
    ],
    popCulture: 'Featured in Universal Robots\' annual ROI campaigns and dozens of factory documentaries. The "human and cobot collaborate" image is now a cliché in automation marketing.',
    teamBehind: 'Founded in 2005 in Odense, Denmark by three PhD students: Esben Østergaard, Kasper Støy, and Kristian Kassow. Acquired by Teradyne in 2015.',
    description:
      "Universal Robots launched the UR5 in 2009 — the world's first commercially successful collaborative robot (cobot). Unlike traditional industrial robots, the UR5 was designed to work safely alongside humans without cages: its force-sensing motors automatically stop on contact. Lightweight (18.4 kg), with a 5 kg payload and 850 mm reach, the UR5 made robotic automation accessible to small and medium-sized factories. Universal Robots has sold over 75,000 cobots worldwide and was acquired by US firm Teradyne in 2015 for $285 million.",
    specs: { payload: '5 kg', reach: '850 mm', weight: '18.4 kg', dof: '6 axes', speed: '1 m/s' },
    capabilities: [
      'Force-sensing safe stop on contact',
      'Drag-and-teach programming',
      'Pick-and-place, machine tending',
      'Welding, gluing, screwdriving',
      'Quick mount on tables or AGVs',
      'No safety cage required (after risk assessment)',
    ],
    funFacts: [
      'Universal Robots was founded by three PhD students in Odense, Denmark in 2005.',
      'UR cobots are so easy to program that factory workers with no engineering training can deploy them.',
      'Teradyne paid $285 million for Universal Robots in 2015.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=R2zZWxnA9ZM',
    imageAlt: 'Universal Robots UR5 collaborative robot arm next to a human',
    metaTitle: 'Universal Robots UR5 Cobot — Specs, Programming & History | R2BOT',
    metaDescription:
      "Universal Robots UR5 profile — the cobot that started the collaborative-robot revolution. Specs, drag-and-teach programming, and Teradyne acquisition.",
    atlasSlug: 'cobot',
    atlasLearnLinks: [
      { label: 'Cobot — Atlas', href: '/atlas/concept/cobot' },
      { label: 'Collaborative Robot Safety — Atlas', href: '/atlas/concept/collaborative-robot-safety' },
      { label: 'ISO/TS 15066 — Atlas', href: '/atlas/concept/iso-ts-15066' },
    ],
  },
  {
    slug: 'kuka-kr',
    fameRank: 20,
    name: 'KUKA KR AGILUS',
    emoji: '🦾',
    maker: 'KUKA',
    country: 'Germany',
    countryFlag: '🇩🇪',
    year: 1973,
    type: 'industrial',
    status: 'active',
    oneLiner: "Germany's iconic 6-axis industrial robot — backbone of factories from Volkswagen to Tesla.",
    hookLine: 'The orange arm that built your car — KUKA invented the 6-axis robot template.',
    statChips: [
      { icon: '🇩🇪', text: 'Born 1973' },
      { icon: '🚗', text: 'Builds your car' },
      { icon: '🛠️', text: '6 axes' },
    ],
    inOneSentence: 'KUKA is the orange German robot arm you see in every car factory — and the company that invented the 6-axis design every modern arm uses.',
    wowFactors: [
      'KUKA built the first 6-axis industrial robot in 1973 — FAMULUS.',
      'Almost every car you have ever ridden in had bodywork welded by a KUKA or Fanuc robot.',
      "China's Midea Group bought KUKA in 2016 for $4.6 billion.",
    ],
    howItWorksSteps: [
      "Six axes provide reach and orientation in a near-spherical workspace.",
      'High-torque servos in each joint give precision and speed.',
      "Repeatability of ±0.02 mm — better than human hands.",
      'KRC controller plus KUKA.WorkVisual programming environment.',
      'Floor, wall, or ceiling mount — flexible for factory layouts.',
    ],
    popCulture: 'KUKA arms appear in Volvo, Volkswagen, Tesla, BMW, and Mercedes-Benz factory videos. Featured in Ford\'s "F-150" production films and dozens of automation documentaries.',
    teamBehind: 'KUKA was founded in Augsburg, Germany in 1898 (originally as a welding-equipment maker). Built the world\'s first 6-axis robot (FAMULUS) in 1973. Acquired by China\'s Midea Group in 2016.',
    description:
      "KUKA is one of the world's largest industrial-robot makers, founded in Augsburg, Germany in 1898. In 1973, KUKA built FAMULUS — the first robot in the world with six electromechanically driven axes. That breakthrough became the template every modern industrial robot follows. KUKA robots are deployed in automotive assembly lines (Volkswagen, BMW, Tesla, Ford), aerospace, electronics, and increasingly in food and beverage. The company was acquired by China's Midea Group in 2016 for $4.6 billion.",
    specs: { payload: '6–10 kg', reach: '700–1,100 mm', dof: '6 axes', speed: 'Cycle times under 0.5s' },
    capabilities: [
      'High-speed pick-and-place',
      'Sub-0.1 mm repeatability',
      'Welding, painting, assembly',
      'Floor, wall, or ceiling mount',
      'IP67 / IP69K cleanroom variants',
      'KUKA KR C5 controller with safety-rated motion',
    ],
    funFacts: [
      'KUKA built the first 6-axis industrial robot in 1973 — the FAMULUS.',
      'Almost every car you have ever ridden in had bodywork welded by a KUKA or Fanuc robot.',
      "China's Midea Group bought KUKA in 2016 for $4.6 billion.",
    ],
    videoUrl: 'https://www.youtube.com/watch?v=YGcq-jK6ZWk',
    imageAlt: 'KUKA orange industrial robot arm welding on a car assembly line',
    metaTitle: "KUKA Industrial Robot — Germany's Iconic 6-Axis Arm | R2BOT",
    metaDescription:
      "KUKA KR AGILUS industrial robot profile — 6 axes, factory automation history, deployment in Volkswagen and Tesla, and the Midea acquisition.",
    atlasSlug: 'industrial-robot',
    atlasLearnLinks: [
      { label: 'Industrial Robot — Atlas', href: '/atlas/concept/industrial-robot' },
      { label: 'Servo Motor — Atlas', href: '/atlas/concept/servo-motor' },
      { label: 'Forward Kinematics — Atlas', href: '/atlas/concept/forward-kinematics' },
    ],
  },
  // ── Additions for the Hall of Fame v2 ───────────────────────────────
  {
    slug: 'mitra',
    fameRank: 18,
    name: 'Mitra',
    emoji: '🇮🇳',
    maker: 'Invento Robotics',
    country: 'India',
    countryFlag: '🇮🇳',
    year: 2017,
    type: 'service',
    status: 'active',
    oneLiner: "India's first commercial social robot — a Bengaluru-built greeter, conversationalist and queue manager deployed in hospitals, hotels and banks.",
    hookLine: 'The robot that welcomed Ivanka Trump to India.',
    statChips: [
      { icon: '📅', text: 'Born 2017' },
      { icon: '🗣️', text: '5 Indian languages' },
      { icon: '🏥', text: 'In Apollo & Manipal' },
    ],
    inOneSentence:
      'Mitra is a wheeled social robot designed in India for Indian customer-facing contexts — hospitals, hotels, retail floors.',
    wowFactors: [
      'Mitra speaks Hindi, English, Telugu, Tamil and Kannada — and switches between them mid-conversation.',
      'It was the first robot to greet a sitting US presidential family member on Indian soil.',
      'A standard Mitra deployment costs roughly one-third of an equivalent Pepper setup.',
    ],
    howItWorksSteps: [
      'A face camera + microphone array detects the visitor.',
      'Mitra greets in the visitor\'s preferred language using a custom NLP stack.',
      'The wheeled base navigates indoor environments using lidar and pre-mapped floor plans.',
      'The chest tablet displays follow-up info — directions, menus, queue tokens.',
    ],
    popCulture: 'Featured on India Today, Forbes India and the 2017 Global Entrepreneurship Summit livestream.',
    teamBehind: 'Founded by Balaji Viswanathan in Bengaluru in 2016. The team includes former Wipro, IISc and IIT engineers.',
    description: "Invento Robotics' Mitra is India's most-deployed indigenous social robot. Built entirely in Bengaluru, Mitra has shipped roughly 75 commercial units to Apollo Hospitals, Manipal Hospitals, Canara Bank, Singapore Changi Airport, and several Indian hotel chains. It speaks five Indian languages, uses a tablet-based face for emotional expression, and runs on a custom middleware on top of ROS.",
    specs: { height: '152 cm', weight: '50 kg', battery: '4–6 hr' },
    capabilities: ['Multilingual conversation', 'Face recognition', 'Indoor navigation', 'Queue management', 'Telepresence mode'],
    funFacts: [
      'Mitra was named after the Sanskrit word for friend.',
      'The original prototype was 3D-printed in a Bengaluru apartment.',
      'Invento Robotics has bootstrapped to break-even — almost unheard of for a hardware startup.',
    ],
    imageAlt: 'Invento Robotics Mitra social robot in an Indian hospital lobby',
    metaTitle: "Mitra Robot — India's Most-Deployed Social Robot | R2BOT",
    metaDescription: 'Bengaluru-built Mitra by Invento Robotics — multilingual, deployed in Apollo Hospitals, Canara Bank, hotels. India\'s commercial robotics success.',
    atlasSlug: 'social-robot',
    atlasLearnLinks: [
      { label: 'Social Robot — Atlas', href: '/atlas/concept/social-robot' },
      { label: 'Human-Robot Interaction — Atlas', href: '/atlas/concept/human-robot-interaction' },
    ],
  },
  {
    slug: 'amazon-kiva',
    fameRank: 6,
    name: 'Amazon Kiva',
    emoji: '📦',
    maker: 'Amazon Robotics (originally Kiva Systems)',
    country: 'USA',
    countryFlag: '🇺🇸',
    year: 2003,
    type: 'warehouse',
    status: 'active',
    oneLiner: 'The orange warehouse drive units that move shelves to pickers — Amazon Robotics operates over 750,000 of them globally.',
    hookLine: 'If you have an Amazon Prime account, your packages have been moved by Kiva.',
    statChips: [
      { icon: '🤖', text: '750K+ fleet' },
      { icon: '📦', text: '1,360 kg lift' },
      { icon: '⚡', text: '5+ km/h drive' },
    ],
    inOneSentence:
      'Kiva (now Amazon Robotics) is the AMR that inverted warehouse work — bring the shelf to the picker instead of the picker to the shelf.',
    wowFactors: [
      'Amazon acquired Kiva for $775M in 2012 and immediately stopped selling it to anyone else.',
      'A single Kiva drive unit can lift 1,360 kg (about a small car).',
      "Amazon's robot fleet now exceeds the population of Bhutan.",
    ],
    howItWorksSteps: [
      'Each drive unit follows QR-coded markers on the warehouse floor.',
      'A central traffic-controller assigns routes to thousands of robots simultaneously.',
      'The drive unit slides under a portable shelf-pod and lifts it.',
      'It delivers the pod to a stationary human picker, who grabs the item and presses confirm.',
      'The robot returns the pod to its grid slot.',
    ],
    popCulture: 'Featured in countless Amazon Prime documentaries and the 2019 Showtime film "Trafficked."',
    teamBehind: 'Founded by Mick Mountz in 2003 after watching Webvan fail. Bought by Amazon for $775M in 2012.',
    description: "Amazon Robotics — formerly Kiva Systems — is the most economically successful warehouse-robot deployment in history. After Amazon's 2012 acquisition, the platform transformed fulfilment economics worldwide. Today, hundreds of thousands of Kiva drive units operate across Amazon centres in North America, Europe and India.",
    specs: { weight: '136 kg', payload: '1,360 kg', speed: '5+ km/h', battery: '~1 hr' },
    capabilities: ['Autonomous mobile transport', 'Coordinated fleet operation', 'Self-charging', 'Heavy-shelf lifting'],
    funFacts: [
      "Kiva's brand was retired after Amazon's acquisition.",
      'GreyOrange (Gurugram) sells the Indian-built equivalent to Flipkart and DHL.',
      'Amazon now reportedly deploys a new Kiva-class robot every minute, somewhere in the world.',
    ],
    imageAlt: 'Amazon Kiva orange warehouse drive unit lifting a shelving pod',
    metaTitle: 'Amazon Kiva / Amazon Robotics — Warehouse AMR Profile | R2BOT',
    metaDescription: "Amazon Robotics' 750,000+ Kiva drive-unit fleet — the largest warehouse-robot deployment in history. How it works.",
    atlasSlug: 'amr',
    atlasLearnLinks: [
      { label: 'AMR — Atlas', href: '/atlas/concept/amr' },
      { label: 'Warehouse Automation — Atlas', href: '/atlas/concept/warehouse-automation' },
    ],
  },
];

// Final exported list: sorted by fameRank (most famous first).
export const ROBOTS: Robot[] = [...ROBOTS_UNSORTED].sort((a, b) => a.fameRank - b.fameRank);

export const ROBOTS_BY_SLUG = new Map(ROBOTS.map((r) => [r.slug, r]));

export function getRobotBySlug(slug: string): Robot | undefined {
  return ROBOTS_BY_SLUG.get(slug);
}

export function getRelatedRobots(slug: string, limit = 3): Robot[] {
  const robot = getRobotBySlug(slug);
  if (!robot) return [];
  return ROBOTS
    .filter((r) => r.slug !== slug && r.type === robot.type)
    .slice(0, limit);
}

export const ROBOT_TYPE_LABELS: Record<RobotType, string> = {
  humanoid: 'Humanoid',
  industrial: 'Industrial',
  space: 'Space',
  consumer: 'Consumer',
  military: 'Military',
  medical: 'Medical',
  service: 'Service',
  companion: 'Companion',
  educational: 'Educational',
  cobot: 'Cobot',
  quadruped: 'Quadruped',
  warehouse: 'Warehouse',
};
