// scripts/atlas-topics-list.ts
// The 20-bucket taxonomy + every topic to generate for Atlas 1000.
// Imported by scripts/generate-atlas-1000.ts.

export interface Bucket {
  id: string
  name: string
  emoji: string
  color: string
  description: string
  targetCount: number
}

export interface TopicSeed {
  slug: string
  title: string
  bucket: string         // Bucket.id
  difficulty: 1 | 2 | 3 | 4 | 5
  tags?: string[]
  readingPaths?: string[]
}

export const BUCKETS: Bucket[] = [
  { id: 'foundations',       name: 'Foundations',         emoji: '📐', color: '#94a3b8', description: 'Physics, math, electricity — the bedrock', targetCount: 50 },
  { id: 'electronics',       name: 'Electronics',         emoji: '🔌', color: '#fbbf24', description: 'Circuits, components, power for robots', targetCount: 60 },
  { id: 'sensors',           name: 'Sensors',             emoji: '📡', color: '#10b981', description: 'How robots feel the world',                   targetCount: 70 },
  { id: 'actuators',         name: 'Actuators',           emoji: '⚡', color: '#f97316', description: 'Motors, muscles, motion',                    targetCount: 60 },
  { id: 'control-systems',   name: 'Control Systems',     emoji: '🎮', color: '#0ea5e9', description: 'Loops, PID, planning',                       targetCount: 70 },
  { id: 'arms-manipulation', name: 'Arms & Manipulation', emoji: '🦾', color: '#a855f7', description: 'Reaching, grasping, picking',                targetCount: 70 },
  { id: 'mobile-robots',     name: 'Mobile Robots',       emoji: '🚗', color: '#ef4444', description: 'Wheels, legs, locomotion',                   targetCount: 70 },
  { id: 'navigation-slam',   name: 'Navigation & SLAM',   emoji: '🗺️', color: '#06b6d4', description: 'Maps, paths, localization',                  targetCount: 50 },
  { id: 'computer-vision',   name: 'Computer Vision',     emoji: '👁️', color: '#3b82f6', description: 'Pixels to understanding',                    targetCount: 60 },
  { id: 'ai-ml',             name: 'AI & ML',             emoji: '🧠', color: '#7c3aed', description: 'Learning, inference, intelligence',          targetCount: 70 },
  { id: 'programming',       name: 'Programming',         emoji: '💻', color: '#22c55e', description: 'Code, frameworks, simulators',               targetCount: 50 },
  { id: 'hri',               name: 'Human-Robot Interaction', emoji: '🤝', color: '#ec4899', description: 'Working alongside humans',               targetCount: 40 },
  { id: 'robot-types',       name: 'Robot Types',         emoji: '🤖', color: '#f43f5e', description: 'Industrial, mobile, social, medical',        targetCount: 50 },
  { id: 'mechanical-design', name: 'Mechanical Design',   emoji: '⚙️', color: '#64748b', description: 'Bodies, materials, manufacturing',           targetCount: 50 },
  { id: 'applications',      name: 'Applications',        emoji: '🌍', color: '#0891b2', description: 'Robotics solving real problems',             targetCount: 50 },
  { id: 'famous',            name: 'Famous Robots & Companies', emoji: '🏭', color: '#d946ef', description: 'Real names, real teams, real history', targetCount: 40 },
  { id: 'soft-robotics',     name: 'Soft Robotics',       emoji: '🦑', color: '#84cc16', description: 'Compliant, flexible, bio-inspired',          targetCount: 30 },
  { id: 'swarm',             name: 'Swarm Robotics',      emoji: '🐝', color: '#facc15', description: 'Many simple robots, emergent complexity',    targetCount: 25 },
  { id: 'ethics-safety',     name: 'Ethics, Safety & Society', emoji: '⚖️', color: '#fb7185', description: 'Standards, regulations, impact',         targetCount: 35 },
  { id: 'future',            name: 'Future Technologies', emoji: '🔮', color: '#a78bfa', description: 'Where robotics is heading',                  targetCount: 25 },
]

// Helper to keep declarations tight.
function T(slug: string, title: string, bucket: string, difficulty: 1 | 2 | 3 | 4 | 5, tags?: string[]): TopicSeed {
  return { slug, title, bucket, difficulty, tags }
}

// ─── New topics ─────────────────────────────────────────────────────────────

const FOUNDATIONS: TopicSeed[] = [
  T('scalar-vs-vector', 'Scalar vs. Vector', 'foundations', 1, ['math']),
  T('newton-laws-robotics', 'Newton\'s Laws in Robotics', 'foundations', 1, ['physics']),
  T('torque-explained', 'Torque, Explained', 'foundations', 1, ['physics', 'motors']),
  T('friction-in-robots', 'Friction in Robots', 'foundations', 1, ['physics']),
  T('centre-of-gravity', 'Centre of Gravity', 'foundations', 1, ['physics', 'mobile']),
  T('moment-of-inertia', 'Moment of Inertia', 'foundations', 2, ['physics']),
  T('angular-velocity', 'Angular Velocity', 'foundations', 2, ['physics']),
  T('linear-velocity', 'Linear Velocity', 'foundations', 1, ['physics']),
  T('acceleration-robotics', 'Acceleration in Robotics', 'foundations', 1, ['physics']),
  T('energy-in-robots', 'Energy in Robots', 'foundations', 1, ['physics']),
  T('power-consumption', 'Power Consumption', 'foundations', 1, ['power']),
  T('efficiency-machines', 'Efficiency of Machines', 'foundations', 1, ['physics']),
  T('simple-machines', 'Simple Machines', 'foundations', 1, ['physics']),
  T('levers-robotics', 'Levers in Robotics', 'foundations', 1, ['mechanics']),
  T('pulleys-robotics', 'Pulleys in Robotics', 'foundations', 1, ['mechanics']),
  T('gears-explained', 'Gears, Explained', 'foundations', 2, ['mechanics']),
  T('gear-ratio', 'Gear Ratio', 'foundations', 2, ['mechanics']),
  T('mechanical-advantage', 'Mechanical Advantage', 'foundations', 2, ['mechanics']),
  T('springs-robotics', 'Springs in Robotics', 'foundations', 1, ['mechanics']),
  T('damping-explained', 'Damping', 'foundations', 2, ['control']),
  T('resonance-vibration', 'Resonance & Vibration', 'foundations', 3, ['physics']),
  T('material-strength', 'Material Strength', 'foundations', 2, ['materials']),
  T('stress-and-strain', 'Stress & Strain', 'foundations', 2, ['materials']),
  T('elasticity', 'Elasticity', 'foundations', 2, ['materials']),
  T('plasticity', 'Plasticity', 'foundations', 2, ['materials']),
  T('hardness-materials', 'Hardness of Materials', 'foundations', 2, ['materials']),
  T('weight-vs-mass', 'Weight vs. Mass', 'foundations', 1, ['physics']),
  T('friction-coefficient', 'Friction Coefficient', 'foundations', 2, ['physics']),
  T('static-vs-kinetic', 'Static vs. Kinetic Friction', 'foundations', 2, ['physics']),
  T('bernoulli-robotics', 'Bernoulli\'s Principle in Robotics', 'foundations', 3, ['physics', 'fluids']),
  T('fluid-mechanics-robots', 'Fluid Mechanics for Robots', 'foundations', 3, ['physics', 'fluids']),
  T('buoyancy-underwater-robots', 'Buoyancy & Underwater Robots', 'foundations', 2, ['underwater']),
  T('heat-dissipation', 'Heat Dissipation', 'foundations', 2, ['thermal']),
  T('thermal-expansion', 'Thermal Expansion', 'foundations', 2, ['thermal']),
  T('magnetism-basics', 'Magnetism Basics', 'foundations', 1, ['physics']),
  T('electromagnetic-induction', 'Electromagnetic Induction', 'foundations', 3, ['physics']),
  T('capacitance-basics', 'Capacitance Basics', 'foundations', 2, ['electronics']),
  T('resistance-ohms-law', 'Resistance & Ohm\'s Law', 'foundations', 1, ['electronics']),
  T('current-voltage-power', 'Current, Voltage, Power', 'foundations', 1, ['electronics']),
  T('series-parallel-circuits', 'Series & Parallel Circuits', 'foundations', 2, ['electronics']),
  T('kirchhoffs-laws', 'Kirchhoff\'s Laws', 'foundations', 3, ['electronics']),
  T('transistors-basics', 'Transistors Basics', 'foundations', 3, ['electronics']),
  T('diodes-explained', 'Diodes', 'foundations', 2, ['electronics']),
  T('integrated-circuits', 'Integrated Circuits', 'foundations', 2, ['electronics']),
  T('microprocessor-vs-microcontroller', 'Microprocessor vs. Microcontroller', 'foundations', 2, ['computing']),
  T('clock-speed-processors', 'Clock Speed of Processors', 'foundations', 2, ['computing']),
  T('memory-types-robots', 'Memory Types in Robots', 'foundations', 2, ['computing']),
  T('boolean-logic', 'Boolean Logic', 'foundations', 1, ['computing']),
  T('binary-numbers', 'Binary Numbers', 'foundations', 1, ['computing']),
  T('binary-arithmetic', 'Binary Arithmetic', 'foundations', 2, ['computing']),
]

const ELECTRONICS: TopicSeed[] = [
  T('breadboard-basics', 'Breadboard Basics', 'electronics', 1),
  T('soldering-basics', 'Soldering Basics', 'electronics', 1),
  T('pcb-design', 'PCB Design', 'electronics', 3),
  T('voltage-regulators', 'Voltage Regulators', 'electronics', 2),
  T('motor-drivers', 'Motor Drivers', 'electronics', 2),
  T('h-bridge', 'H-Bridge', 'electronics', 2),
  T('pwm-explained', 'PWM, Explained', 'electronics', 2),
  T('adc-dac-conversion', 'ADC & DAC Conversion', 'electronics', 3),
  T('i2c-protocol', 'I²C Protocol', 'electronics', 2),
  T('spi-protocol', 'SPI Protocol', 'electronics', 2),
  T('uart-protocol', 'UART Protocol', 'electronics', 2),
  T('can-bus-robotics', 'CAN Bus in Robotics', 'electronics', 3),
  T('rs485-protocol', 'RS-485 Protocol', 'electronics', 3),
  T('ethernet-robotics', 'Ethernet in Robotics', 'electronics', 2),
  T('usb-in-robots', 'USB in Robots', 'electronics', 1),
  T('power-management-robots', 'Power Management for Robots', 'electronics', 2),
  T('battery-types-robots', 'Battery Types for Robots', 'electronics', 1),
  T('lithium-ion-basics', 'Lithium-Ion Basics', 'electronics', 2),
  T('battery-management-system', 'Battery Management System (BMS)', 'electronics', 3),
  T('charging-circuits', 'Charging Circuits', 'electronics', 2),
  T('supercapacitors-robots', 'Supercapacitors in Robots', 'electronics', 3),
  T('fuel-cells-robots', 'Fuel Cells in Robots', 'electronics', 3),
  T('solar-panels-robots', 'Solar Panels in Robots', 'electronics', 2),
  T('energy-harvesting-robots', 'Energy Harvesting in Robots', 'electronics', 3),
  T('emc-electromagnetic', 'EMC & Electromagnetic Compatibility', 'electronics', 4),
  T('oscilloscopes', 'Oscilloscopes', 'electronics', 2),
  T('multimeter-basics', 'Multimeter Basics', 'electronics', 1),
  T('logic-analyzers', 'Logic Analyzers', 'electronics', 3),
  T('signal-generators', 'Signal Generators', 'electronics', 2),
  T('function-generators', 'Function Generators', 'electronics', 2),
  T('operational-amplifiers', 'Operational Amplifiers (Op-Amps)', 'electronics', 3),
  T('comparators-electronics', 'Comparators', 'electronics', 2),
  T('multiplexers', 'Multiplexers', 'electronics', 2),
  T('demultiplexers', 'Demultiplexers', 'electronics', 2),
  T('shift-registers', 'Shift Registers', 'electronics', 3),
  T('counters-electronics', 'Counters', 'electronics', 2),
  T('flip-flops', 'Flip-Flops', 'electronics', 3),
  T('latches-electronics', 'Latches', 'electronics', 3),
  T('decoders-electronics', 'Decoders', 'electronics', 2),
  T('encoders-electronics', 'Encoders (Combinational)', 'electronics', 2),
  T('dac-basics', 'DAC Basics', 'electronics', 2),
  T('adc-basics', 'ADC Basics', 'electronics', 2),
  T('sample-and-hold', 'Sample and Hold', 'electronics', 3),
  T('filters-electronics', 'Filters (Electronics)', 'electronics', 3),
  T('low-pass-filter', 'Low-Pass Filter', 'electronics', 2),
  T('high-pass-filter', 'High-Pass Filter', 'electronics', 2),
  T('band-pass-filter', 'Band-Pass Filter', 'electronics', 2),
  T('noise-reduction-electronics', 'Noise Reduction', 'electronics', 3),
  T('grounding-electronics', 'Grounding', 'electronics', 2),
  T('esd-protection', 'ESD Protection', 'electronics', 2),
  T('circuit-protection', 'Circuit Protection', 'electronics', 2),
  T('fuses-circuit-breakers', 'Fuses & Circuit Breakers', 'electronics', 1),
  T('relays-explained', 'Relays', 'electronics', 2),
  T('optocouplers', 'Optocouplers', 'electronics', 3),
  T('hall-effect-sensors', 'Hall-Effect Sensors', 'electronics', 2),
  T('current-sensors', 'Current Sensors', 'electronics', 2),
  T('voltage-sensors', 'Voltage Sensors', 'electronics', 1),
  T('temperature-sensors-electronics', 'Temperature Sensors (Electronics)', 'electronics', 1),
  T('proximity-sensors-basics', 'Proximity Sensors (Basics)', 'electronics', 1),
  T('reed-switches', 'Reed Switches', 'electronics', 2),
]

const SENSORS: TopicSeed[] = [
  T('accelerometer-explained', 'Accelerometer, Explained', 'sensors', 2),
  T('gyroscope-explained', 'Gyroscope, Explained', 'sensors', 2),
  T('imu-explained', 'IMU (Inertial Measurement Unit)', 'sensors', 2),
  T('magnetometer-compass', 'Magnetometer (Digital Compass)', 'sensors', 2),
  T('barometer-altitude', 'Barometer for Altitude', 'sensors', 2),
  T('gps-explained', 'GPS, Explained', 'sensors', 2),
  T('rtk-gps', 'RTK-GPS', 'sensors', 3),
  T('differential-gps', 'Differential GPS', 'sensors', 3),
  T('encoder-absolute', 'Absolute Encoder', 'sensors', 2),
  T('encoder-incremental', 'Incremental Encoder', 'sensors', 2),
  T('resolver-sensor', 'Resolver Sensor', 'sensors', 3),
  T('potentiometer-sensor', 'Potentiometer (as Sensor)', 'sensors', 1),
  T('strain-gauge', 'Strain Gauge', 'sensors', 3),
  T('load-cell', 'Load Cell', 'sensors', 2),
  T('force-torque-sensor', 'Force-Torque Sensor', 'sensors', 3),
  T('tactile-sensor', 'Tactile Sensor', 'sensors', 3),
  T('slip-sensor', 'Slip Sensor', 'sensors', 3),
  T('temperature-sensor-types', 'Temperature Sensor Types', 'sensors', 1),
  T('infrared-sensor', 'Infrared (IR) Sensor', 'sensors', 1),
  T('ultrasonic-sensor-deep', 'Ultrasonic Sensor — Deep Dive', 'sensors', 2),
  T('microphone-robots', 'Microphone in Robots', 'sensors', 1),
  T('sound-localization', 'Sound Localization', 'sensors', 3),
  T('whisker-sensor', 'Whisker Sensor', 'sensors', 2),
  T('vision-sensor-types', 'Vision Sensor Types', 'sensors', 2),
  T('event-camera', 'Event Camera', 'sensors', 4),
  T('depth-camera', 'Depth Camera', 'sensors', 2),
  T('structured-light', 'Structured Light', 'sensors', 3),
  T('time-of-flight-sensor', 'Time-of-Flight Sensor', 'sensors', 3),
  T('radar-robotics', 'Radar in Robotics', 'sensors', 3),
  T('sonar-robotics', 'Sonar in Robotics', 'sensors', 2),
  T('lidar-types', 'LIDAR Types', 'sensors', 3),
  T('solid-state-lidar', 'Solid-State LIDAR', 'sensors', 4),
  T('spinning-lidar', 'Spinning LIDAR', 'sensors', 3),
  T('flash-lidar', 'Flash LIDAR', 'sensors', 4),
  T('gas-sensor-robots', 'Gas Sensor in Robots', 'sensors', 2),
  T('chemical-sensor', 'Chemical Sensor', 'sensors', 3),
  T('ph-sensor', 'pH Sensor', 'sensors', 2),
  T('humidity-sensor', 'Humidity Sensor', 'sensors', 1),
  T('light-sensor-lux', 'Light (Lux) Sensor', 'sensors', 1),
  T('color-sensor', 'Color Sensor', 'sensors', 2),
  T('spectroscopy-robots', 'Spectroscopy in Robots', 'sensors', 4),
  T('current-sensor-robot', 'Current Sensor (Robot)', 'sensors', 2),
  T('voltage-sensor-robot', 'Voltage Sensor (Robot)', 'sensors', 1),
  T('contact-sensor', 'Contact Sensor', 'sensors', 1),
  T('limit-switch', 'Limit Switch', 'sensors', 1),
  T('bumper-sensor', 'Bumper Sensor', 'sensors', 1),
  T('cliff-sensor', 'Cliff Sensor', 'sensors', 1),
  T('rain-sensor', 'Rain Sensor', 'sensors', 1),
  T('wind-sensor', 'Wind Sensor', 'sensors', 2),
  T('vibration-sensor', 'Vibration Sensor', 'sensors', 2),
  T('shock-sensor', 'Shock Sensor', 'sensors', 2),
  T('tilt-sensor', 'Tilt Sensor', 'sensors', 1),
  T('capacitive-sensor', 'Capacitive Sensor', 'sensors', 2),
  T('inductive-sensor', 'Inductive Sensor', 'sensors', 2),
  T('magnetic-encoder', 'Magnetic Encoder', 'sensors', 2),
  T('optical-encoder', 'Optical Encoder', 'sensors', 2),
  T('resolver-explained', 'Resolver Explained', 'sensors', 3),
  T('synchro-sensor', 'Synchro Sensor', 'sensors', 4),
  T('lvdt-sensor', 'LVDT Sensor', 'sensors', 3),
  T('rvdt-sensor', 'RVDT Sensor', 'sensors', 3),
  T('sensor-fusion-basics', 'Sensor Fusion (Basics)', 'sensors', 3),
  T('kalman-filter-sensors', 'Kalman Filter for Sensors', 'sensors', 4),
  T('complementary-filter', 'Complementary Filter', 'sensors', 3),
  T('madgwick-filter', 'Madgwick Filter', 'sensors', 4),
]

const ACTUATORS: TopicSeed[] = [
  T('dc-motor-types', 'DC Motor Types', 'actuators', 2),
  T('brushed-vs-brushless', 'Brushed vs. Brushless Motors', 'actuators', 2),
  T('bldc-motor', 'BLDC Motor', 'actuators', 3),
  T('servo-motor-types', 'Servo Motor Types', 'actuators', 2),
  T('servo-motor-pwm', 'Servo Motor PWM', 'actuators', 2),
  T('continuous-rotation-servo', 'Continuous Rotation Servo', 'actuators', 2),
  T('digital-servo', 'Digital Servo', 'actuators', 2),
  T('high-torque-servo', 'High-Torque Servo', 'actuators', 2),
  T('stepper-motor-types', 'Stepper Motor Types', 'actuators', 3),
  T('bipolar-stepper', 'Bipolar Stepper', 'actuators', 3),
  T('unipolar-stepper', 'Unipolar Stepper', 'actuators', 3),
  T('microstepping', 'Microstepping', 'actuators', 3),
  T('linear-actuator', 'Linear Actuator', 'actuators', 2),
  T('ball-screw', 'Ball Screw', 'actuators', 3),
  T('lead-screw', 'Lead Screw', 'actuators', 2),
  T('rack-and-pinion', 'Rack and Pinion', 'actuators', 2),
  T('cable-driven-actuator', 'Cable-Driven Actuator', 'actuators', 3),
  T('pneumatic-actuator', 'Pneumatic Actuator', 'actuators', 3),
  T('hydraulic-actuator', 'Hydraulic Actuator', 'actuators', 3),
  T('shape-memory-alloy', 'Shape Memory Alloy', 'actuators', 4),
  T('piezoelectric-actuator', 'Piezoelectric Actuator', 'actuators', 4),
  T('dielectric-elastomer', 'Dielectric Elastomer Actuator', 'actuators', 4),
  T('electroactive-polymer', 'Electroactive Polymer', 'actuators', 4),
  T('artificial-muscle', 'Artificial Muscle', 'actuators', 4),
  T('voice-coil-actuator', 'Voice Coil Actuator', 'actuators', 3),
  T('solenoid-actuator', 'Solenoid Actuator', 'actuators', 2),
  T('magnetic-actuator', 'Magnetic Actuator', 'actuators', 3),
  T('gear-motor', 'Gear Motor', 'actuators', 2),
  T('worm-gear-motor', 'Worm Gear Motor', 'actuators', 3),
  T('planetary-gearbox', 'Planetary Gearbox', 'actuators', 3),
  T('harmonic-drive', 'Harmonic Drive', 'actuators', 4),
  T('cycloidal-drive', 'Cycloidal Drive', 'actuators', 4),
  T('direct-drive-motor', 'Direct Drive Motor', 'actuators', 3),
  T('torque-motor', 'Torque Motor', 'actuators', 3),
  T('back-emf', 'Back EMF', 'actuators', 3),
  T('motor-constants', 'Motor Constants (Kt, Kv)', 'actuators', 4),
  T('stall-torque', 'Stall Torque', 'actuators', 2),
  T('no-load-speed', 'No-Load Speed', 'actuators', 2),
  T('efficiency-curves-motor', 'Motor Efficiency Curves', 'actuators', 3),
  T('thermal-limits', 'Thermal Limits (Actuators)', 'actuators', 3),
  T('motor-sizing', 'Motor Sizing', 'actuators', 3),
  T('backdrivability', 'Backdrivability', 'actuators', 4),
  T('compliance-actuators', 'Compliance in Actuators', 'actuators', 4),
  T('series-elastic-actuator', 'Series Elastic Actuator', 'actuators', 5),
  T('variable-stiffness-actuator', 'Variable Stiffness Actuator', 'actuators', 5),
  T('soft-actuator-types', 'Soft Actuator Types', 'actuators', 3),
  T('fluidic-soft-actuator', 'Fluidic Soft Actuator', 'actuators', 4),
  T('tendon-driven-actuator', 'Tendon-Driven Actuator', 'actuators', 4),
  T('brake-types-robots', 'Brake Types for Robots', 'actuators', 2),
  T('clutch-types-robots', 'Clutch Types for Robots', 'actuators', 3),
  T('transmission-types', 'Transmission Types', 'actuators', 3),
  T('friction-gear', 'Friction Gear', 'actuators', 3),
  T('belt-drive', 'Belt Drive', 'actuators', 2),
  T('chain-drive', 'Chain Drive', 'actuators', 2),
  T('coupling-types', 'Coupling Types', 'actuators', 2),
  T('flexible-coupling', 'Flexible Coupling', 'actuators', 3),
]

const CONTROL_SYSTEMS: TopicSeed[] = [
  T('open-loop-control', 'Open-Loop Control', 'control-systems', 1),
  T('closed-loop-control', 'Closed-Loop Control', 'control-systems', 2),
  T('feedback-control', 'Feedback Control', 'control-systems', 2),
  T('feedforward-control', 'Feedforward Control', 'control-systems', 3),
  T('pid-tuning-methods', 'PID Tuning Methods', 'control-systems', 3),
  T('ziegler-nichols', 'Ziegler-Nichols', 'control-systems', 4),
  T('auto-tuning-pid', 'Auto-Tuning PID', 'control-systems', 4),
  T('cascade-control', 'Cascade Control', 'control-systems', 3),
  T('ratio-control', 'Ratio Control', 'control-systems', 3),
  T('model-predictive-control', 'Model Predictive Control (MPC)', 'control-systems', 5),
  T('adaptive-control', 'Adaptive Control', 'control-systems', 5),
  T('robust-control', 'Robust Control', 'control-systems', 5),
  T('optimal-control', 'Optimal Control', 'control-systems', 5),
  T('linear-quadratic-regulator', 'Linear Quadratic Regulator (LQR)', 'control-systems', 5),
  T('h-infinity-control', 'H∞ Control', 'control-systems', 5),
  T('sliding-mode-control', 'Sliding Mode Control', 'control-systems', 5),
  T('fuzzy-logic-control', 'Fuzzy Logic Control', 'control-systems', 4),
  T('neural-network-control', 'Neural Network Control', 'control-systems', 5),
  T('reinforcement-learning-control', 'Reinforcement Learning Control', 'control-systems', 5),
  T('state-space-representation', 'State-Space Representation', 'control-systems', 4),
  T('transfer-functions', 'Transfer Functions', 'control-systems', 4),
  T('bode-plot', 'Bode Plot', 'control-systems', 4),
  T('nyquist-plot', 'Nyquist Plot', 'control-systems', 4),
  T('root-locus', 'Root Locus', 'control-systems', 4),
  T('frequency-response', 'Frequency Response', 'control-systems', 4),
  T('stability-analysis', 'Stability Analysis', 'control-systems', 4),
  T('lyapunov-stability', 'Lyapunov Stability', 'control-systems', 5),
  T('phase-margin', 'Phase Margin', 'control-systems', 4),
  T('gain-margin', 'Gain Margin', 'control-systems', 4),
  T('bandwidth-control', 'Bandwidth in Control', 'control-systems', 3),
  T('rise-time', 'Rise Time', 'control-systems', 2),
  T('settling-time', 'Settling Time', 'control-systems', 2),
  T('overshoot', 'Overshoot', 'control-systems', 2),
  T('steady-state-error', 'Steady-State Error', 'control-systems', 3),
  T('integral-windup', 'Integral Windup', 'control-systems', 3),
  T('dead-zone-control', 'Dead Zone (Control)', 'control-systems', 3),
  T('saturating-control', 'Saturating Control', 'control-systems', 3),
  T('anti-windup', 'Anti-Windup', 'control-systems', 4),
  T('smith-predictor', 'Smith Predictor', 'control-systems', 5),
  T('model-reference-adaptive', 'Model-Reference Adaptive Control', 'control-systems', 5),
  T('gain-scheduling', 'Gain Scheduling', 'control-systems', 4),
  T('event-triggered-control', 'Event-Triggered Control', 'control-systems', 5),
  T('discrete-time-control', 'Discrete-Time Control', 'control-systems', 4),
  T('z-transform', 'Z-Transform', 'control-systems', 4),
  T('sampling-theorem', 'Sampling Theorem', 'control-systems', 3),
  T('digital-control-design', 'Digital Control Design', 'control-systems', 4),
  T('real-time-computing', 'Real-Time Computing', 'control-systems', 3),
  T('rtos-basics', 'RTOS Basics', 'control-systems', 3),
  T('interrupt-handling', 'Interrupt Handling', 'control-systems', 3),
  T('control-loop-timing', 'Control Loop Timing', 'control-systems', 3),
  T('control-hardware', 'Control Hardware', 'control-systems', 2),
  T('dsp-for-robots', 'DSP for Robots', 'control-systems', 4),
  T('fpga-control', 'FPGA in Control', 'control-systems', 5),
  T('plc-robotics', 'PLC in Robotics', 'control-systems', 3),
]

const ARMS_MANIPULATION: TopicSeed[] = [
  T('dof-degrees-of-freedom', 'Degrees of Freedom (DOF)', 'arms-manipulation', 2),
  T('serial-manipulator', 'Serial Manipulator', 'arms-manipulation', 2),
  T('parallel-manipulator', 'Parallel Manipulator', 'arms-manipulation', 3),
  T('delta-robot', 'Delta Robot', 'arms-manipulation', 3),
  T('stewart-platform', 'Stewart Platform', 'arms-manipulation', 4),
  T('scara-robot', 'SCARA Robot', 'arms-manipulation', 2),
  T('cartesian-robot', 'Cartesian Robot', 'arms-manipulation', 2),
  T('cylindrical-robot', 'Cylindrical Robot', 'arms-manipulation', 2),
  T('spherical-robot', 'Spherical Robot', 'arms-manipulation', 2),
  T('workspace-analysis', 'Workspace Analysis', 'arms-manipulation', 3),
  T('reachability', 'Reachability', 'arms-manipulation', 3),
  T('dexterity-manipulation', 'Dexterity in Manipulation', 'arms-manipulation', 4),
  T('forward-kinematics-deep', 'Forward Kinematics — Deep Dive', 'arms-manipulation', 4),
  T('inverse-kinematics-deep', 'Inverse Kinematics — Deep Dive', 'arms-manipulation', 5),
  T('jacobian-matrix', 'Jacobian Matrix', 'arms-manipulation', 5),
  T('singularities-robotics', 'Singularities in Robotics', 'arms-manipulation', 5),
  T('redundant-manipulator', 'Redundant Manipulator', 'arms-manipulation', 4),
  T('null-space-control', 'Null Space Control', 'arms-manipulation', 5),
  T('operational-space-control', 'Operational Space Control', 'arms-manipulation', 5),
  T('impedance-control', 'Impedance Control', 'arms-manipulation', 5),
  T('admittance-control', 'Admittance Control', 'arms-manipulation', 5),
  T('hybrid-force-position', 'Hybrid Force/Position Control', 'arms-manipulation', 5),
  T('stiffness-control', 'Stiffness Control', 'arms-manipulation', 4),
  T('joint-torque-control', 'Joint Torque Control', 'arms-manipulation', 4),
  T('gravity-compensation', 'Gravity Compensation', 'arms-manipulation', 4),
  T('friction-compensation', 'Friction Compensation', 'arms-manipulation', 4),
  T('trajectory-planning-arms', 'Trajectory Planning for Arms', 'arms-manipulation', 4),
  T('minimum-jerk-trajectory', 'Minimum-Jerk Trajectory', 'arms-manipulation', 4),
  T('polynomial-trajectory', 'Polynomial Trajectory', 'arms-manipulation', 3),
  T('via-points', 'Via Points', 'arms-manipulation', 3),
  T('cartesian-path-planning', 'Cartesian Path Planning', 'arms-manipulation', 4),
  T('tool-center-point', 'Tool Center Point (TCP)', 'arms-manipulation', 2),
  T('end-effector-types', 'End-Effector Types', 'arms-manipulation', 2),
  T('gripper-types', 'Gripper Types', 'arms-manipulation', 2),
  T('parallel-gripper', 'Parallel Gripper', 'arms-manipulation', 2),
  T('underactuated-gripper', 'Underactuated Gripper', 'arms-manipulation', 4),
  T('soft-gripper', 'Soft Gripper', 'arms-manipulation', 3),
  T('magnetic-gripper', 'Magnetic Gripper', 'arms-manipulation', 2),
  T('vacuum-gripper', 'Vacuum Gripper', 'arms-manipulation', 2),
  T('bernoulli-gripper', 'Bernoulli Gripper', 'arms-manipulation', 4),
  T('electrostatic-gripper', 'Electrostatic Gripper', 'arms-manipulation', 4),
  T('suction-cup-physics', 'Suction Cup Physics', 'arms-manipulation', 3),
  T('pinch-grasp', 'Pinch Grasp', 'arms-manipulation', 2),
  T('power-grasp', 'Power Grasp', 'arms-manipulation', 2),
  T('precision-grasp', 'Precision Grasp', 'arms-manipulation', 3),
  T('in-hand-manipulation', 'In-Hand Manipulation', 'arms-manipulation', 5),
  T('regrasping', 'Regrasping', 'arms-manipulation', 4),
  T('compliant-manipulation', 'Compliant Manipulation', 'arms-manipulation', 4),
  T('peg-in-hole', 'Peg-in-Hole', 'arms-manipulation', 4),
  T('assembly-robotics', 'Assembly Robotics', 'arms-manipulation', 3),
  T('bin-picking', 'Bin Picking', 'arms-manipulation', 4),
  T('deformable-object-manipulation', 'Deformable Object Manipulation', 'arms-manipulation', 5),
  T('cloth-manipulation', 'Cloth Manipulation', 'arms-manipulation', 5),
  T('cable-manipulation', 'Cable Manipulation', 'arms-manipulation', 4),
  T('dual-arm-robot', 'Dual-Arm Robot', 'arms-manipulation', 4),
  T('collaborative-robot-cobot', 'Collaborative Robot (Cobot)', 'arms-manipulation', 3),
]

const MOBILE_ROBOTS: TopicSeed[] = [
  T('differential-drive-deep', 'Differential Drive — Deep Dive', 'mobile-robots', 3),
  T('ackermann-steering-deep', 'Ackermann Steering — Deep Dive', 'mobile-robots', 3),
  T('mecanum-wheel-deep', 'Mecanum Wheel — Deep Dive', 'mobile-robots', 3),
  T('omni-wheel-deep', 'Omni Wheel — Deep Dive', 'mobile-robots', 3),
  T('skid-steer-robot', 'Skid-Steer Robot', 'mobile-robots', 3),
  T('legged-locomotion', 'Legged Locomotion', 'mobile-robots', 4),
  T('biped-walking', 'Biped Walking', 'mobile-robots', 5),
  T('quadruped-gait', 'Quadruped Gait', 'mobile-robots', 4),
  T('hexapod-locomotion', 'Hexapod Locomotion', 'mobile-robots', 4),
  T('gait-planning', 'Gait Planning', 'mobile-robots', 5),
  T('balance-control', 'Balance Control', 'mobile-robots', 4),
  T('zmp-zero-moment-point', 'Zero Moment Point (ZMP)', 'mobile-robots', 5),
  T('capturability', 'Capturability', 'mobile-robots', 5),
  T('whole-body-control', 'Whole-Body Control', 'mobile-robots', 5),
  T('passive-dynamic-walking', 'Passive Dynamic Walking', 'mobile-robots', 5),
  T('raibert-controller', 'Raibert Controller', 'mobile-robots', 5),
  T('boston-dynamics-methods', 'Boston Dynamics Methods', 'mobile-robots', 4),
  T('wheeled-legged-robot', 'Wheeled-Legged Robot', 'mobile-robots', 4),
  T('jumping-robots', 'Jumping Robots', 'mobile-robots', 4),
  T('climbing-robots', 'Climbing Robots', 'mobile-robots', 4),
  T('wall-climbing-mechanisms', 'Wall-Climbing Mechanisms', 'mobile-robots', 4),
  T('underwater-propulsion', 'Underwater Propulsion', 'mobile-robots', 3),
  T('thruster-types', 'Thruster Types', 'mobile-robots', 3),
  T('buoyancy-control', 'Buoyancy Control', 'mobile-robots', 3),
  T('uuv-design', 'UUV Design', 'mobile-robots', 4),
  T('surface-robot', 'Surface (Marine) Robot', 'mobile-robots', 3),
  T('amphibious-robot', 'Amphibious Robot', 'mobile-robots', 4),
  T('pipe-inspection-robot', 'Pipe Inspection Robot', 'mobile-robots', 3),
  T('disaster-response-robot', 'Disaster Response Robot', 'mobile-robots', 3),
  T('search-rescue-robot', 'Search & Rescue Robot', 'mobile-robots', 3),
  T('agricultural-robot-locomotion', 'Agricultural Robot Locomotion', 'mobile-robots', 3),
  T('ground-clearance', 'Ground Clearance', 'mobile-robots', 2),
  T('terrain-classification', 'Terrain Classification', 'mobile-robots', 4),
  T('terrain-adaptation', 'Terrain Adaptation', 'mobile-robots', 4),
  T('suspension-systems-robots', 'Suspension Systems (Robots)', 'mobile-robots', 3),
  T('shock-absorption-mobile', 'Shock Absorption (Mobile)', 'mobile-robots', 3),
  T('traction-control', 'Traction Control', 'mobile-robots', 3),
  T('slip-estimation', 'Slip Estimation', 'mobile-robots', 4),
  T('odometry-deep', 'Odometry — Deep Dive', 'mobile-robots', 3),
  T('dead-reckoning', 'Dead Reckoning', 'mobile-robots', 3),
  T('imu-odometry', 'IMU Odometry', 'mobile-robots', 4),
  T('visual-odometry', 'Visual Odometry', 'mobile-robots', 4),
  T('lidar-odometry', 'LIDAR Odometry', 'mobile-robots', 4),
  T('wheel-odometry-error', 'Wheel Odometry Error', 'mobile-robots', 3),
  T('mobile-base-design', 'Mobile Base Design', 'mobile-robots', 3),
  T('center-of-mass-mobile', 'Center of Mass (Mobile)', 'mobile-robots', 3),
  T('tipping-prevention', 'Tipping Prevention', 'mobile-robots', 3),
  T('mobile-robot-sizing', 'Mobile Robot Sizing', 'mobile-robots', 3),
  T('battery-life-optimization', 'Battery Life Optimization', 'mobile-robots', 3),
  T('charging-strategies', 'Charging Strategies', 'mobile-robots', 2),
  T('wireless-charging-robots', 'Wireless Charging for Robots', 'mobile-robots', 3),
]

const NAVIGATION_SLAM: TopicSeed[] = [
  T('slam-explained', 'SLAM, Explained', 'navigation-slam', 4),
  T('slam-types', 'SLAM Types', 'navigation-slam', 4),
  T('feature-based-slam', 'Feature-Based SLAM', 'navigation-slam', 4),
  T('direct-slam', 'Direct SLAM', 'navigation-slam', 5),
  T('dense-slam', 'Dense SLAM', 'navigation-slam', 5),
  T('graph-slam', 'Graph SLAM', 'navigation-slam', 5),
  T('pose-graph-optimization', 'Pose Graph Optimization', 'navigation-slam', 5),
  T('loop-closure', 'Loop Closure', 'navigation-slam', 4),
  T('map-representation', 'Map Representation', 'navigation-slam', 3),
  T('occupancy-grid', 'Occupancy Grid', 'navigation-slam', 3),
  T('point-cloud-map', 'Point Cloud Map', 'navigation-slam', 3),
  T('topological-map', 'Topological Map', 'navigation-slam', 3),
  T('semantic-map', 'Semantic Map', 'navigation-slam', 4),
  T('3d-map', '3D Map', 'navigation-slam', 3),
  T('voxel-map', 'Voxel Map', 'navigation-slam', 4),
  T('octree-map', 'Octree Map', 'navigation-slam', 4),
  T('lidar-slam', 'LIDAR SLAM', 'navigation-slam', 4),
  T('visual-slam', 'Visual SLAM (vSLAM)', 'navigation-slam', 4),
  T('mono-slam', 'Mono SLAM', 'navigation-slam', 5),
  T('stereo-slam', 'Stereo SLAM', 'navigation-slam', 4),
  T('rgbd-slam', 'RGB-D SLAM', 'navigation-slam', 4),
  T('orb-slam', 'ORB-SLAM', 'navigation-slam', 5),
  T('cartographer', 'Cartographer', 'navigation-slam', 4),
  T('gmapping-explained', 'GMapping, Explained', 'navigation-slam', 4),
  T('hector-slam', 'Hector SLAM', 'navigation-slam', 4),
  T('rtab-map', 'RTAB-Map', 'navigation-slam', 4),
  T('global-localization', 'Global Localization', 'navigation-slam', 4),
  T('localization-explained', 'Localization, Explained', 'navigation-slam', 3),
  T('particle-filter', 'Particle Filter', 'navigation-slam', 4),
  T('monte-carlo-localization', 'Monte Carlo Localization', 'navigation-slam', 4),
  T('amcl-explained', 'AMCL, Explained', 'navigation-slam', 4),
  T('ekf-localization', 'EKF Localization', 'navigation-slam', 4),
  T('ukf-localization', 'UKF Localization', 'navigation-slam', 5),
  T('pose-estimation', 'Pose Estimation', 'navigation-slam', 3),
  T('place-recognition', 'Place Recognition', 'navigation-slam', 4),
  T('relocalization', 'Relocalization', 'navigation-slam', 4),
  T('kidnapped-robot', 'The Kidnapped Robot Problem', 'navigation-slam', 4),
  T('path-planning-explained', 'Path Planning, Explained', 'navigation-slam', 3),
  T('dijkstra-algorithm', 'Dijkstra\'s Algorithm', 'navigation-slam', 3),
  T('a-star-algorithm', 'A* Algorithm', 'navigation-slam', 3),
  T('d-star-algorithm', 'D* Algorithm', 'navigation-slam', 4),
  T('rrt-explained', 'RRT, Explained', 'navigation-slam', 4),
  T('rrt-star', 'RRT*', 'navigation-slam', 5),
  T('prm-probabilistic-roadmap', 'Probabilistic Roadmap (PRM)', 'navigation-slam', 4),
  T('potential-field', 'Potential Field', 'navigation-slam', 3),
  T('dynamic-window-approach', 'Dynamic Window Approach (DWA)', 'navigation-slam', 4),
  T('teb-planner', 'TEB Local Planner', 'navigation-slam', 4),
  T('global-vs-local-planner', 'Global vs. Local Planner', 'navigation-slam', 3),
  T('costmap-explained', 'Costmap, Explained', 'navigation-slam', 3),
  T('inflation-layer', 'Inflation Layer', 'navigation-slam', 3),
  T('obstacle-avoidance-deep', 'Obstacle Avoidance — Deep Dive', 'navigation-slam', 3),
  T('dynamic-obstacles', 'Dynamic Obstacles', 'navigation-slam', 4),
  T('velocity-obstacle', 'Velocity Obstacle', 'navigation-slam', 5),
]

const COMPUTER_VISION: TopicSeed[] = [
  T('image-basics', 'Image Basics', 'computer-vision', 1),
  T('pixel-explained', 'Pixel, Explained', 'computer-vision', 1),
  T('color-spaces', 'Color Spaces', 'computer-vision', 2),
  T('rgb-hsv-conversion', 'RGB-HSV Conversion', 'computer-vision', 2),
  T('grayscale-image', 'Grayscale Image', 'computer-vision', 1),
  T('image-filtering', 'Image Filtering', 'computer-vision', 2),
  T('convolution-explained', 'Convolution, Explained', 'computer-vision', 3),
  T('gaussian-blur', 'Gaussian Blur', 'computer-vision', 2),
  T('sobel-edge', 'Sobel Edge Detection', 'computer-vision', 3),
  T('canny-edge', 'Canny Edge Detection', 'computer-vision', 3),
  T('hough-transform', 'Hough Transform', 'computer-vision', 4),
  T('feature-detection', 'Feature Detection', 'computer-vision', 3),
  T('sift-explained', 'SIFT, Explained', 'computer-vision', 4),
  T('surf-explained', 'SURF, Explained', 'computer-vision', 4),
  T('orb-features', 'ORB Features', 'computer-vision', 4),
  T('feature-matching', 'Feature Matching', 'computer-vision', 3),
  T('homography', 'Homography', 'computer-vision', 4),
  T('stereo-vision', 'Stereo Vision', 'computer-vision', 3),
  T('disparity-map', 'Disparity Map', 'computer-vision', 4),
  T('depth-from-stereo', 'Depth from Stereo', 'computer-vision', 4),
  T('epipolar-geometry', 'Epipolar Geometry', 'computer-vision', 5),
  T('camera-calibration', 'Camera Calibration', 'computer-vision', 3),
  T('lens-distortion', 'Lens Distortion', 'computer-vision', 3),
  T('camera-matrix', 'Camera Matrix', 'computer-vision', 4),
  T('projection-matrix', 'Projection Matrix', 'computer-vision', 4),
  T('perspective-transform', 'Perspective Transform', 'computer-vision', 4),
  T('image-segmentation', 'Image Segmentation', 'computer-vision', 3),
  T('thresholding', 'Thresholding', 'computer-vision', 2),
  T('watershed-algorithm', 'Watershed Algorithm', 'computer-vision', 4),
  T('contour-detection', 'Contour Detection', 'computer-vision', 3),
  T('connected-components', 'Connected Components', 'computer-vision', 3),
  T('optical-flow', 'Optical Flow', 'computer-vision', 4),
  T('lucas-kanade', 'Lucas-Kanade', 'computer-vision', 4),
  T('horn-schunck', 'Horn-Schunck', 'computer-vision', 5),
  T('background-subtraction', 'Background Subtraction', 'computer-vision', 3),
  T('object-tracking', 'Object Tracking', 'computer-vision', 3),
  T('kalman-tracking', 'Kalman Tracking', 'computer-vision', 4),
  T('correlation-filter', 'Correlation Filter', 'computer-vision', 4),
  T('object-detection-explained', 'Object Detection, Explained', 'computer-vision', 3),
  T('sliding-window', 'Sliding Window', 'computer-vision', 3),
  T('selective-search', 'Selective Search', 'computer-vision', 4),
  T('region-proposal', 'Region Proposal', 'computer-vision', 4),
  T('bounding-box-regression', 'Bounding Box Regression', 'computer-vision', 4),
  T('non-max-suppression', 'Non-Max Suppression', 'computer-vision', 4),
  T('anchor-boxes', 'Anchor Boxes', 'computer-vision', 4),
  T('yolo-explained', 'YOLO, Explained', 'computer-vision', 4),
  T('rcnn-explained', 'R-CNN, Explained', 'computer-vision', 4),
  T('ssd-explained', 'SSD, Explained', 'computer-vision', 4),
  T('image-classification-explained', 'Image Classification, Explained', 'computer-vision', 3),
  T('transfer-learning-vision', 'Transfer Learning (Vision)', 'computer-vision', 3),
  T('semantic-segmentation', 'Semantic Segmentation', 'computer-vision', 4),
  T('instance-segmentation', 'Instance Segmentation', 'computer-vision', 5),
  T('panoptic-segmentation', 'Panoptic Segmentation', 'computer-vision', 5),
  T('depth-estimation', 'Depth Estimation', 'computer-vision', 4),
  T('monocular-depth', 'Monocular Depth', 'computer-vision', 4),
  T('point-cloud-processing', 'Point Cloud Processing', 'computer-vision', 4),
  T('icp-algorithm', 'ICP Algorithm', 'computer-vision', 4),
  T('normal-estimation', 'Normal Estimation', 'computer-vision', 4),
  T('surface-reconstruction', 'Surface Reconstruction', 'computer-vision', 5),
  T('3d-object-detection', '3D Object Detection', 'computer-vision', 5),
  T('pose-estimation-vision', 'Pose Estimation (Vision)', 'computer-vision', 4),
]

const AI_ML: TopicSeed[] = [
  T('ai-vs-ml-vs-dl', 'AI vs. ML vs. DL', 'ai-ml', 1),
  T('supervised-learning', 'Supervised Learning', 'ai-ml', 2),
  T('unsupervised-learning', 'Unsupervised Learning', 'ai-ml', 2),
  T('reinforcement-learning-deep', 'Reinforcement Learning — Deep Dive', 'ai-ml', 4),
  T('regression-explained', 'Regression, Explained', 'ai-ml', 2),
  T('classification-explained', 'Classification, Explained', 'ai-ml', 2),
  T('clustering-explained', 'Clustering, Explained', 'ai-ml', 3),
  T('neural-network-deep', 'Neural Network — Deep Dive', 'ai-ml', 3),
  T('activation-functions', 'Activation Functions', 'ai-ml', 3),
  T('backpropagation-explained', 'Backpropagation, Explained', 'ai-ml', 4),
  T('gradient-descent', 'Gradient Descent', 'ai-ml', 3),
  T('stochastic-gradient-descent', 'Stochastic Gradient Descent (SGD)', 'ai-ml', 3),
  T('adam-optimizer', 'Adam Optimizer', 'ai-ml', 4),
  T('loss-functions', 'Loss Functions', 'ai-ml', 3),
  T('overfitting-underfitting', 'Overfitting & Underfitting', 'ai-ml', 3),
  T('regularization', 'Regularization', 'ai-ml', 3),
  T('dropout-explained', 'Dropout, Explained', 'ai-ml', 3),
  T('batch-normalization', 'Batch Normalization', 'ai-ml', 4),
  T('cnn-explained', 'CNN, Explained', 'ai-ml', 3),
  T('rnn-explained', 'RNN, Explained', 'ai-ml', 3),
  T('lstm-explained', 'LSTM, Explained', 'ai-ml', 4),
  T('transformer-explained', 'Transformer, Explained', 'ai-ml', 4),
  T('attention-mechanism', 'Attention Mechanism', 'ai-ml', 4),
  T('bert-explained', 'BERT, Explained', 'ai-ml', 4),
  T('gpt-explained', 'GPT, Explained', 'ai-ml', 4),
  T('diffusion-models', 'Diffusion Models', 'ai-ml', 4),
  T('generative-adversarial', 'Generative Adversarial Networks (GANs)', 'ai-ml', 4),
  T('variational-autoencoder', 'Variational Autoencoder (VAE)', 'ai-ml', 4),
  T('graph-neural-network', 'Graph Neural Network', 'ai-ml', 4),
  T('geometric-deep-learning', 'Geometric Deep Learning', 'ai-ml', 5),
  T('model-based-rl', 'Model-Based RL', 'ai-ml', 5),
  T('model-free-rl', 'Model-Free RL', 'ai-ml', 5),
  T('q-learning', 'Q-Learning', 'ai-ml', 4),
  T('dqn-explained', 'DQN, Explained', 'ai-ml', 5),
  T('policy-gradient', 'Policy Gradient', 'ai-ml', 5),
  T('proximal-policy-optimization', 'Proximal Policy Optimization (PPO)', 'ai-ml', 5),
  T('actor-critic', 'Actor-Critic', 'ai-ml', 5),
  T('multi-agent-rl', 'Multi-Agent RL', 'ai-ml', 5),
  T('imitation-learning', 'Imitation Learning', 'ai-ml', 4),
  T('learning-from-demonstration', 'Learning from Demonstration', 'ai-ml', 4),
  T('inverse-rl', 'Inverse Reinforcement Learning', 'ai-ml', 5),
  T('sim-to-real', 'Sim-to-Real', 'ai-ml', 4),
  T('domain-randomization', 'Domain Randomization', 'ai-ml', 4),
  T('meta-learning', 'Meta-Learning', 'ai-ml', 5),
  T('few-shot-learning', 'Few-Shot Learning', 'ai-ml', 5),
  T('continual-learning', 'Continual Learning', 'ai-ml', 5),
  T('federated-learning', 'Federated Learning', 'ai-ml', 5),
  T('edge-ai', 'Edge AI', 'ai-ml', 3),
  T('tinyml', 'TinyML', 'ai-ml', 4),
  T('model-quantization', 'Model Quantization', 'ai-ml', 4),
  T('model-pruning', 'Model Pruning', 'ai-ml', 4),
  T('knowledge-distillation', 'Knowledge Distillation', 'ai-ml', 5),
  T('neural-architecture-search', 'Neural Architecture Search', 'ai-ml', 5),
  T('hyperparameter-tuning', 'Hyperparameter Tuning', 'ai-ml', 3),
  T('cross-validation', 'Cross-Validation', 'ai-ml', 3),
  T('confusion-matrix', 'Confusion Matrix', 'ai-ml', 2),
  T('precision-recall', 'Precision & Recall', 'ai-ml', 3),
  T('f1-score', 'F1 Score', 'ai-ml', 3),
  T('roc-curve', 'ROC Curve', 'ai-ml', 3),
  T('data-augmentation', 'Data Augmentation', 'ai-ml', 3),
  T('synthetic-data', 'Synthetic Data', 'ai-ml', 3),
  T('roboflow', 'Roboflow', 'ai-ml', 2),
  T('annotation-tools', 'Annotation Tools', 'ai-ml', 2),
  T('active-learning', 'Active Learning', 'ai-ml', 4),
]

const PROGRAMMING: TopicSeed[] = [
  T('python-for-robotics', 'Python for Robotics', 'programming', 1),
  T('cpp-for-robotics', 'C++ for Robotics', 'programming', 3),
  T('ros2-explained', 'ROS2, Explained', 'programming', 3),
  T('ros2-nodes', 'ROS2 Nodes', 'programming', 3),
  T('ros2-topics', 'ROS2 Topics', 'programming', 3),
  T('ros2-services', 'ROS2 Services', 'programming', 3),
  T('ros2-actions', 'ROS2 Actions', 'programming', 4),
  T('ros2-parameters', 'ROS2 Parameters', 'programming', 3),
  T('ros2-launch', 'ROS2 Launch', 'programming', 3),
  T('ros2-lifecycle', 'ROS2 Lifecycle', 'programming', 4),
  T('ros2-bags', 'ROS2 Bags', 'programming', 3),
  T('ros2-tf2', 'ROS2 TF2', 'programming', 4),
  T('ros2-urdf', 'ROS2 URDF', 'programming', 3),
  T('ros2-moveit2', 'ROS2 MoveIt 2', 'programming', 4),
  T('ros2-nav2', 'ROS2 Nav2', 'programming', 4),
  T('ros2-gazebo', 'ROS2 + Gazebo', 'programming', 4),
  T('gazebo-simulation', 'Gazebo Simulation', 'programming', 3),
  T('ignition-gazebo', 'Ignition Gazebo', 'programming', 3),
  T('pybullet-simulation', 'PyBullet Simulation', 'programming', 3),
  T('mujoco-simulation', 'MuJoCo Simulation', 'programming', 4),
  T('webots-explained', 'Webots, Explained', 'programming', 3),
  T('v-rep-coppeliasim', 'V-REP / CoppeliaSim', 'programming', 3),
  T('arduino-explained', 'Arduino, Explained', 'programming', 1),
  T('raspberry-pi-robotics', 'Raspberry Pi for Robotics', 'programming', 2),
  T('nvidia-jetson', 'NVIDIA Jetson', 'programming', 3),
  T('esp32-robotics', 'ESP32 in Robotics', 'programming', 2),
  T('stm32-robotics', 'STM32 in Robotics', 'programming', 3),
  T('micro-ros', 'micro-ROS', 'programming', 4),
  T('microros-explained', 'micro-ROS, Explained', 'programming', 4),
  T('docker-robotics', 'Docker for Robotics', 'programming', 3),
  T('git-robotics-workflow', 'Git Workflow for Robotics', 'programming', 2),
  T('ci-cd-robotics', 'CI/CD for Robotics', 'programming', 4),
  T('unit-testing-robotics', 'Unit Testing for Robotics', 'programming', 3),
  T('simulation-testing', 'Simulation Testing', 'programming', 3),
  T('hardware-in-the-loop', 'Hardware-in-the-Loop (HIL)', 'programming', 4),
  T('software-in-the-loop', 'Software-in-the-Loop (SIL)', 'programming', 4),
  T('real-time-os-rtos', 'Real-Time OS (RTOS)', 'programming', 4),
  T('freertos-robotics', 'FreeRTOS for Robotics', 'programming', 3),
  T('linux-robotics', 'Linux for Robotics', 'programming', 2),
  T('embedded-linux', 'Embedded Linux', 'programming', 3),
  T('yocto-project', 'Yocto Project', 'programming', 4),
  T('middleware-robotics', 'Middleware for Robotics', 'programming', 3),
  T('communication-protocols', 'Communication Protocols', 'programming', 2),
  T('grpc-robotics', 'gRPC in Robotics', 'programming', 3),
  T('websockets-robots', 'WebSockets in Robots', 'programming', 3),
  T('mqtt-robotics', 'MQTT in Robotics', 'programming', 2),
  T('rest-api-robots', 'REST APIs for Robots', 'programming', 2),
  T('graphql-robots', 'GraphQL for Robots', 'programming', 3),
  T('database-robots', 'Databases in Robotics', 'programming', 2),
  T('logging-robotics', 'Logging in Robotics', 'programming', 2),
]

const HRI: TopicSeed[] = [
  T('hri-explained', 'HRI, Explained', 'hri', 2),
  T('social-robotics', 'Social Robotics', 'hri', 2),
  T('robot-companions', 'Robot Companions', 'hri', 2),
  T('emotional-robots', 'Emotional Robots', 'hri', 3),
  T('robot-empathy', 'Robot Empathy', 'hri', 3),
  T('robot-personality', 'Robot Personality', 'hri', 3),
  T('robot-expression', 'Robot Expression', 'hri', 3),
  T('robot-voice', 'Robot Voice', 'hri', 2),
  T('text-to-speech-robots', 'Text-to-Speech for Robots', 'hri', 2),
  T('speech-recognition-robots', 'Speech Recognition for Robots', 'hri', 3),
  T('natural-language-processing-robots', 'NLP for Robots', 'hri', 3),
  T('conversational-ai-robots', 'Conversational AI for Robots', 'hri', 3),
  T('chatbot-vs-robot', 'Chatbot vs. Robot', 'hri', 1),
  T('gesture-recognition', 'Gesture Recognition', 'hri', 3),
  T('body-language-robots', 'Body Language for Robots', 'hri', 3),
  T('eye-contact-robots', 'Eye Contact in Robots', 'hri', 3),
  T('proxemics-robots', 'Proxemics for Robots', 'hri', 3),
  T('personal-space-robots', 'Personal Space and Robots', 'hri', 2),
  T('robot-legibility', 'Robot Legibility', 'hri', 4),
  T('robot-predictability', 'Robot Predictability', 'hri', 3),
  T('trust-in-robots', 'Trust in Robots', 'hri', 3),
  T('robot-transparency', 'Robot Transparency', 'hri', 3),
  T('explainable-ai-robots', 'Explainable AI in Robots', 'hri', 4),
  T('shared-autonomy', 'Shared Autonomy', 'hri', 4),
  T('human-on-the-loop', 'Human-on-the-Loop', 'hri', 3),
  T('teleoperation-explained', 'Teleoperation, Explained', 'hri', 3),
  T('haptic-feedback', 'Haptic Feedback', 'hri', 3),
  T('force-feedback', 'Force Feedback', 'hri', 3),
  T('exoskeleton-control', 'Exoskeleton Control', 'hri', 4),
  T('brain-computer-interface', 'Brain-Computer Interface', 'hri', 5),
  T('eeg-robotics', 'EEG in Robotics', 'hri', 5),
  T('emg-control', 'EMG Control', 'hri', 4),
  T('eye-tracking-robots', 'Eye Tracking for Robots', 'hri', 3),
  T('augmented-reality-robots', 'AR for Robots', 'hri', 3),
  T('mixed-reality-robots', 'Mixed Reality for Robots', 'hri', 4),
  T('robot-teaching-by-demonstration', 'Robot Teaching by Demonstration', 'hri', 4),
  T('kinesthetic-teaching', 'Kinesthetic Teaching', 'hri', 4),
  T('lfd-learning-from-demonstration', 'Learning from Demonstration (LfD)', 'hri', 4),
  T('cobots-safety', 'Cobots Safety', 'hri', 3),
  T('iso-10218', 'ISO 10218', 'hri', 4),
]

const ROBOT_TYPES: TopicSeed[] = [
  T('industrial-robot-types', 'Industrial Robot Types', 'robot-types', 2),
  T('articulated-robot', 'Articulated Robot', 'robot-types', 2),
  T('scara-type', 'SCARA Type', 'robot-types', 2),
  T('delta-type', 'Delta Type', 'robot-types', 3),
  T('gantry-robot', 'Gantry Robot', 'robot-types', 2),
  T('parallel-kinematic-machine', 'Parallel Kinematic Machine', 'robot-types', 4),
  T('mobile-robot-types', 'Mobile Robot Types', 'robot-types', 2),
  T('autonomous-mobile-robot', 'Autonomous Mobile Robot', 'robot-types', 3),
  T('guided-vehicle-agv', 'AGV (Automated Guided Vehicle)', 'robot-types', 2),
  T('autonomous-mobile-robot-amr', 'AMR (Autonomous Mobile Robot)', 'robot-types', 3),
  T('agv-vs-amr', 'AGV vs. AMR', 'robot-types', 2),
  T('warehouse-robot', 'Warehouse Robot', 'robot-types', 2),
  T('delivery-robot', 'Delivery Robot', 'robot-types', 2),
  T('last-mile-robot', 'Last-Mile Robot', 'robot-types', 2),
  T('service-robot', 'Service Robot', 'robot-types', 2),
  T('social-robot', 'Social Robot', 'robot-types', 2),
  T('educational-robot', 'Educational Robot', 'robot-types', 1),
  T('toy-robot', 'Toy Robot', 'robot-types', 1),
  T('medical-robot', 'Medical Robot', 'robot-types', 2),
  T('surgical-robot', 'Surgical Robot', 'robot-types', 3),
  T('rehabilitation-robot', 'Rehabilitation Robot', 'robot-types', 3),
  T('prosthetic-robot', 'Prosthetic Robot', 'robot-types', 3),
  T('exoskeleton-types', 'Exoskeleton Types', 'robot-types', 3),
  T('military-robot', 'Military Robot', 'robot-types', 3),
  T('bomb-disposal-robot', 'Bomb Disposal Robot', 'robot-types', 3),
  T('drone-types', 'Drone Types', 'robot-types', 2),
  T('fixed-wing-uav', 'Fixed-Wing UAV', 'robot-types', 3),
  T('multirotor', 'Multirotor', 'robot-types', 2),
  T('vtol-drone', 'VTOL Drone', 'robot-types', 3),
  T('underwater-robot', 'Underwater Robot', 'robot-types', 3),
  T('rov-explained', 'ROV, Explained', 'robot-types', 3),
  T('auv-explained', 'AUV, Explained', 'robot-types', 3),
  T('space-robot', 'Space Robot', 'robot-types', 4),
  T('mars-rovers', 'Mars Rovers', 'robot-types', 3),
  T('lunar-robot', 'Lunar Robot', 'robot-types', 3),
  T('space-station-robot', 'Space Station Robot', 'robot-types', 4),
  T('satellite-servicing', 'Satellite Servicing', 'robot-types', 5),
  T('agricultural-robot-types', 'Agricultural Robot Types', 'robot-types', 2),
  T('fruit-picking-robot', 'Fruit-Picking Robot', 'robot-types', 3),
  T('weeding-robot', 'Weeding Robot', 'robot-types', 3),
  T('spraying-drone', 'Spraying Drone', 'robot-types', 2),
  T('milking-robot', 'Milking Robot', 'robot-types', 3),
  T('construction-robot', 'Construction Robot', 'robot-types', 3),
  T('inspection-robot', 'Inspection Robot', 'robot-types', 2),
  T('cleaning-robot', 'Cleaning Robot', 'robot-types', 2),
  T('security-robot', 'Security Robot', 'robot-types', 2),
  T('entertainment-robot', 'Entertainment Robot', 'robot-types', 2),
  T('soft-robot-types', 'Soft Robot Types', 'robot-types', 3),
  T('microrobot', 'Microrobot', 'robot-types', 4),
  T('nanorobot', 'Nanorobot', 'robot-types', 5),
  T('swarm-robot', 'Swarm Robot', 'robot-types', 4),
]

const FAMOUS: TopicSeed[] = [
  T('spot-boston-dynamics', 'Spot (Boston Dynamics)', 'famous', 2),
  T('atlas-robot-bd', 'Atlas (Boston Dynamics)', 'famous', 3),
  T('stretch-robot-bd', 'Stretch (Boston Dynamics)', 'famous', 3),
  T('optimus-tesla-robot', 'Optimus (Tesla)', 'famous', 3),
  T('figure-humanoid', 'Figure (Humanoid)', 'famous', 3),
  T('agility-digit', 'Digit (Agility Robotics)', 'famous', 3),
  T('unitree-robots', 'Unitree Robots', 'famous', 3),
  T('boston-dynamics-history', 'Boston Dynamics History', 'famous', 2),
  T('abb-robotics', 'ABB Robotics', 'famous', 2),
  T('fanuc-robots', 'FANUC Robots', 'famous', 2),
  T('kuka-history', 'KUKA History', 'famous', 2),
  T('yaskawa-robots', 'Yaskawa Robots', 'famous', 2),
  T('universal-robots', 'Universal Robots', 'famous', 2),
  T('rethink-robotics', 'Rethink Robotics', 'famous', 3),
  T('fetch-robotics', 'Fetch Robotics', 'famous', 3),
  T('locus-robotics', 'Locus Robotics', 'famous', 3),
  T('6-river-systems', '6 River Systems', 'famous', 3),
  T('irobot-roomba', 'iRobot Roomba', 'famous', 1),
  T('amazon-robotics', 'Amazon Robotics', 'famous', 2),
  T('boston-dynamics-acquisition', 'Boston Dynamics Acquisitions', 'famous', 2),
  T('softbank-pepper', 'SoftBank Pepper', 'famous', 2),
  T('honda-asimo', 'Honda ASIMO', 'famous', 2),
  T('toyota-t-hr3', 'Toyota T-HR3', 'famous', 3),
  T('sony-aibo', 'Sony Aibo', 'famous', 2),
  T('boston-dynamics-spot-uses', 'Boston Dynamics Spot — Uses', 'famous', 2),
  T('da-vinci-surgical-system', 'da Vinci Surgical System', 'famous', 3),
  T('intuitive-surgical', 'Intuitive Surgical', 'famous', 3),
  T('medtronic-robots', 'Medtronic Robots', 'famous', 3),
  T('stryker-mako', 'Stryker Mako', 'famous', 3),
  T('nasa-perseverance', 'NASA Perseverance', 'famous', 3),
  T('nasa-ingenuity', 'NASA Ingenuity', 'famous', 3),
  T('nasa-opportunity', 'NASA Opportunity', 'famous', 3),
  T('iss-canadarm', 'ISS Canadarm', 'famous', 3),
  T('robonaut', 'Robonaut', 'famous', 3),
  T('shadow-robot-hand', 'Shadow Robot Hand', 'famous', 4),
  T('festo-bionic', 'Festo Bionic Robots', 'famous', 4),
  T('hanson-sophia', 'Hanson Robotics Sophia', 'famous', 2),
  T('engineered-arts-ameca', 'Engineered Arts Ameca', 'famous', 3),
  T('nao-robot', 'NAO Robot', 'famous', 2),
  T('pepper-robot', 'Pepper Robot', 'famous', 2),
  T('pioneer-robots', 'Pioneer Robots', 'famous', 3),
]

const MECHANICAL: TopicSeed[] = [
  T('cad-for-robots', 'CAD for Robots', 'mechanical-design', 2),
  T('solidworks-basics', 'SolidWorks Basics', 'mechanical-design', 2),
  T('fusion360-basics', 'Fusion 360 Basics', 'mechanical-design', 2),
  T('onshape-robotics', 'Onshape for Robotics', 'mechanical-design', 2),
  T('3d-printing-robots', '3D Printing Robots', 'mechanical-design', 2),
  T('fdm-printing', 'FDM Printing', 'mechanical-design', 2),
  T('sla-printing', 'SLA Printing', 'mechanical-design', 2),
  T('material-selection', 'Material Selection', 'mechanical-design', 3),
  T('pla-vs-abs-vs-petg', 'PLA vs. ABS vs. PETG', 'mechanical-design', 2),
  T('carbon-fiber-robotics', 'Carbon Fiber in Robotics', 'mechanical-design', 3),
  T('aluminum-extrusion', 'Aluminum Extrusion', 'mechanical-design', 2),
  T('steel-in-robots', 'Steel in Robots', 'mechanical-design', 2),
  T('titanium-robotics', 'Titanium in Robotics', 'mechanical-design', 4),
  T('design-for-manufacturing', 'Design for Manufacturing (DFM)', 'mechanical-design', 3),
  T('design-for-assembly', 'Design for Assembly (DFA)', 'mechanical-design', 3),
  T('tolerances-fits', 'Tolerances & Fits', 'mechanical-design', 3),
  T('fasteners-robots', 'Fasteners in Robots', 'mechanical-design', 1),
  T('bolts-nuts-screws', 'Bolts, Nuts, Screws', 'mechanical-design', 1),
  T('threaded-inserts', 'Threaded Inserts', 'mechanical-design', 2),
  T('press-fit-joints', 'Press-Fit Joints', 'mechanical-design', 3),
  T('snap-fit-design', 'Snap-Fit Design', 'mechanical-design', 3),
  T('welding-robots', 'Welding Robots', 'mechanical-design', 2),
  T('laser-cutting', 'Laser Cutting', 'mechanical-design', 2),
  T('cnc-machining', 'CNC Machining', 'mechanical-design', 3),
  T('waterjet-cutting', 'Waterjet Cutting', 'mechanical-design', 3),
  T('injection-molding-robots', 'Injection Molding (Robots)', 'mechanical-design', 3),
  T('linkage-mechanisms', 'Linkage Mechanisms', 'mechanical-design', 3),
  T('four-bar-linkage', 'Four-Bar Linkage', 'mechanical-design', 3),
  T('crank-slider', 'Crank-Slider', 'mechanical-design', 3),
  T('cam-mechanisms', 'Cam Mechanisms', 'mechanical-design', 3),
  T('ratchet-pawl', 'Ratchet & Pawl', 'mechanical-design', 3),
  T('differential-mechanism', 'Differential Mechanism', 'mechanical-design', 3),
  T('epicyclic-gear', 'Epicyclic Gear', 'mechanical-design', 4),
  T('cable-routing', 'Cable Routing', 'mechanical-design', 2),
  T('wire-management', 'Wire Management', 'mechanical-design', 2),
  T('bearing-types', 'Bearing Types', 'mechanical-design', 2),
  T('rolling-bearing', 'Rolling Bearing', 'mechanical-design', 2),
  T('plain-bearing', 'Plain Bearing', 'mechanical-design', 2),
  T('linear-bearing', 'Linear Bearing', 'mechanical-design', 2),
  T('ball-bearing', 'Ball Bearing', 'mechanical-design', 2),
  T('bushing-explained', 'Bushing, Explained', 'mechanical-design', 2),
  T('seal-types', 'Seal Types', 'mechanical-design', 2),
  T('lubrication-robotics', 'Lubrication in Robotics', 'mechanical-design', 2),
  T('vibration-isolation', 'Vibration Isolation', 'mechanical-design', 3),
  T('structural-analysis', 'Structural Analysis', 'mechanical-design', 4),
  T('finite-element-analysis', 'Finite Element Analysis (FEA)', 'mechanical-design', 4),
  T('topology-optimization', 'Topology Optimization', 'mechanical-design', 5),
  T('weight-reduction', 'Weight Reduction', 'mechanical-design', 3),
  T('modularity-design', 'Modularity in Design', 'mechanical-design', 3),
  T('plug-and-play-hardware', 'Plug-and-Play Hardware', 'mechanical-design', 2),
  T('hot-swap-components', 'Hot-Swap Components', 'mechanical-design', 3),
]

const APPLICATIONS: TopicSeed[] = [
  T('healthcare-robotics-deep', 'Healthcare Robotics — Deep Dive', 'applications', 3),
  T('surgery-robotics-deep', 'Surgery Robotics — Deep Dive', 'applications', 4),
  T('rehabilitation-robotics-deep', 'Rehabilitation Robotics — Deep Dive', 'applications', 3),
  T('elderly-care-robots', 'Elderly Care Robots', 'applications', 3),
  T('mental-health-robots', 'Mental Health Robots', 'applications', 3),
  T('drug-dispensing-robot', 'Drug-Dispensing Robot', 'applications', 2),
  T('lab-automation', 'Lab Automation', 'applications', 3),
  T('agriculture-robotics-deep', 'Agriculture Robotics — Deep Dive', 'applications', 3),
  T('precision-agriculture', 'Precision Agriculture', 'applications', 3),
  T('vertical-farming-robots', 'Vertical Farming Robots', 'applications', 3),
  T('greenhouse-automation', 'Greenhouse Automation', 'applications', 3),
  T('livestock-monitoring', 'Livestock Monitoring', 'applications', 2),
  T('crop-monitoring-drone', 'Crop-Monitoring Drone', 'applications', 2),
  T('food-processing-robots', 'Food Processing Robots', 'applications', 2),
  T('manufacturing-robotics-deep', 'Manufacturing Robotics — Deep Dive', 'applications', 3),
  T('automotive-manufacturing', 'Automotive Manufacturing', 'applications', 3),
  T('electronics-manufacturing', 'Electronics Manufacturing', 'applications', 3),
  T('aerospace-manufacturing', 'Aerospace Manufacturing', 'applications', 4),
  T('semiconductor-robots', 'Semiconductor Robots', 'applications', 4),
  T('quality-control-robots', 'Quality Control Robots', 'applications', 3),
  T('welding-robot', 'Welding Robot', 'applications', 2),
  T('painting-robot', 'Painting Robot', 'applications', 2),
  T('assembly-line-robots', 'Assembly Line Robots', 'applications', 2),
  T('logistics-robotics', 'Logistics Robotics', 'applications', 2),
  T('warehouse-automation', 'Warehouse Automation', 'applications', 2),
  T('sortation-systems', 'Sortation Systems', 'applications', 3),
  T('goods-to-person', 'Goods-to-Person', 'applications', 3),
  T('last-mile-delivery', 'Last-Mile Delivery', 'applications', 2),
  T('autonomous-truck', 'Autonomous Truck', 'applications', 4),
  T('construction-robotics', 'Construction Robotics', 'applications', 3),
  T('bricklaying-robot', 'Bricklaying Robot', 'applications', 3),
  T('3d-printing-construction', '3D Printing Construction', 'applications', 4),
  T('demolition-robots', 'Demolition Robots', 'applications', 3),
  T('mining-robots', 'Mining Robots', 'applications', 3),
  T('oil-gas-robots', 'Oil & Gas Robots', 'applications', 3),
  T('nuclear-robots', 'Nuclear Robots', 'applications', 4),
  T('offshore-robots', 'Offshore Robots', 'applications', 4),
  T('environmental-robots', 'Environmental Robots', 'applications', 3),
  T('ocean-cleanup-robots', 'Ocean Cleanup Robots', 'applications', 3),
  T('pipeline-inspection', 'Pipeline Inspection', 'applications', 3),
  T('bridge-inspection', 'Bridge Inspection', 'applications', 3),
  T('facade-cleaning-robot', 'Façade Cleaning Robot', 'applications', 3),
  T('retail-robots', 'Retail Robots', 'applications', 2),
  T('hotel-robots', 'Hotel Robots', 'applications', 2),
  T('restaurant-robots', 'Restaurant Robots', 'applications', 2),
  T('airport-robots', 'Airport Robots', 'applications', 2),
  T('space-applications-robots', 'Space Applications (Robots)', 'applications', 4),
  T('satellite-assembly', 'Satellite Assembly', 'applications', 4),
  T('planetary-exploration', 'Planetary Exploration', 'applications', 4),
  T('asteroid-mining', 'Asteroid Mining', 'applications', 5),
]

const SOFT: TopicSeed[] = [
  T('soft-robotics-explained', 'Soft Robotics, Explained', 'soft-robotics', 2),
  T('soft-vs-rigid-robots', 'Soft vs. Rigid Robots', 'soft-robotics', 2),
  T('bio-inspired-robots', 'Bio-Inspired Robots', 'soft-robotics', 3),
  T('soft-actuator-physics', 'Soft Actuator Physics', 'soft-robotics', 4),
  T('pneumatic-soft-actuator', 'Pneumatic Soft Actuator', 'soft-robotics', 3),
  T('hydraulic-soft-actuator', 'Hydraulic Soft Actuator', 'soft-robotics', 4),
  T('dielectric-elastomer-actuator', 'Dielectric Elastomer Actuator', 'soft-robotics', 5),
  T('ionic-polymer-metal', 'Ionic Polymer-Metal Composite', 'soft-robotics', 5),
  T('shape-memory-polymer', 'Shape Memory Polymer', 'soft-robotics', 4),
  T('granular-jamming', 'Granular Jamming', 'soft-robotics', 4),
  T('soft-gripper-design', 'Soft Gripper Design', 'soft-robotics', 3),
  T('fiber-reinforced-actuator', 'Fiber-Reinforced Actuator', 'soft-robotics', 4),
  T('soft-robot-fabrication', 'Soft Robot Fabrication', 'soft-robotics', 4),
  T('silicone-molding', 'Silicone Molding', 'soft-robotics', 3),
  T('multi-material-printing', 'Multi-Material Printing', 'soft-robotics', 4),
  T('soft-sensor', 'Soft Sensor', 'soft-robotics', 4),
  T('stretchable-electronics', 'Stretchable Electronics', 'soft-robotics', 5),
  T('embedded-pneumatics', 'Embedded Pneumatics', 'soft-robotics', 4),
  T('soft-robot-control', 'Soft Robot Control', 'soft-robotics', 5),
  T('model-free-soft-control', 'Model-Free Soft Robot Control', 'soft-robotics', 5),
  T('machine-learning-soft-robots', 'Machine Learning for Soft Robots', 'soft-robotics', 5),
  T('crawling-soft-robot', 'Crawling Soft Robot', 'soft-robotics', 3),
  T('swimming-soft-robot', 'Swimming Soft Robot', 'soft-robotics', 3),
  T('snake-soft-robot', 'Snake-Like Soft Robot', 'soft-robotics', 3),
  T('wearable-soft-robot', 'Wearable Soft Robot', 'soft-robotics', 4),
  T('soft-exosuit', 'Soft Exosuit', 'soft-robotics', 4),
  T('rehabilitation-soft-robot', 'Rehabilitation Soft Robot', 'soft-robotics', 4),
  T('medical-soft-robot', 'Medical Soft Robot', 'soft-robotics', 4),
  T('swallowable-robot', 'Swallowable Robot', 'soft-robotics', 5),
  T('capsule-endoscopy-robot', 'Capsule Endoscopy Robot', 'soft-robotics', 4),
]

const SWARM: TopicSeed[] = [
  T('swarm-robotics-explained', 'Swarm Robotics, Explained', 'swarm', 3),
  T('swarm-intelligence', 'Swarm Intelligence', 'swarm', 3),
  T('stigmergy', 'Stigmergy', 'swarm', 4),
  T('pheromone-algorithms', 'Pheromone Algorithms', 'swarm', 4),
  T('ant-colony-optimization', 'Ant Colony Optimization', 'swarm', 4),
  T('particle-swarm-optimization', 'Particle Swarm Optimization', 'swarm', 4),
  T('boid-algorithm', 'Boid Algorithm', 'swarm', 3),
  T('flocking-behaviour', 'Flocking Behaviour', 'swarm', 3),
  T('collective-decision-making', 'Collective Decision Making', 'swarm', 4),
  T('quorum-sensing-robots', 'Quorum Sensing in Robots', 'swarm', 4),
  T('task-allocation-swarm', 'Task Allocation (Swarm)', 'swarm', 4),
  T('self-organization', 'Self-Organization', 'swarm', 4),
  T('emergence-robotics', 'Emergence in Robotics', 'swarm', 4),
  T('scalability-swarms', 'Scalability of Swarms', 'swarm', 4),
  T('fault-tolerance-swarms', 'Fault Tolerance in Swarms', 'swarm', 4),
  T('robot-communication-swarm', 'Robot Communication (Swarm)', 'swarm', 3),
  T('local-vs-global-info', 'Local vs. Global Information', 'swarm', 3),
  T('swarm-mapping', 'Swarm Mapping', 'swarm', 4),
  T('swarm-construction', 'Swarm Construction', 'swarm', 4),
  T('swarm-search-rescue', 'Swarm Search & Rescue', 'swarm', 4),
  T('aerial-swarm', 'Aerial Swarm', 'swarm', 4),
  T('ground-swarm', 'Ground Swarm', 'swarm', 3),
  T('heterogeneous-swarm', 'Heterogeneous Swarm', 'swarm', 4),
  T('miniaturized-robots', 'Miniaturized Robots', 'swarm', 4),
  T('kilobot-explained', 'Kilobot, Explained', 'swarm', 3),
]

const ETHICS: TopicSeed[] = [
  T('robot-safety-standards', 'Robot Safety Standards', 'ethics-safety', 3),
  T('iso-10218-explained', 'ISO 10218, Explained', 'ethics-safety', 4),
  T('iso-ts-15066', 'ISO/TS 15066', 'ethics-safety', 4),
  T('robot-risk-assessment', 'Robot Risk Assessment', 'ethics-safety', 4),
  T('safety-functions', 'Safety Functions', 'ethics-safety', 3),
  T('emergency-stop', 'Emergency Stop', 'ethics-safety', 2),
  T('speed-force-limiting', 'Speed & Force Limiting', 'ethics-safety', 3),
  T('functional-safety', 'Functional Safety', 'ethics-safety', 4),
  T('iec-61508', 'IEC 61508', 'ethics-safety', 4),
  T('machinery-directive', 'Machinery Directive', 'ethics-safety', 4),
  T('ce-marking-robots', 'CE Marking (Robots)', 'ethics-safety', 3),
  T('robot-insurance', 'Robot Insurance', 'ethics-safety', 3),
  T('liability-robots', 'Liability for Robots', 'ethics-safety', 4),
  T('autonomous-weapons', 'Autonomous Weapons', 'ethics-safety', 4),
  T('lethal-autonomous-weapons', 'Lethal Autonomous Weapons', 'ethics-safety', 4),
  T('robot-rights', 'Robot Rights', 'ethics-safety', 3),
  T('legal-personhood-robots', 'Legal Personhood for Robots', 'ethics-safety', 4),
  T('robots-and-jobs', 'Robots & Jobs', 'ethics-safety', 2),
  T('automation-displacement', 'Automation Displacement', 'ethics-safety', 3),
  T('future-of-work-robots', 'Future of Work (Robots)', 'ethics-safety', 3),
  T('reskilling-upskilling', 'Reskilling & Upskilling', 'ethics-safety', 2),
  T('universal-basic-income-robots', 'Universal Basic Income (Robotics)', 'ethics-safety', 3),
  T('ai-bias-robotics', 'AI Bias in Robotics', 'ethics-safety', 4),
  T('fairness-robotics', 'Fairness in Robotics', 'ethics-safety', 4),
  T('privacy-surveillance-robots', 'Privacy & Surveillance Robots', 'ethics-safety', 3),
  T('robot-in-public', 'Robots in Public Spaces', 'ethics-safety', 3),
  T('regulations-autonomous-vehicles', 'Regulations for Autonomous Vehicles', 'ethics-safety', 3),
  T('drone-regulations-india', 'Drone Regulations (India)', 'ethics-safety', 3),
  T('drone-regulations-global', 'Drone Regulations (Global)', 'ethics-safety', 3),
  T('data-privacy-robots', 'Data Privacy (Robots)', 'ethics-safety', 3),
  T('cybersecurity-robots', 'Cybersecurity for Robots', 'ethics-safety', 4),
  T('robot-hacking', 'Robot Hacking', 'ethics-safety', 4),
  T('adversarial-attacks', 'Adversarial Attacks', 'ethics-safety', 5),
  T('environmental-impact-robots', 'Environmental Impact of Robots', 'ethics-safety', 3),
  T('robot-ewaste', 'Robot E-Waste', 'ethics-safety', 3),
]

const FUTURE: TopicSeed[] = [
  T('general-purpose-robot', 'General-Purpose Robot', 'future', 4),
  T('humanoid-future', 'Humanoid Future', 'future', 4),
  T('robot-consciousness', 'Robot Consciousness', 'future', 5),
  T('agi-robotics', 'AGI & Robotics', 'future', 5),
  T('whole-body-loco-manipulation', 'Whole-Body Loco-Manipulation', 'future', 5),
  T('foundation-models-robotics', 'Foundation Models in Robotics', 'future', 5),
  T('large-language-model-robots', 'Large Language Models for Robots', 'future', 4),
  T('multimodal-ai-robots', 'Multimodal AI for Robots', 'future', 5),
  T('world-model-robots', 'World Models for Robots', 'future', 5),
  T('robot-internet', 'Robot Internet', 'future', 4),
  T('cloud-robotics', 'Cloud Robotics', 'future', 3),
  T('5g-robotics', '5G in Robotics', 'future', 3),
  T('quantum-computing-robots', 'Quantum Computing for Robots', 'future', 5),
  T('neuromorphic-computing', 'Neuromorphic Computing', 'future', 5),
  T('memristor-robots', 'Memristor in Robots', 'future', 5),
  T('dna-computing-robots', 'DNA Computing in Robots', 'future', 5),
  T('molecular-robots', 'Molecular Robots', 'future', 5),
  T('nanorobotics-future', 'Nanorobotics Future', 'future', 5),
  T('biorobotics', 'Biorobotics', 'future', 4),
  T('cyborg-technology', 'Cyborg Technology', 'future', 4),
  T('brain-computer-interface-future', 'Brain-Computer Interface Future', 'future', 5),
  T('human-enhancement', 'Human Enhancement', 'future', 4),
  T('robot-economy', 'Robot Economy', 'future', 3),
  T('robot-as-a-service', 'Robot-as-a-Service (RaaS)', 'future', 3),
  T('robotics-in-india-2030', 'Robotics in India 2030', 'future', 3),
]

export const NEW_TOPICS: TopicSeed[] = [
  ...FOUNDATIONS,
  ...ELECTRONICS,
  ...SENSORS,
  ...ACTUATORS,
  ...CONTROL_SYSTEMS,
  ...ARMS_MANIPULATION,
  ...MOBILE_ROBOTS,
  ...NAVIGATION_SLAM,
  ...COMPUTER_VISION,
  ...AI_ML,
  ...PROGRAMMING,
  ...HRI,
  ...ROBOT_TYPES,
  ...FAMOUS,
  ...MECHANICAL,
  ...APPLICATIONS,
  ...SOFT,
  ...SWARM,
  ...ETHICS,
  ...FUTURE,
]

// Sanity counts (run `npx tsx scripts/atlas-topics-list.ts` to print)
if (require.main === module) {
  const byBucket = new Map<string, number>()
  for (const t of NEW_TOPICS) {
    byBucket.set(t.bucket, (byBucket.get(t.bucket) ?? 0) + 1)
  }
  console.log(`Total new topics: ${NEW_TOPICS.length}`)
  for (const b of BUCKETS) {
    console.log(`  ${b.id}: ${byBucket.get(b.id) ?? 0} (target ${b.targetCount})`)
  }
}

// ─── Reading paths ─────────────────────────────────────────────────────────

export interface ReadingPath {
  id: string
  title: string
  emoji: string
  color: string
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  description: string
  estimatedMinutes: number
  concepts: string[]   // slugs in order
}

export const READING_PATHS: ReadingPath[] = [
  {
    id: 'robot-basics',
    title: 'Robot Basics',
    emoji: '🤖',
    color: '#6366f1',
    level: 'Beginner',
    description: 'Perfect first path. 8 concepts, ~45 minutes.',
    estimatedMinutes: 45,
    concepts: [
      'sensor', 'actuator', 'controller', 'feedback-loop',
      'pid-controller', 'differential-drive-deep', 'arduino-explained', 'python-for-robotics',
    ],
  },
  {
    id: 'computer-vision',
    title: 'See Like a Robot',
    emoji: '👁️',
    color: '#0891b2',
    level: 'Intermediate',
    description: 'How robots understand what they see. 12 concepts.',
    estimatedMinutes: 90,
    concepts: [
      'camera-calibration', 'image-basics', 'feature-detection',
      'object-detection-explained', 'yolo-explained', 'optical-flow',
      'depth-from-stereo', 'slam-explained', 'visual-slam', 'orb-slam',
      'semantic-segmentation', 'pose-estimation-vision',
    ],
  },
  {
    id: 'build-robot-arm',
    title: 'Build a Robot Arm',
    emoji: '🦾',
    color: '#16a34a',
    level: 'Intermediate',
    description: 'From motors to manipulation. 10 concepts.',
    estimatedMinutes: 75,
    concepts: [
      'servo-motor-types', 'dof-degrees-of-freedom', 'forward-kinematics-deep',
      'inverse-kinematics-deep', 'jacobian-matrix', 'pid-controller',
      'gripper-types', 'trajectory-planning-arms', 'ros2-moveit2', 'assembly-robotics',
    ],
  },
  {
    id: 'self-driving-101',
    title: 'Self-Driving 101',
    emoji: '🚗',
    color: '#dc2626',
    level: 'Advanced',
    description: 'How autonomous cars work. 15 concepts.',
    estimatedMinutes: 120,
    concepts: [
      'lidar-types', 'camera-calibration', 'sensor-fusion-basics',
      'object-detection-explained', 'slam-explained', 'path-planning-explained',
      'a-star-algorithm', 'pid-controller', 'model-predictive-control',
      'ackermann-steering-deep', 'occupancy-grid', 'kalman-filter-sensors',
      'particle-filter', 'amcl-explained', 'cybersecurity-robots',
    ],
  },
  {
    id: 'ai-for-robots',
    title: 'AI for Robots',
    emoji: '🧠',
    color: '#7c3aed',
    level: 'Advanced',
    description: 'Machine learning meets robotics. 12 concepts.',
    estimatedMinutes: 100,
    concepts: [
      'neural-network-deep', 'cnn-explained', 'reinforcement-learning-deep',
      'q-learning', 'proximal-policy-optimization', 'imitation-learning',
      'sim-to-real', 'domain-randomization', 'foundation-models-robotics',
      'large-language-model-robots', 'multimodal-ai-robots', 'world-model-robots',
    ],
  },
]
