/**
 * scripts/seed-atlas.ts
 *
 * One-shot script. Reads every MDX file in content/atlas/, parses the
 * frontmatter, and upserts each entry into the atlas_entries table in Supabase.
 *
 * If OPENAI_API_KEY is set, it also generates a 1536-dim embedding per entry
 * via text-embedding-3-small. Those embeddings are what powers RAG on the
 * R2 Co-pilot. Without them, the Co-pilot still works — it just can't ground
 * its answers in the Atlas.
 *
 * Run: npm run seed:atlas
 *
 * Hybrid model: MDX files in this repo remain the canonical source. The
 * database is purely a search index that's regenerated by running this script.
 * Editing an MDX file → push → re-run this script.
 */

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

// Load .env.local (dotenv/config would only load .env, which we don't use).
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;
const OPENAI_KEY = process.env.OPENAI_API_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const CONTENT_DIR = path.join(process.cwd(), 'content', 'atlas');
const VALID_TYPES = ['concept', 'person', 'company', 'robot', 'paper'] as const;
type AtlasType = (typeof VALID_TYPES)[number];

function normalizeDate(v: unknown): string {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (typeof v === 'string' && v.length > 0) return v.slice(0, 10);
  return new Date().toISOString().slice(0, 10);
}

async function embed(text: string): Promise<number[] | null> {
  if (!OPENAI_KEY) return null;

  // text-embedding-3-small: 1536 dims, max 8191 tokens (~ 32k chars).
  // We truncate to 30k chars to stay safely under the limit without tokenizing.
  const input = text.slice(0, 30_000);

  const res = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_KEY}`,
    },
    body: JSON.stringify({
      model: 'text-embedding-3-small',
      input,
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`OpenAI embeddings API error ${res.status}: ${errText}`);
  }

  const json = (await res.json()) as { data: { embedding: number[] }[] };
  return json.data[0].embedding;
}

type Frontmatter = {
  title?: string;
  summary?: string;
  seeAlso?: string[];
  sources?: { title: string; url: string }[];
  lastReviewed?: string;
  tags?: string[];
};

async function seed() {
  if (!fs.existsSync(CONTENT_DIR)) {
    console.error(`No content directory at ${CONTENT_DIR}`);
    process.exit(1);
  }

  if (!OPENAI_KEY) {
    console.log('⚠️  OPENAI_API_KEY not set — embeddings will be NULL.');
    console.log('   RAG search will return no results until you re-seed with the key.\n');
  } else {
    console.log('✓ OPENAI_API_KEY found — generating embeddings via text-embedding-3-small\n');
  }

  let inserted = 0;
  let failed = 0;

  for (const type of fs.readdirSync(CONTENT_DIR)) {
    const dir = path.join(CONTENT_DIR, type);
    if (!fs.statSync(dir).isDirectory()) continue;
    if (!(VALID_TYPES as readonly string[]).includes(type)) continue;
    const atlasType = type as AtlasType;

    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.mdx') && !file.endsWith('.md')) continue;
      const slug = file.replace(/\.(mdx|md)$/, '');
      const raw = fs.readFileSync(path.join(dir, file), 'utf8');
      const { data, content } = matter(raw);
      const fm = data as Frontmatter;

      const title = fm.title ?? slug;
      const summary = fm.summary ?? '';
      const bodyMd = content;

      try {
        const embedding = await embed(`${title}\n\n${summary}\n\n${bodyMd}`);

        const { error } = await supabase
          .from('atlas_entries')
          .upsert(
            {
              type: atlasType,
              slug,
              title,
              summary,
              body_md: bodyMd,
              see_also: fm.seeAlso ?? [],
              sources: fm.sources ?? [],
              tags: fm.tags ?? [],
              last_reviewed_at: normalizeDate(fm.lastReviewed),
              embedding,
            },
            { onConflict: 'type,slug' },
          );

        if (error) {
          console.error(`  ✗ ${type}/${slug} — ${error.message}`);
          failed++;
        } else {
          console.log(`  ✓ ${type}/${slug}${embedding ? '  (embedded)' : ''}`);
          inserted++;
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`  ✗ ${type}/${slug} — ${msg}`);
        failed++;
      }
    }
  }

  console.log(`\nDone. ${inserted} upserted, ${failed} failed.`);
  process.exit(failed > 0 ? 1 : 0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
